/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_CMSERR_H
# define ossl_OPENSSL_CMSERR_H
# pragma once

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/cryptoerr_legacy.h"


# ifndef ossl_OPENSSL_NO_CMS


/*
 * CMS reason codes.
 */
#  define ossl_CMS_R_ADD_SIGNER_ERROR                           99
#  define ossl_CMS_R_ATTRIBUTE_ERROR                            161
#  define ossl_CMS_R_CERTIFICATE_ALREADY_PRESENT                175
#  define ossl_CMS_R_CERTIFICATE_HAS_NO_KEYID                   160
#  define ossl_CMS_R_CERTIFICATE_VERIFY_ERROR                   100
#  define ossl_CMS_R_CIPHER_AEAD_SET_TAG_ERROR                  184
#  define ossl_CMS_R_CIPHER_GET_TAG                             185
#  define ossl_CMS_R_CIPHER_INITIALISATION_ERROR                101
#  define ossl_CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR      102
#  define ossl_CMS_R_CMS_DATAFINAL_ERROR                        103
#  define ossl_CMS_R_CMS_LIB                                    104
#  define ossl_CMS_R_CONTENTIDENTIFIER_MISMATCH                 170
#  define ossl_CMS_R_CONTENT_NOT_FOUND                          105
#  define ossl_CMS_R_CONTENT_TYPE_MISMATCH                      171
#  define ossl_CMS_R_CONTENT_TYPE_NOT_COMPRESSED_DATA           106
#  define ossl_CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA            107
#  define ossl_CMS_R_CONTENT_TYPE_NOT_SIGNED_DATA               108
#  define ossl_CMS_R_CONTENT_VERIFY_ERROR                       109
#  define ossl_CMS_R_CTRL_ERROR                                 110
#  define ossl_CMS_R_CTRL_FAILURE                               111
#  define ossl_CMS_R_DECODE_ERROR                               187
#  define ossl_CMS_R_DECRYPT_ERROR                              112
#  define ossl_CMS_R_ERROR_GETTING_PUBLIC_KEY                   113
#  define ossl_CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE      114
#  define ossl_CMS_R_ERROR_SETTING_KEY                          115
#  define ossl_CMS_R_ERROR_SETTING_RECIPIENTINFO                116
#  define ossl_CMS_R_ESS_SIGNING_CERTID_MISMATCH_ERROR          183
#  define ossl_CMS_R_INVALID_ENCRYPTED_KEY_LENGTH               117
#  define ossl_CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER           176
#  define ossl_CMS_R_INVALID_KEY_LENGTH                         118
#  define ossl_CMS_R_INVALID_LABEL                              190
#  define ossl_CMS_R_INVALID_OAEP_PARAMETERS                    191
#  define ossl_CMS_R_KDF_PARAMETER_ERROR                        186
#  define ossl_CMS_R_MD_BIO_INIT_ERROR                          119
#  define ossl_CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH       120
#  define ossl_CMS_R_MESSAGEDIGEST_WRONG_LENGTH                 121
#  define ossl_CMS_R_MSGSIGDIGEST_ERROR                         172
#  define ossl_CMS_R_MSGSIGDIGEST_VERIFICATION_FAILURE          162
#  define ossl_CMS_R_MSGSIGDIGEST_WRONG_LENGTH                  163
#  define ossl_CMS_R_NEED_ONE_SIGNER                            164
#  define ossl_CMS_R_NOT_A_SIGNED_RECEIPT                       165
#  define ossl_CMS_R_NOT_ENCRYPTED_DATA                         122
#  define ossl_CMS_R_NOT_KEK                                    123
#  define ossl_CMS_R_NOT_KEY_AGREEMENT                          181
#  define ossl_CMS_R_NOT_KEY_TRANSPORT                          124
#  define ossl_CMS_R_NOT_PWRI                                   177
#  define ossl_CMS_R_NOT_SUPPORTED_FOR_THIS_KEY_TYPE            125
#  define ossl_CMS_R_NO_CIPHER                                  126
#  define ossl_CMS_R_NO_CONTENT                                 127
#  define ossl_CMS_R_NO_CONTENT_TYPE                            173
#  define ossl_CMS_R_NO_DEFAULT_DIGEST                          128
#  define ossl_CMS_R_NO_DIGEST_SET                              129
#  define ossl_CMS_R_NO_KEY                                     130
#  define ossl_CMS_R_NO_KEY_OR_CERT                             174
#  define ossl_CMS_R_NO_MATCHING_DIGEST                         131
#  define ossl_CMS_R_NO_MATCHING_RECIPIENT                      132
#  define ossl_CMS_R_NO_MATCHING_SIGNATURE                      166
#  define ossl_CMS_R_NO_MSGSIGDIGEST                            167
#  define ossl_CMS_R_NO_PASSWORD                                178
#  define ossl_CMS_R_NO_PRIVATE_KEY                             133
#  define ossl_CMS_R_NO_PUBLIC_KEY                              134
#  define ossl_CMS_R_NO_RECEIPT_REQUEST                         168
#  define ossl_CMS_R_NO_SIGNERS                                 135
#  define ossl_CMS_R_PEER_KEY_ERROR                             188
#  define ossl_CMS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE     136
#  define ossl_CMS_R_RECEIPT_DECODE_ERROR                       169
#  define ossl_CMS_R_RECIPIENT_ERROR                            137
#  define ossl_CMS_R_SHARED_INFO_ERROR                          189
#  define ossl_CMS_R_SIGNER_CERTIFICATE_NOT_FOUND               138
#  define ossl_CMS_R_SIGNFINAL_ERROR                            139
#  define ossl_CMS_R_SMIME_TEXT_ERROR                           140
#  define ossl_CMS_R_STORE_INIT_ERROR                           141
#  define ossl_CMS_R_TYPE_NOT_COMPRESSED_DATA                   142
#  define ossl_CMS_R_TYPE_NOT_DATA                              143
#  define ossl_CMS_R_TYPE_NOT_DIGESTED_DATA                     144
#  define ossl_CMS_R_TYPE_NOT_ENCRYPTED_DATA                    145
#  define ossl_CMS_R_TYPE_NOT_ENVELOPED_DATA                    146
#  define ossl_CMS_R_UNABLE_TO_FINALIZE_CONTEXT                 147
#  define ossl_CMS_R_UNKNOWN_CIPHER                             148
#  define ossl_CMS_R_UNKNOWN_DIGEST_ALGORITHM                   149
#  define ossl_CMS_R_UNKNOWN_ID                                 150
#  define ossl_CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM          151
#  define ossl_CMS_R_UNSUPPORTED_CONTENT_ENCRYPTION_ALGORITHM   194
#  define ossl_CMS_R_UNSUPPORTED_CONTENT_TYPE                   152
#  define ossl_CMS_R_UNSUPPORTED_ENCRYPTION_TYPE                192
#  define ossl_CMS_R_UNSUPPORTED_KEK_ALGORITHM                  153
#  define ossl_CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM       179
#  define ossl_CMS_R_UNSUPPORTED_LABEL_SOURCE                   193
#  define ossl_CMS_R_UNSUPPORTED_RECIPIENTINFO_TYPE             155
#  define ossl_CMS_R_UNSUPPORTED_RECIPIENT_TYPE                 154
#  define ossl_CMS_R_UNSUPPORTED_SIGNATURE_ALGORITHM            195
#  define ossl_CMS_R_UNSUPPORTED_TYPE                           156
#  define ossl_CMS_R_UNWRAP_ERROR                               157
#  define ossl_CMS_R_UNWRAP_FAILURE                             180
#  define ossl_CMS_R_VERIFICATION_FAILURE                       158
#  define ossl_CMS_R_WRAP_ERROR                                 159

# endif
#endif
