/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_DHERR_H
# define ossl_OPENSSL_DHERR_H
# pragma once

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/cryptoerr_legacy.h"


# ifndef ossl_OPENSSL_NO_DH


/*
 * ossl_DH reason codes.
 */
#  define ossl_DH_R_BAD_FFC_PARAMETERS                          127
#  define ossl_DH_R_BAD_GENERATOR                               101
#  define ossl_DH_R_BN_DECODE_ERROR                             109
#  define ossl_DH_R_BN_ERROR                                    106
#  define ossl_DH_R_CHECK_INVALID_J_VALUE                       115
#  define ossl_DH_R_CHECK_INVALID_Q_VALUE                       116
#  define ossl_DH_R_CHECK_PUBKEY_INVALID                        122
#  define ossl_DH_R_CHECK_PUBKEY_TOO_LARGE                      123
#  define ossl_DH_R_CHECK_PUBKEY_TOO_SMALL                      124
#  define ossl_DH_R_CHECK_P_NOT_PRIME                           117
#  define ossl_DH_R_CHECK_P_NOT_SAFE_PRIME                      118
#  define ossl_DH_R_CHECK_Q_NOT_PRIME                           119
#  define ossl_DH_R_DECODE_ERROR                                104
#  define ossl_DH_R_INVALID_PARAMETER_NAME                      110
#  define ossl_DH_R_INVALID_PARAMETER_NID                       114
#  define ossl_DH_R_INVALID_PUBKEY                              102
#  define ossl_DH_R_INVALID_SECRET                              128
#  define ossl_DH_R_KDF_PARAMETER_ERROR                         112
#  define ossl_DH_R_KEYS_NOT_SET                                108
#  define ossl_DH_R_MISSING_PUBKEY                              125
#  define ossl_DH_R_MODULUS_TOO_LARGE                           103
#  define ossl_DH_R_MODULUS_TOO_SMALL                           126
#  define ossl_DH_R_NOT_SUITABLE_GENERATOR                      120
#  define ossl_DH_R_NO_PARAMETERS_SET                           107
#  define ossl_DH_R_NO_PRIVATE_VALUE                            100
#  define ossl_DH_R_PARAMETER_ENCODING_ERROR                    105
#  define ossl_DH_R_PEER_KEY_ERROR                              111
#  define ossl_DH_R_Q_TOO_LARGE                                 130
#  define ossl_DH_R_SHARED_INFO_ERROR                           113
#  define ossl_DH_R_UNABLE_TO_CHECK_GENERATOR                   121

# endif
#endif
