/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_OBJECTSERR_H
# define ossl_OPENSSL_OBJECTSERR_H
# pragma once

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/cryptoerr_legacy.h"



/*
 * OBJ reason codes.
 */
# define ossl_OBJ_R_OID_EXISTS                                 102
# define ossl_OBJ_R_UNKNOWN_NID                                101
# define ossl_OBJ_R_UNKNOWN_OBJECT_NAME                        103

#endif
