/*
 * WARNING: do not edit!
 * Generated by Makefile from ../../../openssl/source/include/openssl/x509.h.in
 *
 * Copyright 1995-2022 The OpenSSL Project Authors. All Rights Reserved.
 * Copyright (c) 2002, Oracle and/or its affiliates. All rights reserved
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */



#ifndef ossl_OPENSSL_X509_H
# define ossl_OPENSSL_X509_H
# pragma once

# include "ossl/openssl/macros.h"
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#  define ossl_HEADER_X509_H
# endif

# include "ossl/openssl/e_os2.h"
# include "ossl/openssl/types.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/buffer.h"
# include "ossl/openssl/evp.h"
# include "ossl/openssl/bio.h"
# include "ossl/openssl/asn1.h"
# include "ossl/openssl/safestack.h"
# include "ossl/openssl/ec.h"

# ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
#  include "ossl/openssl/rsa.h"
#  include "ossl/openssl/dsa.h"
#  include "ossl/openssl/dh.h"
# endif

# include "ossl/openssl/sha.h"
# include "ossl/openssl/x509err.h"

#ifdef  __cplusplus
extern "C" {
#endif

/* Needed stacks for types defined in other headers */
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_NAME, ossl_X509_NAME, ossl_X509_NAME)
#define ossl_sk_X509_NAME_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_NAME_sk_type(sk))
#define ossl_sk_X509_NAME_value(sk, idx) ((ossl_X509_NAME *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_NAME_sk_type(sk), (idx)))
#define ossl_sk_X509_NAME_new(cmp) ((ossl_STACK_OF(ossl_X509_NAME) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_NAME_compfunc_type(cmp)))
#define ossl_sk_X509_NAME_new_null() ((ossl_STACK_OF(ossl_X509_NAME) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_NAME_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_NAME) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_NAME_compfunc_type(cmp), (n)))
#define ossl_sk_X509_NAME_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_NAME_sk_type(sk), (n))
#define ossl_sk_X509_NAME_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_NAME_sk_type(sk))
#define ossl_sk_X509_NAME_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_NAME_sk_type(sk))
#define ossl_sk_X509_NAME_delete(sk, i) ((ossl_X509_NAME *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_NAME_sk_type(sk), (i)))
#define ossl_sk_X509_NAME_delete_ptr(sk, ptr) ((ossl_X509_NAME *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr)))
#define ossl_sk_X509_NAME_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr))
#define ossl_sk_X509_NAME_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr))
#define ossl_sk_X509_NAME_pop(sk) ((ossl_X509_NAME *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_NAME_sk_type(sk)))
#define ossl_sk_X509_NAME_shift(sk) ((ossl_X509_NAME *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_NAME_sk_type(sk)))
#define ossl_sk_X509_NAME_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_NAME_sk_type(sk),ossl_ossl_check_X509_NAME_freefunc_type(freefunc))
#define ossl_sk_X509_NAME_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr), (idx))
#define ossl_sk_X509_NAME_set(sk, idx, ptr) ((ossl_X509_NAME *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_NAME_sk_type(sk), (idx), ossl_ossl_check_X509_NAME_type(ptr)))
#define ossl_sk_X509_NAME_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr))
#define ossl_sk_X509_NAME_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr))
#define ossl_sk_X509_NAME_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_type(ptr), pnum)
#define ossl_sk_X509_NAME_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_NAME_sk_type(sk))
#define ossl_sk_X509_NAME_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_NAME_sk_type(sk))
#define ossl_sk_X509_NAME_dup(sk) ((ossl_STACK_OF(ossl_X509_NAME) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_NAME_sk_type(sk)))
#define ossl_sk_X509_NAME_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_NAME) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_copyfunc_type(copyfunc), ossl_ossl_check_X509_NAME_freefunc_type(freefunc)))
#define ossl_sk_X509_NAME_set_cmp_func(sk, cmp) ((ossl_sk_X509_NAME_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_NAME_sk_type(sk), ossl_ossl_check_X509_NAME_compfunc_type(cmp)))
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509, ossl_X509, ossl_X509)
#define ossl_sk_X509_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_sk_type(sk))
#define ossl_sk_X509_value(sk, idx) ((ossl_X509 *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_sk_type(sk), (idx)))
#define ossl_sk_X509_new(cmp) ((ossl_STACK_OF(ossl_X509) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_compfunc_type(cmp)))
#define ossl_sk_X509_new_null() ((ossl_STACK_OF(ossl_X509) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_compfunc_type(cmp), (n)))
#define ossl_sk_X509_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_sk_type(sk), (n))
#define ossl_sk_X509_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_sk_type(sk))
#define ossl_sk_X509_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_sk_type(sk))
#define ossl_sk_X509_delete(sk, i) ((ossl_X509 *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_sk_type(sk), (i)))
#define ossl_sk_X509_delete_ptr(sk, ptr) ((ossl_X509 *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr)))
#define ossl_sk_X509_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr))
#define ossl_sk_X509_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr))
#define ossl_sk_X509_pop(sk) ((ossl_X509 *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_sk_type(sk)))
#define ossl_sk_X509_shift(sk) ((ossl_X509 *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_sk_type(sk)))
#define ossl_sk_X509_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_sk_type(sk),ossl_ossl_check_X509_freefunc_type(freefunc))
#define ossl_sk_X509_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr), (idx))
#define ossl_sk_X509_set(sk, idx, ptr) ((ossl_X509 *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_sk_type(sk), (idx), ossl_ossl_check_X509_type(ptr)))
#define ossl_sk_X509_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr))
#define ossl_sk_X509_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr))
#define ossl_sk_X509_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_type(ptr), pnum)
#define ossl_sk_X509_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_sk_type(sk))
#define ossl_sk_X509_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_sk_type(sk))
#define ossl_sk_X509_dup(sk) ((ossl_STACK_OF(ossl_X509) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_sk_type(sk)))
#define ossl_sk_X509_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_sk_type(sk), ossl_ossl_check_X509_copyfunc_type(copyfunc), ossl_ossl_check_X509_freefunc_type(freefunc)))
#define ossl_sk_X509_set_cmp_func(sk, cmp) ((ossl_sk_X509_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_sk_type(sk), ossl_ossl_check_X509_compfunc_type(cmp)))
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_REVOKED, ossl_X509_REVOKED, ossl_X509_REVOKED)
#define ossl_sk_X509_REVOKED_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_REVOKED_sk_type(sk))
#define ossl_sk_X509_REVOKED_value(sk, idx) ((ossl_X509_REVOKED *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_REVOKED_sk_type(sk), (idx)))
#define ossl_sk_X509_REVOKED_new(cmp) ((ossl_STACK_OF(ossl_X509_REVOKED) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_REVOKED_compfunc_type(cmp)))
#define ossl_sk_X509_REVOKED_new_null() ((ossl_STACK_OF(ossl_X509_REVOKED) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_REVOKED_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_REVOKED) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_REVOKED_compfunc_type(cmp), (n)))
#define ossl_sk_X509_REVOKED_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_REVOKED_sk_type(sk), (n))
#define ossl_sk_X509_REVOKED_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_REVOKED_sk_type(sk))
#define ossl_sk_X509_REVOKED_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_REVOKED_sk_type(sk))
#define ossl_sk_X509_REVOKED_delete(sk, i) ((ossl_X509_REVOKED *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_REVOKED_sk_type(sk), (i)))
#define ossl_sk_X509_REVOKED_delete_ptr(sk, ptr) ((ossl_X509_REVOKED *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr)))
#define ossl_sk_X509_REVOKED_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr))
#define ossl_sk_X509_REVOKED_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr))
#define ossl_sk_X509_REVOKED_pop(sk) ((ossl_X509_REVOKED *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_REVOKED_sk_type(sk)))
#define ossl_sk_X509_REVOKED_shift(sk) ((ossl_X509_REVOKED *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_REVOKED_sk_type(sk)))
#define ossl_sk_X509_REVOKED_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_REVOKED_sk_type(sk),ossl_ossl_check_X509_REVOKED_freefunc_type(freefunc))
#define ossl_sk_X509_REVOKED_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr), (idx))
#define ossl_sk_X509_REVOKED_set(sk, idx, ptr) ((ossl_X509_REVOKED *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_REVOKED_sk_type(sk), (idx), ossl_ossl_check_X509_REVOKED_type(ptr)))
#define ossl_sk_X509_REVOKED_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr))
#define ossl_sk_X509_REVOKED_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr))
#define ossl_sk_X509_REVOKED_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_type(ptr), pnum)
#define ossl_sk_X509_REVOKED_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_REVOKED_sk_type(sk))
#define ossl_sk_X509_REVOKED_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_REVOKED_sk_type(sk))
#define ossl_sk_X509_REVOKED_dup(sk) ((ossl_STACK_OF(ossl_X509_REVOKED) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_REVOKED_sk_type(sk)))
#define ossl_sk_X509_REVOKED_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_REVOKED) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_copyfunc_type(copyfunc), ossl_ossl_check_X509_REVOKED_freefunc_type(freefunc)))
#define ossl_sk_X509_REVOKED_set_cmp_func(sk, cmp) ((ossl_sk_X509_REVOKED_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_REVOKED_sk_type(sk), ossl_ossl_check_X509_REVOKED_compfunc_type(cmp)))
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_CRL, ossl_X509_CRL, ossl_X509_CRL)
#define ossl_sk_X509_CRL_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_CRL_sk_type(sk))
#define ossl_sk_X509_CRL_value(sk, idx) ((ossl_X509_CRL *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_CRL_sk_type(sk), (idx)))
#define ossl_sk_X509_CRL_new(cmp) ((ossl_STACK_OF(ossl_X509_CRL) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_CRL_compfunc_type(cmp)))
#define ossl_sk_X509_CRL_new_null() ((ossl_STACK_OF(ossl_X509_CRL) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_CRL_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_CRL) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_CRL_compfunc_type(cmp), (n)))
#define ossl_sk_X509_CRL_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_CRL_sk_type(sk), (n))
#define ossl_sk_X509_CRL_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_CRL_sk_type(sk))
#define ossl_sk_X509_CRL_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_CRL_sk_type(sk))
#define ossl_sk_X509_CRL_delete(sk, i) ((ossl_X509_CRL *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_CRL_sk_type(sk), (i)))
#define ossl_sk_X509_CRL_delete_ptr(sk, ptr) ((ossl_X509_CRL *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr)))
#define ossl_sk_X509_CRL_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr))
#define ossl_sk_X509_CRL_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr))
#define ossl_sk_X509_CRL_pop(sk) ((ossl_X509_CRL *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_CRL_sk_type(sk)))
#define ossl_sk_X509_CRL_shift(sk) ((ossl_X509_CRL *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_CRL_sk_type(sk)))
#define ossl_sk_X509_CRL_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_CRL_sk_type(sk),ossl_ossl_check_X509_CRL_freefunc_type(freefunc))
#define ossl_sk_X509_CRL_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr), (idx))
#define ossl_sk_X509_CRL_set(sk, idx, ptr) ((ossl_X509_CRL *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_CRL_sk_type(sk), (idx), ossl_ossl_check_X509_CRL_type(ptr)))
#define ossl_sk_X509_CRL_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr))
#define ossl_sk_X509_CRL_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr))
#define ossl_sk_X509_CRL_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_type(ptr), pnum)
#define ossl_sk_X509_CRL_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_CRL_sk_type(sk))
#define ossl_sk_X509_CRL_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_CRL_sk_type(sk))
#define ossl_sk_X509_CRL_dup(sk) ((ossl_STACK_OF(ossl_X509_CRL) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_CRL_sk_type(sk)))
#define ossl_sk_X509_CRL_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_CRL) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_copyfunc_type(copyfunc), ossl_ossl_check_X509_CRL_freefunc_type(freefunc)))
#define ossl_sk_X509_CRL_set_cmp_func(sk, cmp) ((ossl_sk_X509_CRL_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_CRL_sk_type(sk), ossl_ossl_check_X509_CRL_compfunc_type(cmp)))


/* Flags for ossl_X509_get_signature_info() */
/* Signature info is valid */
# define ossl_X509_SIG_INFO_VALID     0x1
/* Signature is suitable for TLS use */
# define ossl_X509_SIG_INFO_TLS       0x2

# define ossl_X509_FILETYPE_PEM       1
# define ossl_X509_FILETYPE_ASN1      2
# define ossl_X509_FILETYPE_DEFAULT   3

# define ossl_X509v3_KU_DIGITAL_SIGNATURE     0x0080
# define ossl_X509v3_KU_NON_REPUDIATION       0x0040
# define ossl_X509v3_KU_KEY_ENCIPHERMENT      0x0020
# define ossl_X509v3_KU_DATA_ENCIPHERMENT     0x0010
# define ossl_X509v3_KU_KEY_AGREEMENT         0x0008
# define ossl_X509v3_KU_KEY_CERT_SIGN         0x0004
# define ossl_X509v3_KU_CRL_SIGN              0x0002
# define ossl_X509v3_KU_ENCIPHER_ONLY         0x0001
# define ossl_X509v3_KU_DECIPHER_ONLY         0x8000
# define ossl_X509v3_KU_UNDEF                 0xffff

struct ossl_X509_algor_st {
    ossl_ASN1_OBJECT *algorithm;
    ossl_ASN1_TYPE *parameter;
} /* ossl_X509_ALGOR */ ;

typedef ossl_STACK_OF(ossl_X509_ALGOR) ossl_X509_ALGORS;

typedef struct ossl_X509_val_st {
    ossl_ASN1_TIME *notBefore;
    ossl_ASN1_TIME *notAfter;
} ossl_X509_VAL;

typedef struct ossl_X509_sig_st ossl_X509_SIG;

typedef struct ossl_X509_name_entry_st ossl_X509_NAME_ENTRY;

ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_NAME_ENTRY, ossl_X509_NAME_ENTRY, ossl_X509_NAME_ENTRY)
#define ossl_sk_X509_NAME_ENTRY_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_NAME_ENTRY_sk_type(sk))
#define ossl_sk_X509_NAME_ENTRY_value(sk, idx) ((ossl_X509_NAME_ENTRY *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_NAME_ENTRY_sk_type(sk), (idx)))
#define ossl_sk_X509_NAME_ENTRY_new(cmp) ((ossl_STACK_OF(ossl_X509_NAME_ENTRY) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_NAME_ENTRY_compfunc_type(cmp)))
#define ossl_sk_X509_NAME_ENTRY_new_null() ((ossl_STACK_OF(ossl_X509_NAME_ENTRY) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_NAME_ENTRY_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_NAME_ENTRY) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_NAME_ENTRY_compfunc_type(cmp), (n)))
#define ossl_sk_X509_NAME_ENTRY_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), (n))
#define ossl_sk_X509_NAME_ENTRY_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk))
#define ossl_sk_X509_NAME_ENTRY_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk))
#define ossl_sk_X509_NAME_ENTRY_delete(sk, i) ((ossl_X509_NAME_ENTRY *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), (i)))
#define ossl_sk_X509_NAME_ENTRY_delete_ptr(sk, ptr) ((ossl_X509_NAME_ENTRY *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr)))
#define ossl_sk_X509_NAME_ENTRY_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr))
#define ossl_sk_X509_NAME_ENTRY_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr))
#define ossl_sk_X509_NAME_ENTRY_pop(sk) ((ossl_X509_NAME_ENTRY *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk)))
#define ossl_sk_X509_NAME_ENTRY_shift(sk) ((ossl_X509_NAME_ENTRY *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk)))
#define ossl_sk_X509_NAME_ENTRY_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk),ossl_ossl_check_X509_NAME_ENTRY_freefunc_type(freefunc))
#define ossl_sk_X509_NAME_ENTRY_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr), (idx))
#define ossl_sk_X509_NAME_ENTRY_set(sk, idx, ptr) ((ossl_X509_NAME_ENTRY *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), (idx), ossl_ossl_check_X509_NAME_ENTRY_type(ptr)))
#define ossl_sk_X509_NAME_ENTRY_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr))
#define ossl_sk_X509_NAME_ENTRY_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr))
#define ossl_sk_X509_NAME_ENTRY_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_type(ptr), pnum)
#define ossl_sk_X509_NAME_ENTRY_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk))
#define ossl_sk_X509_NAME_ENTRY_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_NAME_ENTRY_sk_type(sk))
#define ossl_sk_X509_NAME_ENTRY_dup(sk) ((ossl_STACK_OF(ossl_X509_NAME_ENTRY) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_NAME_ENTRY_sk_type(sk)))
#define ossl_sk_X509_NAME_ENTRY_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_NAME_ENTRY) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_copyfunc_type(copyfunc), ossl_ossl_check_X509_NAME_ENTRY_freefunc_type(freefunc)))
#define ossl_sk_X509_NAME_ENTRY_set_cmp_func(sk, cmp) ((ossl_sk_X509_NAME_ENTRY_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_NAME_ENTRY_sk_type(sk), ossl_ossl_check_X509_NAME_ENTRY_compfunc_type(cmp)))


# define ossl_X509_EX_V_NETSCAPE_HACK         0x8000
# define ossl_X509_EX_V_INIT                  0x0001
typedef struct ossl_X509_extension_st ossl_X509_EXTENSION;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_EXTENSION, ossl_X509_EXTENSION, ossl_X509_EXTENSION)
#define ossl_sk_X509_EXTENSION_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_EXTENSION_sk_type(sk))
#define ossl_sk_X509_EXTENSION_value(sk, idx) ((ossl_X509_EXTENSION *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_EXTENSION_sk_type(sk), (idx)))
#define ossl_sk_X509_EXTENSION_new(cmp) ((ossl_STACK_OF(ossl_X509_EXTENSION) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_EXTENSION_compfunc_type(cmp)))
#define ossl_sk_X509_EXTENSION_new_null() ((ossl_STACK_OF(ossl_X509_EXTENSION) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_EXTENSION_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_EXTENSION) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_EXTENSION_compfunc_type(cmp), (n)))
#define ossl_sk_X509_EXTENSION_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_EXTENSION_sk_type(sk), (n))
#define ossl_sk_X509_EXTENSION_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_EXTENSION_sk_type(sk))
#define ossl_sk_X509_EXTENSION_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_EXTENSION_sk_type(sk))
#define ossl_sk_X509_EXTENSION_delete(sk, i) ((ossl_X509_EXTENSION *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_EXTENSION_sk_type(sk), (i)))
#define ossl_sk_X509_EXTENSION_delete_ptr(sk, ptr) ((ossl_X509_EXTENSION *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr)))
#define ossl_sk_X509_EXTENSION_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr))
#define ossl_sk_X509_EXTENSION_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr))
#define ossl_sk_X509_EXTENSION_pop(sk) ((ossl_X509_EXTENSION *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_EXTENSION_sk_type(sk)))
#define ossl_sk_X509_EXTENSION_shift(sk) ((ossl_X509_EXTENSION *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_EXTENSION_sk_type(sk)))
#define ossl_sk_X509_EXTENSION_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_EXTENSION_sk_type(sk),ossl_ossl_check_X509_EXTENSION_freefunc_type(freefunc))
#define ossl_sk_X509_EXTENSION_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr), (idx))
#define ossl_sk_X509_EXTENSION_set(sk, idx, ptr) ((ossl_X509_EXTENSION *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_EXTENSION_sk_type(sk), (idx), ossl_ossl_check_X509_EXTENSION_type(ptr)))
#define ossl_sk_X509_EXTENSION_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr))
#define ossl_sk_X509_EXTENSION_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr))
#define ossl_sk_X509_EXTENSION_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_type(ptr), pnum)
#define ossl_sk_X509_EXTENSION_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_EXTENSION_sk_type(sk))
#define ossl_sk_X509_EXTENSION_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_EXTENSION_sk_type(sk))
#define ossl_sk_X509_EXTENSION_dup(sk) ((ossl_STACK_OF(ossl_X509_EXTENSION) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_EXTENSION_sk_type(sk)))
#define ossl_sk_X509_EXTENSION_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_EXTENSION) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_copyfunc_type(copyfunc), ossl_ossl_check_X509_EXTENSION_freefunc_type(freefunc)))
#define ossl_sk_X509_EXTENSION_set_cmp_func(sk, cmp) ((ossl_sk_X509_EXTENSION_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_EXTENSION_sk_type(sk), ossl_ossl_check_X509_EXTENSION_compfunc_type(cmp)))

typedef ossl_STACK_OF(ossl_X509_EXTENSION) ossl_X509_EXTENSIONS;
typedef struct ossl_x509_attributes_st ossl_X509_ATTRIBUTE;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_ATTRIBUTE, ossl_X509_ATTRIBUTE, ossl_X509_ATTRIBUTE)
#define ossl_sk_X509_ATTRIBUTE_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_ATTRIBUTE_sk_type(sk))
#define ossl_sk_X509_ATTRIBUTE_value(sk, idx) ((ossl_X509_ATTRIBUTE *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_ATTRIBUTE_sk_type(sk), (idx)))
#define ossl_sk_X509_ATTRIBUTE_new(cmp) ((ossl_STACK_OF(ossl_X509_ATTRIBUTE) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_ATTRIBUTE_compfunc_type(cmp)))
#define ossl_sk_X509_ATTRIBUTE_new_null() ((ossl_STACK_OF(ossl_X509_ATTRIBUTE) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_ATTRIBUTE_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_ATTRIBUTE) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_ATTRIBUTE_compfunc_type(cmp), (n)))
#define ossl_sk_X509_ATTRIBUTE_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), (n))
#define ossl_sk_X509_ATTRIBUTE_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk))
#define ossl_sk_X509_ATTRIBUTE_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk))
#define ossl_sk_X509_ATTRIBUTE_delete(sk, i) ((ossl_X509_ATTRIBUTE *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), (i)))
#define ossl_sk_X509_ATTRIBUTE_delete_ptr(sk, ptr) ((ossl_X509_ATTRIBUTE *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr)))
#define ossl_sk_X509_ATTRIBUTE_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr))
#define ossl_sk_X509_ATTRIBUTE_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr))
#define ossl_sk_X509_ATTRIBUTE_pop(sk) ((ossl_X509_ATTRIBUTE *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk)))
#define ossl_sk_X509_ATTRIBUTE_shift(sk) ((ossl_X509_ATTRIBUTE *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk)))
#define ossl_sk_X509_ATTRIBUTE_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk),ossl_ossl_check_X509_ATTRIBUTE_freefunc_type(freefunc))
#define ossl_sk_X509_ATTRIBUTE_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr), (idx))
#define ossl_sk_X509_ATTRIBUTE_set(sk, idx, ptr) ((ossl_X509_ATTRIBUTE *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), (idx), ossl_ossl_check_X509_ATTRIBUTE_type(ptr)))
#define ossl_sk_X509_ATTRIBUTE_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr))
#define ossl_sk_X509_ATTRIBUTE_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr))
#define ossl_sk_X509_ATTRIBUTE_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_type(ptr), pnum)
#define ossl_sk_X509_ATTRIBUTE_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk))
#define ossl_sk_X509_ATTRIBUTE_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_ATTRIBUTE_sk_type(sk))
#define ossl_sk_X509_ATTRIBUTE_dup(sk) ((ossl_STACK_OF(ossl_X509_ATTRIBUTE) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_ATTRIBUTE_sk_type(sk)))
#define ossl_sk_X509_ATTRIBUTE_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_ATTRIBUTE) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_copyfunc_type(copyfunc), ossl_ossl_check_X509_ATTRIBUTE_freefunc_type(freefunc)))
#define ossl_sk_X509_ATTRIBUTE_set_cmp_func(sk, cmp) ((ossl_sk_X509_ATTRIBUTE_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_ATTRIBUTE_sk_type(sk), ossl_ossl_check_X509_ATTRIBUTE_compfunc_type(cmp)))

typedef struct ossl_X509_req_info_st ossl_X509_REQ_INFO;
typedef struct ossl_X509_req_st ossl_X509_REQ;
typedef struct ossl_x509_cert_aux_st ossl_X509_CERT_AUX;
typedef struct ossl_x509_cinf_st ossl_X509_CINF;

/* Flags for ossl_X509_print_ex() */

# define ossl_X509_FLAG_COMPAT                0
# define ossl_X509_FLAG_NO_HEADER             1L
# define ossl_X509_FLAG_NO_VERSION            (1L << 1)
# define ossl_X509_FLAG_NO_SERIAL             (1L << 2)
# define ossl_X509_FLAG_NO_SIGNAME            (1L << 3)
# define ossl_X509_FLAG_NO_ISSUER             (1L << 4)
# define ossl_X509_FLAG_NO_VALIDITY           (1L << 5)
# define ossl_X509_FLAG_NO_SUBJECT            (1L << 6)
# define ossl_X509_FLAG_NO_PUBKEY             (1L << 7)
# define ossl_X509_FLAG_NO_EXTENSIONS         (1L << 8)
# define ossl_X509_FLAG_NO_SIGDUMP            (1L << 9)
# define ossl_X509_FLAG_NO_AUX                (1L << 10)
# define ossl_X509_FLAG_NO_ATTRIBUTES         (1L << 11)
# define ossl_X509_FLAG_NO_IDS                (1L << 12)
# define ossl_X509_FLAG_EXTENSIONS_ONLY_KID   (1L << 13)

/* Flags specific to ossl_X509_NAME_print_ex() */

/* The field separator information */

# define ossl_XN_FLAG_SEP_MASK        (0xf << 16)

# define ossl_XN_FLAG_COMPAT          0/* Traditional; use old ossl_X509_NAME_print */
# define ossl_XN_FLAG_SEP_COMMA_PLUS  (1 << 16)/* RFC2253 ,+ */
# define ossl_XN_FLAG_SEP_CPLUS_SPC   (2 << 16)/* ,+ spaced: more readable */
# define ossl_XN_FLAG_SEP_SPLUS_SPC   (3 << 16)/* ;+ spaced */
# define ossl_XN_FLAG_SEP_MULTILINE   (4 << 16)/* One line per field */

# define ossl_XN_FLAG_DN_REV          (1 << 20)/* Reverse DN order */

/* How the field name is shown */

# define ossl_XN_FLAG_FN_MASK         (0x3 << 21)

# define ossl_XN_FLAG_FN_SN           0/* Object short name */
# define ossl_XN_FLAG_FN_LN           (1 << 21)/* Object long name */
# define ossl_XN_FLAG_FN_OID          (2 << 21)/* Always use OIDs */
# define ossl_XN_FLAG_FN_NONE         (3 << 21)/* No field names */

# define ossl_XN_FLAG_SPC_EQ          (1 << 23)/* Put spaces round '=' */

/*
 * This determines if we dump fields we don't recognise: RFC2253 requires
 * this.
 */

# define ossl_XN_FLAG_DUMP_UNKNOWN_FIELDS (1 << 24)

# define ossl_XN_FLAG_FN_ALIGN        (1 << 25)/* Align field names to 20
                                           * characters */

/* Complete set of RFC2253 flags */

# define ossl_XN_FLAG_RFC2253 (ossl_ASN1_STRFLGS_RFC2253 | \
                        ossl_XN_FLAG_SEP_COMMA_PLUS | \
                        ossl_XN_FLAG_DN_REV | \
                        ossl_XN_FLAG_FN_SN | \
                        ossl_XN_FLAG_DUMP_UNKNOWN_FIELDS)

/* readable oneline form */

# define ossl_XN_FLAG_ONELINE (ossl_ASN1_STRFLGS_RFC2253 | \
                        ossl_ASN1_STRFLGS_ESC_QUOTE | \
                        ossl_XN_FLAG_SEP_CPLUS_SPC | \
                        ossl_XN_FLAG_SPC_EQ | \
                        ossl_XN_FLAG_FN_SN)

/* readable multiline form */

# define ossl_XN_FLAG_MULTILINE (ossl_ASN1_STRFLGS_ESC_CTRL | \
                        ossl_ASN1_STRFLGS_ESC_MSB | \
                        ossl_XN_FLAG_SEP_MULTILINE | \
                        ossl_XN_FLAG_SPC_EQ | \
                        ossl_XN_FLAG_FN_LN | \
                        ossl_XN_FLAG_FN_ALIGN)

typedef struct ossl_X509_crl_info_st ossl_X509_CRL_INFO;

typedef struct ossl_private_key_st {
    int version;
    /* The PKCS#8 data types */
    ossl_X509_ALGOR *enc_algor;
    ossl_ASN1_OCTET_STRING *enc_pkey; /* encrypted pub key */
    /* When decrypted, the following will not be NULL */
    ossl_EVP_PKEY *dec_pkey;
    /* used to encrypt and decrypt */
    int key_length;
    char *key_data;
    int key_free;               /* true if we should auto free key_data */
    /* expanded version of 'enc_algor' */
    ossl_EVP_CIPHER_INFO cipher;
} ossl_X509_PKEY;

typedef struct ossl_X509_info_st {
    ossl_X509 *x509;
    ossl_X509_CRL *crl;
    ossl_X509_PKEY *x_pkey;
    ossl_EVP_CIPHER_INFO enc_cipher;
    int enc_len;
    char *enc_data;
} ossl_X509_INFO;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_INFO, ossl_X509_INFO, ossl_X509_INFO)
#define ossl_sk_X509_INFO_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_INFO_sk_type(sk))
#define ossl_sk_X509_INFO_value(sk, idx) ((ossl_X509_INFO *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_INFO_sk_type(sk), (idx)))
#define ossl_sk_X509_INFO_new(cmp) ((ossl_STACK_OF(ossl_X509_INFO) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_INFO_compfunc_type(cmp)))
#define ossl_sk_X509_INFO_new_null() ((ossl_STACK_OF(ossl_X509_INFO) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_INFO_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_INFO) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_INFO_compfunc_type(cmp), (n)))
#define ossl_sk_X509_INFO_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_INFO_sk_type(sk), (n))
#define ossl_sk_X509_INFO_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_INFO_sk_type(sk))
#define ossl_sk_X509_INFO_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_INFO_sk_type(sk))
#define ossl_sk_X509_INFO_delete(sk, i) ((ossl_X509_INFO *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_INFO_sk_type(sk), (i)))
#define ossl_sk_X509_INFO_delete_ptr(sk, ptr) ((ossl_X509_INFO *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr)))
#define ossl_sk_X509_INFO_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr))
#define ossl_sk_X509_INFO_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr))
#define ossl_sk_X509_INFO_pop(sk) ((ossl_X509_INFO *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_INFO_sk_type(sk)))
#define ossl_sk_X509_INFO_shift(sk) ((ossl_X509_INFO *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_INFO_sk_type(sk)))
#define ossl_sk_X509_INFO_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_INFO_sk_type(sk),ossl_ossl_check_X509_INFO_freefunc_type(freefunc))
#define ossl_sk_X509_INFO_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr), (idx))
#define ossl_sk_X509_INFO_set(sk, idx, ptr) ((ossl_X509_INFO *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_INFO_sk_type(sk), (idx), ossl_ossl_check_X509_INFO_type(ptr)))
#define ossl_sk_X509_INFO_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr))
#define ossl_sk_X509_INFO_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr))
#define ossl_sk_X509_INFO_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_type(ptr), pnum)
#define ossl_sk_X509_INFO_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_INFO_sk_type(sk))
#define ossl_sk_X509_INFO_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_INFO_sk_type(sk))
#define ossl_sk_X509_INFO_dup(sk) ((ossl_STACK_OF(ossl_X509_INFO) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_INFO_sk_type(sk)))
#define ossl_sk_X509_INFO_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_INFO) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_copyfunc_type(copyfunc), ossl_ossl_check_X509_INFO_freefunc_type(freefunc)))
#define ossl_sk_X509_INFO_set_cmp_func(sk, cmp) ((ossl_sk_X509_INFO_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_INFO_sk_type(sk), ossl_ossl_check_X509_INFO_compfunc_type(cmp)))


/*
 * The next 2 structures and their 8 routines are used to manipulate Netscape's
 * spki structures - useful if you are writing a CA web page
 */
typedef struct ossl_Netscape_spkac_st {
    ossl_X509_PUBKEY *pubkey;
    ossl_ASN1_IA5STRING *challenge;  /* challenge sent in atlas >= PR2 */
} ossl_NETSCAPE_SPKAC;

typedef struct ossl_Netscape_spki_st {
    ossl_NETSCAPE_SPKAC *spkac;      /* signed public key and challenge */
    ossl_X509_ALGOR sig_algor;
    ossl_ASN1_BIT_STRING *signature;
} ossl_NETSCAPE_SPKI;

/* Netscape certificate sequence structure */
typedef struct ossl_Netscape_certificate_sequence {
    ossl_ASN1_OBJECT *type;
    ossl_STACK_OF(ossl_X509) *certs;
} ossl_NETSCAPE_CERT_SEQUENCE;

/*- Unused (and iv length is wrong)
typedef struct CBCParameter_st
        {
        unsigned char iv[8];
        } CBC_PARAM;
*/

/* Password based encryption structure */

typedef struct ossl_PBEPARAM_st {
    ossl_ASN1_OCTET_STRING *salt;
    ossl_ASN1_INTEGER *iter;
} ossl_PBEPARAM;

/* Password based encryption V2 structures */

typedef struct ossl_PBE2PARAM_st {
    ossl_X509_ALGOR *keyfunc;
    ossl_X509_ALGOR *encryption;
} ossl_PBE2PARAM;

typedef struct ossl_PBKDF2PARAM_st {
/* Usually OCTET STRING but could be anything */
    ossl_ASN1_TYPE *salt;
    ossl_ASN1_INTEGER *iter;
    ossl_ASN1_INTEGER *keylength;
    ossl_X509_ALGOR *prf;
} ossl_PBKDF2PARAM;

#ifndef ossl_OPENSSL_NO_SCRYPT
typedef struct ossl_SCRYPT_PARAMS_st {
    ossl_ASN1_OCTET_STRING *salt;
    ossl_ASN1_INTEGER *costParameter;
    ossl_ASN1_INTEGER *blockSize;
    ossl_ASN1_INTEGER *parallelizationParameter;
    ossl_ASN1_INTEGER *keyLength;
} ossl_SCRYPT_PARAMS;
#endif

#ifdef  __cplusplus
}
#endif

# include "ossl/openssl/x509_vfy.h"
# include "ossl/openssl/pkcs7.h"

#ifdef  __cplusplus
extern "C" {
#endif

# define ossl_X509_EXT_PACK_UNKNOWN   1
# define ossl_X509_EXT_PACK_STRING    2

# define         ossl_X509_extract_key(x)     ossl_X509_get_pubkey(x)/*****/
# define         ossl_X509_REQ_extract_key(a) ossl_X509_REQ_get_pubkey(a)
# define         ossl_X509_name_cmp(a,b)      ossl_X509_NAME_cmp((a),(b))

void ossl_X509_CRL_set_default_method(const ossl_X509_CRL_METHOD *meth);
ossl_X509_CRL_METHOD *ossl_X509_CRL_METHOD_new(int (*crl_init) (ossl_X509_CRL *crl),
                                     int (*crl_free) (ossl_X509_CRL *crl),
                                     int (*crl_lookup) (ossl_X509_CRL *crl,
                                                        ossl_X509_REVOKED **ret,
                                                        const
                                                        ossl_ASN1_INTEGER *serial,
                                                        const
                                                        ossl_X509_NAME *issuer),
                                     int (*crl_verify) (ossl_X509_CRL *crl,
                                                        ossl_EVP_PKEY *pk));
void ossl_X509_CRL_METHOD_free(ossl_X509_CRL_METHOD *m);

void ossl_X509_CRL_set_meth_data(ossl_X509_CRL *crl, void *dat);
void *ossl_X509_CRL_get_meth_data(ossl_X509_CRL *crl);

const char *ossl_X509_verify_cert_error_string(long n);

int ossl_X509_verify(ossl_X509 *a, ossl_EVP_PKEY *r);
int ossl_X509_self_signed(ossl_X509 *cert, int verify_signature);

int ossl_X509_REQ_verify_ex(ossl_X509_REQ *a, ossl_EVP_PKEY *r, ossl_OSSL_LIB_CTX *libctx,
                       const char *propq);
int ossl_X509_REQ_verify(ossl_X509_REQ *a, ossl_EVP_PKEY *r);
int ossl_X509_CRL_verify(ossl_X509_CRL *a, ossl_EVP_PKEY *r);
int ossl_NETSCAPE_SPKI_verify(ossl_NETSCAPE_SPKI *a, ossl_EVP_PKEY *r);

ossl_NETSCAPE_SPKI *ossl_NETSCAPE_SPKI_b64_decode(const char *str, int len);
char *ossl_NETSCAPE_SPKI_b64_encode(ossl_NETSCAPE_SPKI *x);
ossl_EVP_PKEY *ossl_NETSCAPE_SPKI_get_pubkey(ossl_NETSCAPE_SPKI *x);
int ossl_NETSCAPE_SPKI_set_pubkey(ossl_NETSCAPE_SPKI *x, ossl_EVP_PKEY *pkey);

int ossl_NETSCAPE_SPKI_print(ossl_BIO *out, ossl_NETSCAPE_SPKI *spki);

int ossl_X509_signature_dump(ossl_BIO *bp, const ossl_ASN1_STRING *sig, int indent);
int ossl_X509_signature_print(ossl_BIO *bp, const ossl_X509_ALGOR *alg,
                         const ossl_ASN1_STRING *sig);

int ossl_X509_sign(ossl_X509 *x, ossl_EVP_PKEY *pkey, const ossl_EVP_MD *md);
int ossl_X509_sign_ctx(ossl_X509 *x, ossl_EVP_MD_CTX *ctx);
int ossl_X509_REQ_sign(ossl_X509_REQ *x, ossl_EVP_PKEY *pkey, const ossl_EVP_MD *md);
int ossl_X509_REQ_sign_ctx(ossl_X509_REQ *x, ossl_EVP_MD_CTX *ctx);
int ossl_X509_CRL_sign(ossl_X509_CRL *x, ossl_EVP_PKEY *pkey, const ossl_EVP_MD *md);
int ossl_X509_CRL_sign_ctx(ossl_X509_CRL *x, ossl_EVP_MD_CTX *ctx);
int ossl_NETSCAPE_SPKI_sign(ossl_NETSCAPE_SPKI *x, ossl_EVP_PKEY *pkey, const ossl_EVP_MD *md);

int ossl_X509_pubkey_digest(const ossl_X509 *data, const ossl_EVP_MD *type,
                       unsigned char *md, unsigned int *len);
int ossl_X509_digest(const ossl_X509 *data, const ossl_EVP_MD *type,
                unsigned char *md, unsigned int *len);
ossl_ASN1_OCTET_STRING *ossl_X509_digest_sig(const ossl_X509 *cert,
                                   ossl_EVP_MD **md_used, int *md_is_fallback);
int ossl_X509_CRL_digest(const ossl_X509_CRL *data, const ossl_EVP_MD *type,
                    unsigned char *md, unsigned int *len);
int ossl_X509_REQ_digest(const ossl_X509_REQ *data, const ossl_EVP_MD *type,
                    unsigned char *md, unsigned int *len);
int ossl_X509_NAME_digest(const ossl_X509_NAME *data, const ossl_EVP_MD *type,
                     unsigned char *md, unsigned int *len);

ossl_X509 *ossl_X509_load_http(const char *url, ossl_BIO *bio, ossl_BIO *rbio, int timeout);
ossl_X509_CRL *ossl_X509_CRL_load_http(const char *url, ossl_BIO *bio, ossl_BIO *rbio, int timeout);
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#  include "ossl/openssl/http.h" /* ossl_OSSL_HTTP_REQ_CTX_nbio_d2i */
#  define ossl_X509_http_nbio(rctx, pcert) \
      ossl_OSSL_HTTP_REQ_CTX_nbio_d2i(rctx, pcert, ossl_ASN1_ITEM_rptr(ossl_X509))
#  define ossl_X509_CRL_http_nbio(rctx, pcrl) \
      ossl_OSSL_HTTP_REQ_CTX_nbio_d2i(rctx, pcrl, ossl_ASN1_ITEM_rptr(ossl_X509_CRL))
# endif

# ifndef ossl_OPENSSL_NO_STDIO
ossl_X509 *ossl_d2i_X509_fp(FILE *fp, ossl_X509 **x509);
int ossl_i2d_X509_fp(FILE *fp, const ossl_X509 *x509);
ossl_X509_CRL *ossl_d2i_X509_CRL_fp(FILE *fp, ossl_X509_CRL **crl);
int ossl_i2d_X509_CRL_fp(FILE *fp, const ossl_X509_CRL *crl);
ossl_X509_REQ *ossl_d2i_X509_REQ_fp(FILE *fp, ossl_X509_REQ **req);
int ossl_i2d_X509_REQ_fp(FILE *fp, const ossl_X509_REQ *req);
#  ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
ossl_OSSL_DEPRECATEDIN_3_0 ossl_RSA *ossl_d2i_RSAPrivateKey_fp(FILE *fp, ossl_RSA **rsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_RSAPrivateKey_fp(FILE *fp, const ossl_RSA *rsa);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_RSA *ossl_d2i_RSAPublicKey_fp(FILE *fp, ossl_RSA **rsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_RSAPublicKey_fp(FILE *fp, const ossl_RSA *rsa);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_RSA *ossl_d2i_RSA_PUBKEY_fp(FILE *fp, ossl_RSA **rsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_RSA_PUBKEY_fp(FILE *fp, const ossl_RSA *rsa);
#  endif
#  ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#   ifndef ossl_OPENSSL_NO_DSA
ossl_OSSL_DEPRECATEDIN_3_0 ossl_DSA *ossl_d2i_DSA_PUBKEY_fp(FILE *fp, ossl_DSA **dsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_DSA_PUBKEY_fp(FILE *fp, const ossl_DSA *dsa);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_DSA *ossl_d2i_DSAPrivateKey_fp(FILE *fp, ossl_DSA **dsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_DSAPrivateKey_fp(FILE *fp, const ossl_DSA *dsa);
#   endif
#  endif
#  ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#   ifndef ossl_OPENSSL_NO_EC
ossl_OSSL_DEPRECATEDIN_3_0 ossl_EC_KEY *ossl_d2i_EC_PUBKEY_fp(FILE *fp, ossl_EC_KEY **eckey);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_EC_PUBKEY_fp(FILE *fp, const ossl_EC_KEY *eckey);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_EC_KEY *ossl_d2i_ECPrivateKey_fp(FILE *fp, ossl_EC_KEY **eckey);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_ECPrivateKey_fp(FILE *fp, const ossl_EC_KEY *eckey);
#   endif /* ossl_OPENSSL_NO_EC */
#  endif /* ossl_OPENSSL_NO_DEPRECATED_3_0 */
ossl_X509_SIG *ossl_d2i_PKCS8_fp(FILE *fp, ossl_X509_SIG **p8);
int ossl_i2d_PKCS8_fp(FILE *fp, const ossl_X509_SIG *p8);
ossl_X509_PUBKEY *ossl_d2i_X509_PUBKEY_fp(FILE *fp, ossl_X509_PUBKEY **xpk);
int ossl_i2d_X509_PUBKEY_fp(FILE *fp, const ossl_X509_PUBKEY *xpk);
ossl_PKCS8_PRIV_KEY_INFO *ossl_d2i_PKCS8_PRIV_KEY_INFO_fp(FILE *fp,
                                                ossl_PKCS8_PRIV_KEY_INFO **p8inf);
int ossl_i2d_PKCS8_PRIV_KEY_INFO_fp(FILE *fp, const ossl_PKCS8_PRIV_KEY_INFO *p8inf);
int ossl_i2d_PKCS8PrivateKeyInfo_fp(FILE *fp, const ossl_EVP_PKEY *key);
int ossl_i2d_PrivateKey_fp(FILE *fp, const ossl_EVP_PKEY *pkey);
ossl_EVP_PKEY *ossl_d2i_PrivateKey_ex_fp(FILE *fp, ossl_EVP_PKEY **a, ossl_OSSL_LIB_CTX *libctx,
                               const char *propq);
ossl_EVP_PKEY *ossl_d2i_PrivateKey_fp(FILE *fp, ossl_EVP_PKEY **a);
int ossl_i2d_PUBKEY_fp(FILE *fp, const ossl_EVP_PKEY *pkey);
ossl_EVP_PKEY *ossl_d2i_PUBKEY_fp(FILE *fp, ossl_EVP_PKEY **a);
# endif

ossl_X509 *ossl_d2i_X509_bio(ossl_BIO *bp, ossl_X509 **x509);
int ossl_i2d_X509_bio(ossl_BIO *bp, const ossl_X509 *x509);
ossl_X509_CRL *ossl_d2i_X509_CRL_bio(ossl_BIO *bp, ossl_X509_CRL **crl);
int ossl_i2d_X509_CRL_bio(ossl_BIO *bp, const ossl_X509_CRL *crl);
ossl_X509_REQ *ossl_d2i_X509_REQ_bio(ossl_BIO *bp, ossl_X509_REQ **req);
int ossl_i2d_X509_REQ_bio(ossl_BIO *bp, const ossl_X509_REQ *req);
#  ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
ossl_OSSL_DEPRECATEDIN_3_0 ossl_RSA *ossl_d2i_RSAPrivateKey_bio(ossl_BIO *bp, ossl_RSA **rsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_RSAPrivateKey_bio(ossl_BIO *bp, const ossl_RSA *rsa);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_RSA *ossl_d2i_RSAPublicKey_bio(ossl_BIO *bp, ossl_RSA **rsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_RSAPublicKey_bio(ossl_BIO *bp, const ossl_RSA *rsa);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_RSA *ossl_d2i_RSA_PUBKEY_bio(ossl_BIO *bp, ossl_RSA **rsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_RSA_PUBKEY_bio(ossl_BIO *bp, const ossl_RSA *rsa);
#  endif
#  ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#   ifndef ossl_OPENSSL_NO_DSA
ossl_OSSL_DEPRECATEDIN_3_0 ossl_DSA *ossl_d2i_DSA_PUBKEY_bio(ossl_BIO *bp, ossl_DSA **dsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_DSA_PUBKEY_bio(ossl_BIO *bp, const ossl_DSA *dsa);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_DSA *ossl_d2i_DSAPrivateKey_bio(ossl_BIO *bp, ossl_DSA **dsa);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_DSAPrivateKey_bio(ossl_BIO *bp, const ossl_DSA *dsa);
#   endif
#  endif

#  ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#   ifndef ossl_OPENSSL_NO_EC
ossl_OSSL_DEPRECATEDIN_3_0 ossl_EC_KEY *ossl_d2i_EC_PUBKEY_bio(ossl_BIO *bp, ossl_EC_KEY **eckey);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_EC_PUBKEY_bio(ossl_BIO *bp, const ossl_EC_KEY *eckey);
ossl_OSSL_DEPRECATEDIN_3_0 ossl_EC_KEY *ossl_d2i_ECPrivateKey_bio(ossl_BIO *bp, ossl_EC_KEY **eckey);
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_i2d_ECPrivateKey_bio(ossl_BIO *bp, const ossl_EC_KEY *eckey);
#   endif /* ossl_OPENSSL_NO_EC */
#  endif /* ossl_OPENSSL_NO_DEPRECATED_3_0 */

ossl_X509_SIG *ossl_d2i_PKCS8_bio(ossl_BIO *bp, ossl_X509_SIG **p8);
int ossl_i2d_PKCS8_bio(ossl_BIO *bp, const ossl_X509_SIG *p8);
ossl_X509_PUBKEY *ossl_d2i_X509_PUBKEY_bio(ossl_BIO *bp, ossl_X509_PUBKEY **xpk);
int ossl_i2d_X509_PUBKEY_bio(ossl_BIO *bp, const ossl_X509_PUBKEY *xpk);
ossl_PKCS8_PRIV_KEY_INFO *ossl_d2i_PKCS8_PRIV_KEY_INFO_bio(ossl_BIO *bp,
                                                 ossl_PKCS8_PRIV_KEY_INFO **p8inf);
int ossl_i2d_PKCS8_PRIV_KEY_INFO_bio(ossl_BIO *bp, const ossl_PKCS8_PRIV_KEY_INFO *p8inf);
int ossl_i2d_PKCS8PrivateKeyInfo_bio(ossl_BIO *bp, const ossl_EVP_PKEY *key);
int ossl_i2d_PrivateKey_bio(ossl_BIO *bp, const ossl_EVP_PKEY *pkey);
ossl_EVP_PKEY *ossl_d2i_PrivateKey_ex_bio(ossl_BIO *bp, ossl_EVP_PKEY **a, ossl_OSSL_LIB_CTX *libctx,
                                const char *propq);
ossl_EVP_PKEY *ossl_d2i_PrivateKey_bio(ossl_BIO *bp, ossl_EVP_PKEY **a);
int ossl_i2d_PUBKEY_bio(ossl_BIO *bp, const ossl_EVP_PKEY *pkey);
ossl_EVP_PKEY *ossl_d2i_PUBKEY_bio(ossl_BIO *bp, ossl_EVP_PKEY **a);

ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_ALGOR)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_ATTRIBUTE)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_CRL)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_EXTENSION)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_PUBKEY)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_REQ)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_REVOKED)
int ossl_X509_ALGOR_set0(ossl_X509_ALGOR *alg, ossl_ASN1_OBJECT *aobj, int ptype,
                    void *pval);
void ossl_X509_ALGOR_get0(const ossl_ASN1_OBJECT **paobj, int *pptype,
                     const void **ppval, const ossl_X509_ALGOR *algor);
void ossl_X509_ALGOR_set_md(ossl_X509_ALGOR *alg, const ossl_EVP_MD *md);
int ossl_X509_ALGOR_cmp(const ossl_X509_ALGOR *a, const ossl_X509_ALGOR *b);
int ossl_X509_ALGOR_copy(ossl_X509_ALGOR *dest, const ossl_X509_ALGOR *src);

ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_NAME)
ossl_DECLARE_ASN1_DUP_FUNCTION(ossl_X509_NAME_ENTRY)

int ossl_X509_cmp_time(const ossl_ASN1_TIME *s, time_t *t);
int ossl_X509_cmp_current_time(const ossl_ASN1_TIME *s);
int ossl_X509_cmp_timeframe(const ossl_X509_VERIFY_PARAM *vpm,
                       const ossl_ASN1_TIME *start, const ossl_ASN1_TIME *end);
ossl_ASN1_TIME *ossl_X509_time_adj(ossl_ASN1_TIME *s, long adj, time_t *t);
ossl_ASN1_TIME *ossl_X509_time_adj_ex(ossl_ASN1_TIME *s,
                            int offset_day, long offset_sec, time_t *t);
ossl_ASN1_TIME *ossl_X509_gmtime_adj(ossl_ASN1_TIME *s, long adj);

const char *ossl_X509_get_default_cert_area(void);
const char *ossl_X509_get_default_cert_dir(void);
const char *ossl_X509_get_default_cert_file(void);
const char *ossl_X509_get_default_cert_dir_env(void);
const char *ossl_X509_get_default_cert_file_env(void);
const char *ossl_X509_get_default_private_dir(void);

ossl_X509_REQ *ossl_X509_to_X509_REQ(ossl_X509 *x, ossl_EVP_PKEY *pkey, const ossl_EVP_MD *md);
ossl_X509 *ossl_X509_REQ_to_X509(ossl_X509_REQ *r, int days, ossl_EVP_PKEY *pkey);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_ALGOR)
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS(ossl_X509_ALGORS, ossl_X509_ALGORS, ossl_X509_ALGORS)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_VAL)

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_PUBKEY)

ossl_X509_PUBKEY *ossl_X509_PUBKEY_new_ex(ossl_OSSL_LIB_CTX *libctx, const char *propq);
int ossl_X509_PUBKEY_set(ossl_X509_PUBKEY **x, ossl_EVP_PKEY *pkey);
ossl_EVP_PKEY *ossl_X509_PUBKEY_get0(const ossl_X509_PUBKEY *key);
ossl_EVP_PKEY *ossl_X509_PUBKEY_get(const ossl_X509_PUBKEY *key);
int ossl_X509_get_pubkey_parameters(ossl_EVP_PKEY *pkey, ossl_STACK_OF(ossl_X509) *chain);
long ossl_X509_get_pathlen(ossl_X509 *x);
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS_only(ossl_EVP_PKEY, PUBKEY)
ossl_EVP_PKEY *ossl_d2i_PUBKEY_ex(ossl_EVP_PKEY **a, const unsigned char **pp, long length,
                        ossl_OSSL_LIB_CTX *libctx, const char *propq);
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS_only_attr(ossl_OSSL_DEPRECATEDIN_3_0,ossl_RSA, RSA_PUBKEY)
# endif
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#  ifndef ossl_OPENSSL_NO_DSA
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS_only_attr(ossl_OSSL_DEPRECATEDIN_3_0,ossl_DSA, DSA_PUBKEY)
#  endif
# endif
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#  ifndef ossl_OPENSSL_NO_EC
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS_only_attr(ossl_OSSL_DEPRECATEDIN_3_0, ossl_EC_KEY, EC_PUBKEY)
#  endif
# endif

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_SIG)
void ossl_X509_SIG_get0(const ossl_X509_SIG *sig, const ossl_X509_ALGOR **palg,
                   const ossl_ASN1_OCTET_STRING **pdigest);
void ossl_X509_SIG_getm(ossl_X509_SIG *sig, ossl_X509_ALGOR **palg,
                   ossl_ASN1_OCTET_STRING **pdigest);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_REQ_INFO)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_REQ)
ossl_X509_REQ *ossl_X509_REQ_new_ex(ossl_OSSL_LIB_CTX *libctx, const char *propq);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_ATTRIBUTE)
ossl_X509_ATTRIBUTE *ossl_X509_ATTRIBUTE_create(int nid, int atrtype, void *value);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_EXTENSION)
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS(ossl_X509_EXTENSIONS, ossl_X509_EXTENSIONS, ossl_X509_EXTENSIONS)

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_NAME_ENTRY)

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_NAME)

int ossl_X509_NAME_set(ossl_X509_NAME **xn, const ossl_X509_NAME *name);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_CINF)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509)
ossl_X509 *ossl_X509_new_ex(ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_CERT_AUX)

#define ossl_X509_get_ex_new_index(l, p, newf, dupf, freef) \
    ossl_CRYPTO_get_ex_new_index(ossl_CRYPTO_EX_INDEX_X509, l, p, newf, dupf, freef)
int ossl_X509_set_ex_data(ossl_X509 *r, int idx, void *arg);
void *ossl_X509_get_ex_data(const ossl_X509 *r, int idx);
ossl_DECLARE_ASN1_ENCODE_FUNCTIONS_only(ossl_X509,X509_AUX)

int ossl_i2d_re_X509_tbs(ossl_X509 *x, unsigned char **pp);

int ossl_X509_SIG_INFO_get(const ossl_X509_SIG_INFO *siginf, int *mdnid, int *pknid,
                      int *secbits, uint32_t *flags);
void ossl_X509_SIG_INFO_set(ossl_X509_SIG_INFO *siginf, int mdnid, int pknid,
                       int secbits, uint32_t flags);

int ossl_X509_get_signature_info(ossl_X509 *x, int *mdnid, int *pknid, int *secbits,
                            uint32_t *flags);

void ossl_X509_get0_signature(const ossl_ASN1_BIT_STRING **psig,
                         const ossl_X509_ALGOR **palg, const ossl_X509 *x);
int ossl_X509_get_signature_nid(const ossl_X509 *x);

void ossl_X509_set0_distinguishing_id(ossl_X509 *x, ossl_ASN1_OCTET_STRING *d_id);
ossl_ASN1_OCTET_STRING *ossl_X509_get0_distinguishing_id(ossl_X509 *x);
void ossl_X509_REQ_set0_distinguishing_id(ossl_X509_REQ *x, ossl_ASN1_OCTET_STRING *d_id);
ossl_ASN1_OCTET_STRING *ossl_X509_REQ_get0_distinguishing_id(ossl_X509_REQ *x);

int ossl_X509_alias_set1(ossl_X509 *x, const unsigned char *name, int len);
int ossl_X509_keyid_set1(ossl_X509 *x, const unsigned char *id, int len);
unsigned char *ossl_X509_alias_get0(ossl_X509 *x, int *len);
unsigned char *ossl_X509_keyid_get0(ossl_X509 *x, int *len);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_REVOKED)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_CRL_INFO)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_X509_CRL)
ossl_X509_CRL *ossl_X509_CRL_new_ex(ossl_OSSL_LIB_CTX *libctx, const char *propq);

int ossl_X509_CRL_add0_revoked(ossl_X509_CRL *crl, ossl_X509_REVOKED *rev);
int ossl_X509_CRL_get0_by_serial(ossl_X509_CRL *crl,
                            ossl_X509_REVOKED **ret, const ossl_ASN1_INTEGER *serial);
int ossl_X509_CRL_get0_by_cert(ossl_X509_CRL *crl, ossl_X509_REVOKED **ret, ossl_X509 *x);

ossl_X509_PKEY *ossl_X509_PKEY_new(void);
void ossl_X509_PKEY_free(ossl_X509_PKEY *a);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_NETSCAPE_SPKI)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_NETSCAPE_SPKAC)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_NETSCAPE_CERT_SEQUENCE)

ossl_X509_INFO *ossl_X509_INFO_new(void);
void ossl_X509_INFO_free(ossl_X509_INFO *a);
char *ossl_X509_NAME_oneline(const ossl_X509_NAME *a, char *buf, int size);

#ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_ASN1_verify(ossl_i2d_of_void *i2d, ossl_X509_ALGOR *algor1,
                ossl_ASN1_BIT_STRING *signature, char *data, ossl_EVP_PKEY *pkey);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_ASN1_digest(ossl_i2d_of_void *i2d, const ossl_EVP_MD *type, char *data,
                unsigned char *md, unsigned int *len);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_ASN1_sign(ossl_i2d_of_void *i2d, ossl_X509_ALGOR *algor1, ossl_X509_ALGOR *algor2,
              ossl_ASN1_BIT_STRING *signature, char *data, ossl_EVP_PKEY *pkey,
              const ossl_EVP_MD *type);
#endif
int ossl_ASN1_item_digest(const ossl_ASN1_ITEM *it, const ossl_EVP_MD *type, void *data,
                     unsigned char *md, unsigned int *len);
int ossl_ASN1_item_verify(const ossl_ASN1_ITEM *it, const ossl_X509_ALGOR *alg,
                     const ossl_ASN1_BIT_STRING *signature, const void *data,
                     ossl_EVP_PKEY *pkey);
int ossl_ASN1_item_verify_ctx(const ossl_ASN1_ITEM *it, const ossl_X509_ALGOR *alg,
                         const ossl_ASN1_BIT_STRING *signature, const void *data,
                         ossl_EVP_MD_CTX *ctx);
int ossl_ASN1_item_sign(const ossl_ASN1_ITEM *it, ossl_X509_ALGOR *algor1, ossl_X509_ALGOR *algor2,
                   ossl_ASN1_BIT_STRING *signature, const void *data,
                   ossl_EVP_PKEY *pkey, const ossl_EVP_MD *md);
int ossl_ASN1_item_sign_ctx(const ossl_ASN1_ITEM *it, ossl_X509_ALGOR *algor1,
                       ossl_X509_ALGOR *algor2, ossl_ASN1_BIT_STRING *signature,
                       const void *data, ossl_EVP_MD_CTX *ctx);

#define ossl_X509_VERSION_1 0
#define ossl_X509_VERSION_2 1
#define ossl_X509_VERSION_3 2

long ossl_X509_get_version(const ossl_X509 *x);
int ossl_X509_set_version(ossl_X509 *x, long version);
int ossl_X509_set_serialNumber(ossl_X509 *x, ossl_ASN1_INTEGER *serial);
ossl_ASN1_INTEGER *ossl_X509_get_serialNumber(ossl_X509 *x);
const ossl_ASN1_INTEGER *ossl_X509_get0_serialNumber(const ossl_X509 *x);
int ossl_X509_set_issuer_name(ossl_X509 *x, const ossl_X509_NAME *name);
ossl_X509_NAME *ossl_X509_get_issuer_name(const ossl_X509 *a);
int ossl_X509_set_subject_name(ossl_X509 *x, const ossl_X509_NAME *name);
ossl_X509_NAME *ossl_X509_get_subject_name(const ossl_X509 *a);
const ossl_ASN1_TIME * ossl_X509_get0_notBefore(const ossl_X509 *x);
ossl_ASN1_TIME *ossl_X509_getm_notBefore(const ossl_X509 *x);
int ossl_X509_set1_notBefore(ossl_X509 *x, const ossl_ASN1_TIME *tm);
const ossl_ASN1_TIME *ossl_X509_get0_notAfter(const ossl_X509 *x);
ossl_ASN1_TIME *ossl_X509_getm_notAfter(const ossl_X509 *x);
int ossl_X509_set1_notAfter(ossl_X509 *x, const ossl_ASN1_TIME *tm);
int ossl_X509_set_pubkey(ossl_X509 *x, ossl_EVP_PKEY *pkey);
int ossl_X509_up_ref(ossl_X509 *x);
int ossl_X509_get_signature_type(const ossl_X509 *x);

# ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
#  define ossl_X509_get_notBefore ossl_X509_getm_notBefore
#  define ossl_X509_get_notAfter ossl_X509_getm_notAfter
#  define ossl_X509_set_notBefore ossl_X509_set1_notBefore
#  define ossl_X509_set_notAfter ossl_X509_set1_notAfter
#endif


/*
 * This one is only used so that a binary form can output, as in
 * ossl_i2d_X509_PUBKEY(ossl_X509_get_X509_PUBKEY(x), &buf)
 */
ossl_X509_PUBKEY *ossl_X509_get_X509_PUBKEY(const ossl_X509 *x);
const ossl_STACK_OF(ossl_X509_EXTENSION) *ossl_X509_get0_extensions(const ossl_X509 *x);
void ossl_X509_get0_uids(const ossl_X509 *x, const ossl_ASN1_BIT_STRING **piuid,
                    const ossl_ASN1_BIT_STRING **psuid);
const ossl_X509_ALGOR *ossl_X509_get0_tbs_sigalg(const ossl_X509 *x);

ossl_EVP_PKEY *ossl_X509_get0_pubkey(const ossl_X509 *x);
ossl_EVP_PKEY *ossl_X509_get_pubkey(ossl_X509 *x);
ossl_ASN1_BIT_STRING *ossl_X509_get0_pubkey_bitstr(const ossl_X509 *x);

#define ossl_X509_REQ_VERSION_1 0

long ossl_X509_REQ_get_version(const ossl_X509_REQ *req);
int ossl_X509_REQ_set_version(ossl_X509_REQ *x, long version);
ossl_X509_NAME *ossl_X509_REQ_get_subject_name(const ossl_X509_REQ *req);
int ossl_X509_REQ_set_subject_name(ossl_X509_REQ *req, const ossl_X509_NAME *name);
void ossl_X509_REQ_get0_signature(const ossl_X509_REQ *req, const ossl_ASN1_BIT_STRING **psig,
                             const ossl_X509_ALGOR **palg);
void ossl_X509_REQ_set0_signature(ossl_X509_REQ *req, ossl_ASN1_BIT_STRING *psig);
int ossl_X509_REQ_set1_signature_algo(ossl_X509_REQ *req, ossl_X509_ALGOR *palg);
int ossl_X509_REQ_get_signature_nid(const ossl_X509_REQ *req);
int ossl_i2d_re_X509_REQ_tbs(ossl_X509_REQ *req, unsigned char **pp);
int ossl_X509_REQ_set_pubkey(ossl_X509_REQ *x, ossl_EVP_PKEY *pkey);
ossl_EVP_PKEY *ossl_X509_REQ_get_pubkey(ossl_X509_REQ *req);
ossl_EVP_PKEY *ossl_X509_REQ_get0_pubkey(ossl_X509_REQ *req);
ossl_X509_PUBKEY *ossl_X509_REQ_get_X509_PUBKEY(ossl_X509_REQ *req);
int ossl_X509_REQ_extension_nid(int nid);
int *ossl_X509_REQ_get_extension_nids(void);
void ossl_X509_REQ_set_extension_nids(int *nids);
ossl_STACK_OF(ossl_X509_EXTENSION) *ossl_X509_REQ_get_extensions(ossl_X509_REQ *req);
int ossl_X509_REQ_add_extensions_nid(ossl_X509_REQ *req,
                                const ossl_STACK_OF(ossl_X509_EXTENSION) *exts, int nid);
int ossl_X509_REQ_add_extensions(ossl_X509_REQ *req, const ossl_STACK_OF(ossl_X509_EXTENSION) *ext);
int ossl_X509_REQ_get_attr_count(const ossl_X509_REQ *req);
int ossl_X509_REQ_get_attr_by_NID(const ossl_X509_REQ *req, int nid, int lastpos);
int ossl_X509_REQ_get_attr_by_OBJ(const ossl_X509_REQ *req, const ossl_ASN1_OBJECT *obj,
                             int lastpos);
ossl_X509_ATTRIBUTE *ossl_X509_REQ_get_attr(const ossl_X509_REQ *req, int loc);
ossl_X509_ATTRIBUTE *ossl_X509_REQ_delete_attr(ossl_X509_REQ *req, int loc);
int ossl_X509_REQ_add1_attr(ossl_X509_REQ *req, ossl_X509_ATTRIBUTE *attr);
int ossl_X509_REQ_add1_attr_by_OBJ(ossl_X509_REQ *req,
                              const ossl_ASN1_OBJECT *obj, int type,
                              const unsigned char *bytes, int len);
int ossl_X509_REQ_add1_attr_by_NID(ossl_X509_REQ *req,
                              int nid, int type,
                              const unsigned char *bytes, int len);
int ossl_X509_REQ_add1_attr_by_txt(ossl_X509_REQ *req,
                              const char *attrname, int type,
                              const unsigned char *bytes, int len);

#define ossl_X509_CRL_VERSION_1 0
#define ossl_X509_CRL_VERSION_2 1

int ossl_X509_CRL_set_version(ossl_X509_CRL *x, long version);
int ossl_X509_CRL_set_issuer_name(ossl_X509_CRL *x, const ossl_X509_NAME *name);
int ossl_X509_CRL_set1_lastUpdate(ossl_X509_CRL *x, const ossl_ASN1_TIME *tm);
int ossl_X509_CRL_set1_nextUpdate(ossl_X509_CRL *x, const ossl_ASN1_TIME *tm);
int ossl_X509_CRL_sort(ossl_X509_CRL *crl);
int ossl_X509_CRL_up_ref(ossl_X509_CRL *crl);

# ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
#  define ossl_X509_CRL_set_lastUpdate ossl_X509_CRL_set1_lastUpdate
#  define ossl_X509_CRL_set_nextUpdate ossl_X509_CRL_set1_nextUpdate
#endif

long ossl_X509_CRL_get_version(const ossl_X509_CRL *crl);
const ossl_ASN1_TIME *ossl_X509_CRL_get0_lastUpdate(const ossl_X509_CRL *crl);
const ossl_ASN1_TIME *ossl_X509_CRL_get0_nextUpdate(const ossl_X509_CRL *crl);
#ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
ossl_OSSL_DEPRECATEDIN_1_1_0 ossl_ASN1_TIME *ossl_X509_CRL_get_lastUpdate(ossl_X509_CRL *crl);
ossl_OSSL_DEPRECATEDIN_1_1_0 ossl_ASN1_TIME *ossl_X509_CRL_get_nextUpdate(ossl_X509_CRL *crl);
#endif
ossl_X509_NAME *ossl_X509_CRL_get_issuer(const ossl_X509_CRL *crl);
const ossl_STACK_OF(ossl_X509_EXTENSION) *ossl_X509_CRL_get0_extensions(const ossl_X509_CRL *crl);
ossl_STACK_OF(ossl_X509_REVOKED) *ossl_X509_CRL_get_REVOKED(ossl_X509_CRL *crl);
void ossl_X509_CRL_get0_signature(const ossl_X509_CRL *crl, const ossl_ASN1_BIT_STRING **psig,
                             const ossl_X509_ALGOR **palg);
int ossl_X509_CRL_get_signature_nid(const ossl_X509_CRL *crl);
int ossl_i2d_re_X509_CRL_tbs(ossl_X509_CRL *req, unsigned char **pp);

const ossl_ASN1_INTEGER *ossl_X509_REVOKED_get0_serialNumber(const ossl_X509_REVOKED *x);
int ossl_X509_REVOKED_set_serialNumber(ossl_X509_REVOKED *x, ossl_ASN1_INTEGER *serial);
const ossl_ASN1_TIME *ossl_X509_REVOKED_get0_revocationDate(const ossl_X509_REVOKED *x);
int ossl_X509_REVOKED_set_revocationDate(ossl_X509_REVOKED *r, ossl_ASN1_TIME *tm);
const ossl_STACK_OF(ossl_X509_EXTENSION) *
ossl_X509_REVOKED_get0_extensions(const ossl_X509_REVOKED *r);

ossl_X509_CRL *ossl_X509_CRL_diff(ossl_X509_CRL *base, ossl_X509_CRL *newer,
                        ossl_EVP_PKEY *skey, const ossl_EVP_MD *md, unsigned int flags);

int ossl_X509_REQ_check_private_key(ossl_X509_REQ *x509, ossl_EVP_PKEY *pkey);

int ossl_X509_check_private_key(const ossl_X509 *x509, const ossl_EVP_PKEY *pkey);
int ossl_X509_chain_check_suiteb(int *perror_depth,
                            ossl_X509 *x, ossl_STACK_OF(ossl_X509) *chain,
                            unsigned long flags);
int ossl_X509_CRL_check_suiteb(ossl_X509_CRL *crl, ossl_EVP_PKEY *pk, unsigned long flags);
ossl_STACK_OF(ossl_X509) *ossl_X509_chain_up_ref(ossl_STACK_OF(ossl_X509) *chain);

int ossl_X509_issuer_and_serial_cmp(const ossl_X509 *a, const ossl_X509 *b);
unsigned long ossl_X509_issuer_and_serial_hash(ossl_X509 *a);

int ossl_X509_issuer_name_cmp(const ossl_X509 *a, const ossl_X509 *b);
unsigned long ossl_X509_issuer_name_hash(ossl_X509 *a);

int ossl_X509_subject_name_cmp(const ossl_X509 *a, const ossl_X509 *b);
unsigned long ossl_X509_subject_name_hash(ossl_X509 *x);

# ifndef ossl_OPENSSL_NO_MD5
unsigned long ossl_X509_issuer_name_hash_old(ossl_X509 *a);
unsigned long ossl_X509_subject_name_hash_old(ossl_X509 *x);
# endif

# define ossl_X509_ADD_FLAG_DEFAULT  0
# define ossl_X509_ADD_FLAG_UP_REF   0x1
# define ossl_X509_ADD_FLAG_PREPEND  0x2
# define ossl_X509_ADD_FLAG_NO_DUP   0x4
# define ossl_X509_ADD_FLAG_NO_SS    0x8
int ossl_X509_add_cert(ossl_STACK_OF(ossl_X509) *sk, ossl_X509 *cert, int flags);
int ossl_X509_add_certs(ossl_STACK_OF(ossl_X509) *sk, ossl_STACK_OF(ossl_X509) *certs, int flags);

int ossl_X509_cmp(const ossl_X509 *a, const ossl_X509 *b);
int ossl_X509_NAME_cmp(const ossl_X509_NAME *a, const ossl_X509_NAME *b);
#ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
# define ossl_X509_NAME_hash(x) ossl_X509_NAME_hash_ex(x, NULL, NULL, NULL)
ossl_OSSL_DEPRECATEDIN_3_0 int ossl_X509_certificate_type(const ossl_X509 *x,
                                                const ossl_EVP_PKEY *pubkey);
#endif
unsigned long ossl_X509_NAME_hash_ex(const ossl_X509_NAME *x, ossl_OSSL_LIB_CTX *libctx,
                                const char *propq, int *ok);
unsigned long ossl_X509_NAME_hash_old(const ossl_X509_NAME *x);

int ossl_X509_CRL_cmp(const ossl_X509_CRL *a, const ossl_X509_CRL *b);
int ossl_X509_CRL_match(const ossl_X509_CRL *a, const ossl_X509_CRL *b);
int ossl_X509_aux_print(ossl_BIO *out, ossl_X509 *x, int indent);
# ifndef ossl_OPENSSL_NO_STDIO
int ossl_X509_print_ex_fp(FILE *bp, ossl_X509 *x, unsigned long nmflag,
                     unsigned long cflag);
int ossl_X509_print_fp(FILE *bp, ossl_X509 *x);
int ossl_X509_CRL_print_fp(FILE *bp, ossl_X509_CRL *x);
int ossl_X509_REQ_print_fp(FILE *bp, ossl_X509_REQ *req);
int ossl_X509_NAME_print_ex_fp(FILE *fp, const ossl_X509_NAME *nm, int indent,
                          unsigned long flags);
# endif

int ossl_X509_NAME_print(ossl_BIO *bp, const ossl_X509_NAME *name, int obase);
int ossl_X509_NAME_print_ex(ossl_BIO *out, const ossl_X509_NAME *nm, int indent,
                       unsigned long flags);
int ossl_X509_print_ex(ossl_BIO *bp, ossl_X509 *x, unsigned long nmflag,
                  unsigned long cflag);
int ossl_X509_print(ossl_BIO *bp, ossl_X509 *x);
int ossl_X509_ocspid_print(ossl_BIO *bp, ossl_X509 *x);
int ossl_X509_CRL_print_ex(ossl_BIO *out, ossl_X509_CRL *x, unsigned long nmflag);
int ossl_X509_CRL_print(ossl_BIO *bp, ossl_X509_CRL *x);
int ossl_X509_REQ_print_ex(ossl_BIO *bp, ossl_X509_REQ *x, unsigned long nmflag,
                      unsigned long cflag);
int ossl_X509_REQ_print(ossl_BIO *bp, ossl_X509_REQ *req);

int ossl_X509_NAME_entry_count(const ossl_X509_NAME *name);
int ossl_X509_NAME_get_text_by_NID(const ossl_X509_NAME *name, int nid,
                              char *buf, int len);
int ossl_X509_NAME_get_text_by_OBJ(const ossl_X509_NAME *name, const ossl_ASN1_OBJECT *obj,
                              char *buf, int len);

/*
 * NOTE: you should be passing -1, not 0 as lastpos. The functions that use
 * lastpos, search after that position on.
 */
int ossl_X509_NAME_get_index_by_NID(const ossl_X509_NAME *name, int nid, int lastpos);
int ossl_X509_NAME_get_index_by_OBJ(const ossl_X509_NAME *name, const ossl_ASN1_OBJECT *obj,
                               int lastpos);
ossl_X509_NAME_ENTRY *ossl_X509_NAME_get_entry(const ossl_X509_NAME *name, int loc);
ossl_X509_NAME_ENTRY *ossl_X509_NAME_delete_entry(ossl_X509_NAME *name, int loc);
int ossl_X509_NAME_add_entry(ossl_X509_NAME *name, const ossl_X509_NAME_ENTRY *ne,
                        int loc, int set);
int ossl_X509_NAME_add_entry_by_OBJ(ossl_X509_NAME *name, const ossl_ASN1_OBJECT *obj, int type,
                               const unsigned char *bytes, int len, int loc,
                               int set);
int ossl_X509_NAME_add_entry_by_NID(ossl_X509_NAME *name, int nid, int type,
                               const unsigned char *bytes, int len, int loc,
                               int set);
ossl_X509_NAME_ENTRY *ossl_X509_NAME_ENTRY_create_by_txt(ossl_X509_NAME_ENTRY **ne,
                                               const char *field, int type,
                                               const unsigned char *bytes,
                                               int len);
ossl_X509_NAME_ENTRY *ossl_X509_NAME_ENTRY_create_by_NID(ossl_X509_NAME_ENTRY **ne, int nid,
                                               int type,
                                               const unsigned char *bytes,
                                               int len);
int ossl_X509_NAME_add_entry_by_txt(ossl_X509_NAME *name, const char *field, int type,
                               const unsigned char *bytes, int len, int loc,
                               int set);
ossl_X509_NAME_ENTRY *ossl_X509_NAME_ENTRY_create_by_OBJ(ossl_X509_NAME_ENTRY **ne,
                                               const ossl_ASN1_OBJECT *obj, int type,
                                               const unsigned char *bytes,
                                               int len);
int ossl_X509_NAME_ENTRY_set_object(ossl_X509_NAME_ENTRY *ne, const ossl_ASN1_OBJECT *obj);
int ossl_X509_NAME_ENTRY_set_data(ossl_X509_NAME_ENTRY *ne, int type,
                             const unsigned char *bytes, int len);
ossl_ASN1_OBJECT *ossl_X509_NAME_ENTRY_get_object(const ossl_X509_NAME_ENTRY *ne);
ossl_ASN1_STRING * ossl_X509_NAME_ENTRY_get_data(const ossl_X509_NAME_ENTRY *ne);
int ossl_X509_NAME_ENTRY_set(const ossl_X509_NAME_ENTRY *ne);

int ossl_X509_NAME_get0_der(const ossl_X509_NAME *nm, const unsigned char **pder,
                       size_t *pderlen);

int ossl_X509v3_get_ext_count(const ossl_STACK_OF(ossl_X509_EXTENSION) *x);
int ossl_X509v3_get_ext_by_NID(const ossl_STACK_OF(ossl_X509_EXTENSION) *x,
                          int nid, int lastpos);
int ossl_X509v3_get_ext_by_OBJ(const ossl_STACK_OF(ossl_X509_EXTENSION) *x,
                          const ossl_ASN1_OBJECT *obj, int lastpos);
int ossl_X509v3_get_ext_by_critical(const ossl_STACK_OF(ossl_X509_EXTENSION) *x,
                               int crit, int lastpos);
ossl_X509_EXTENSION *ossl_X509v3_get_ext(const ossl_STACK_OF(ossl_X509_EXTENSION) *x, int loc);
ossl_X509_EXTENSION *ossl_X509v3_delete_ext(ossl_STACK_OF(ossl_X509_EXTENSION) *x, int loc);
ossl_STACK_OF(ossl_X509_EXTENSION) *ossl_X509v3_add_ext(ossl_STACK_OF(ossl_X509_EXTENSION) **x,
                                         ossl_X509_EXTENSION *ex, int loc);

int ossl_X509_get_ext_count(const ossl_X509 *x);
int ossl_X509_get_ext_by_NID(const ossl_X509 *x, int nid, int lastpos);
int ossl_X509_get_ext_by_OBJ(const ossl_X509 *x, const ossl_ASN1_OBJECT *obj, int lastpos);
int ossl_X509_get_ext_by_critical(const ossl_X509 *x, int crit, int lastpos);
ossl_X509_EXTENSION *ossl_X509_get_ext(const ossl_X509 *x, int loc);
ossl_X509_EXTENSION *ossl_X509_delete_ext(ossl_X509 *x, int loc);
int ossl_X509_add_ext(ossl_X509 *x, ossl_X509_EXTENSION *ex, int loc);
void *ossl_X509_get_ext_d2i(const ossl_X509 *x, int nid, int *crit, int *idx);
int ossl_X509_add1_ext_i2d(ossl_X509 *x, int nid, void *value, int crit,
                      unsigned long flags);

int ossl_X509_CRL_get_ext_count(const ossl_X509_CRL *x);
int ossl_X509_CRL_get_ext_by_NID(const ossl_X509_CRL *x, int nid, int lastpos);
int ossl_X509_CRL_get_ext_by_OBJ(const ossl_X509_CRL *x, const ossl_ASN1_OBJECT *obj,
                            int lastpos);
int ossl_X509_CRL_get_ext_by_critical(const ossl_X509_CRL *x, int crit, int lastpos);
ossl_X509_EXTENSION *ossl_X509_CRL_get_ext(const ossl_X509_CRL *x, int loc);
ossl_X509_EXTENSION *ossl_X509_CRL_delete_ext(ossl_X509_CRL *x, int loc);
int ossl_X509_CRL_add_ext(ossl_X509_CRL *x, ossl_X509_EXTENSION *ex, int loc);
void *ossl_X509_CRL_get_ext_d2i(const ossl_X509_CRL *x, int nid, int *crit, int *idx);
int ossl_X509_CRL_add1_ext_i2d(ossl_X509_CRL *x, int nid, void *value, int crit,
                          unsigned long flags);

int ossl_X509_REVOKED_get_ext_count(const ossl_X509_REVOKED *x);
int ossl_X509_REVOKED_get_ext_by_NID(const ossl_X509_REVOKED *x, int nid, int lastpos);
int ossl_X509_REVOKED_get_ext_by_OBJ(const ossl_X509_REVOKED *x, const ossl_ASN1_OBJECT *obj,
                                int lastpos);
int ossl_X509_REVOKED_get_ext_by_critical(const ossl_X509_REVOKED *x, int crit,
                                     int lastpos);
ossl_X509_EXTENSION *ossl_X509_REVOKED_get_ext(const ossl_X509_REVOKED *x, int loc);
ossl_X509_EXTENSION *ossl_X509_REVOKED_delete_ext(ossl_X509_REVOKED *x, int loc);
int ossl_X509_REVOKED_add_ext(ossl_X509_REVOKED *x, ossl_X509_EXTENSION *ex, int loc);
void *ossl_X509_REVOKED_get_ext_d2i(const ossl_X509_REVOKED *x, int nid, int *crit,
                               int *idx);
int ossl_X509_REVOKED_add1_ext_i2d(ossl_X509_REVOKED *x, int nid, void *value, int crit,
                              unsigned long flags);

ossl_X509_EXTENSION *ossl_X509_EXTENSION_create_by_NID(ossl_X509_EXTENSION **ex,
                                             int nid, int crit,
                                             ossl_ASN1_OCTET_STRING *data);
ossl_X509_EXTENSION *ossl_X509_EXTENSION_create_by_OBJ(ossl_X509_EXTENSION **ex,
                                             const ossl_ASN1_OBJECT *obj, int crit,
                                             ossl_ASN1_OCTET_STRING *data);
int ossl_X509_EXTENSION_set_object(ossl_X509_EXTENSION *ex, const ossl_ASN1_OBJECT *obj);
int ossl_X509_EXTENSION_set_critical(ossl_X509_EXTENSION *ex, int crit);
int ossl_X509_EXTENSION_set_data(ossl_X509_EXTENSION *ex, ossl_ASN1_OCTET_STRING *data);
ossl_ASN1_OBJECT *ossl_X509_EXTENSION_get_object(ossl_X509_EXTENSION *ex);
ossl_ASN1_OCTET_STRING *ossl_X509_EXTENSION_get_data(ossl_X509_EXTENSION *ne);
int ossl_X509_EXTENSION_get_critical(const ossl_X509_EXTENSION *ex);

int ossl_X509at_get_attr_count(const ossl_STACK_OF(ossl_X509_ATTRIBUTE) *x);
int ossl_X509at_get_attr_by_NID(const ossl_STACK_OF(ossl_X509_ATTRIBUTE) *x, int nid,
                           int lastpos);
int ossl_X509at_get_attr_by_OBJ(const ossl_STACK_OF(ossl_X509_ATTRIBUTE) *sk,
                           const ossl_ASN1_OBJECT *obj, int lastpos);
ossl_X509_ATTRIBUTE *ossl_X509at_get_attr(const ossl_STACK_OF(ossl_X509_ATTRIBUTE) *x, int loc);
ossl_X509_ATTRIBUTE *ossl_X509at_delete_attr(ossl_STACK_OF(ossl_X509_ATTRIBUTE) *x, int loc);
ossl_STACK_OF(ossl_X509_ATTRIBUTE) *ossl_X509at_add1_attr(ossl_STACK_OF(ossl_X509_ATTRIBUTE) **x,
                                           ossl_X509_ATTRIBUTE *attr);
ossl_STACK_OF(ossl_X509_ATTRIBUTE) *ossl_X509at_add1_attr_by_OBJ(ossl_STACK_OF(ossl_X509_ATTRIBUTE)
                                                  **x, const ossl_ASN1_OBJECT *obj,
                                                  int type,
                                                  const unsigned char *bytes,
                                                  int len);
ossl_STACK_OF(ossl_X509_ATTRIBUTE) *ossl_X509at_add1_attr_by_NID(ossl_STACK_OF(ossl_X509_ATTRIBUTE)
                                                  **x, int nid, int type,
                                                  const unsigned char *bytes,
                                                  int len);
ossl_STACK_OF(ossl_X509_ATTRIBUTE) *ossl_X509at_add1_attr_by_txt(ossl_STACK_OF(ossl_X509_ATTRIBUTE)
                                                  **x, const char *attrname,
                                                  int type,
                                                  const unsigned char *bytes,
                                                  int len);
void *ossl_X509at_get0_data_by_OBJ(const ossl_STACK_OF(ossl_X509_ATTRIBUTE) *x,
                              const ossl_ASN1_OBJECT *obj, int lastpos, int type);
ossl_X509_ATTRIBUTE *ossl_X509_ATTRIBUTE_create_by_NID(ossl_X509_ATTRIBUTE **attr, int nid,
                                             int atrtype, const void *data,
                                             int len);
ossl_X509_ATTRIBUTE *ossl_X509_ATTRIBUTE_create_by_OBJ(ossl_X509_ATTRIBUTE **attr,
                                             const ossl_ASN1_OBJECT *obj,
                                             int atrtype, const void *data,
                                             int len);
ossl_X509_ATTRIBUTE *ossl_X509_ATTRIBUTE_create_by_txt(ossl_X509_ATTRIBUTE **attr,
                                             const char *atrname, int type,
                                             const unsigned char *bytes,
                                             int len);
int ossl_X509_ATTRIBUTE_set1_object(ossl_X509_ATTRIBUTE *attr, const ossl_ASN1_OBJECT *obj);
int ossl_X509_ATTRIBUTE_set1_data(ossl_X509_ATTRIBUTE *attr, int attrtype,
                             const void *data, int len);
void *ossl_X509_ATTRIBUTE_get0_data(ossl_X509_ATTRIBUTE *attr, int idx, int atrtype,
                               void *data);
int ossl_X509_ATTRIBUTE_count(const ossl_X509_ATTRIBUTE *attr);
ossl_ASN1_OBJECT *ossl_X509_ATTRIBUTE_get0_object(ossl_X509_ATTRIBUTE *attr);
ossl_ASN1_TYPE *ossl_X509_ATTRIBUTE_get0_type(ossl_X509_ATTRIBUTE *attr, int idx);

int ossl_EVP_PKEY_get_attr_count(const ossl_EVP_PKEY *key);
int ossl_EVP_PKEY_get_attr_by_NID(const ossl_EVP_PKEY *key, int nid, int lastpos);
int ossl_EVP_PKEY_get_attr_by_OBJ(const ossl_EVP_PKEY *key, const ossl_ASN1_OBJECT *obj,
                             int lastpos);
ossl_X509_ATTRIBUTE *ossl_EVP_PKEY_get_attr(const ossl_EVP_PKEY *key, int loc);
ossl_X509_ATTRIBUTE *ossl_EVP_PKEY_delete_attr(ossl_EVP_PKEY *key, int loc);
int ossl_EVP_PKEY_add1_attr(ossl_EVP_PKEY *key, ossl_X509_ATTRIBUTE *attr);
int ossl_EVP_PKEY_add1_attr_by_OBJ(ossl_EVP_PKEY *key,
                              const ossl_ASN1_OBJECT *obj, int type,
                              const unsigned char *bytes, int len);
int ossl_EVP_PKEY_add1_attr_by_NID(ossl_EVP_PKEY *key,
                              int nid, int type,
                              const unsigned char *bytes, int len);
int ossl_EVP_PKEY_add1_attr_by_txt(ossl_EVP_PKEY *key,
                              const char *attrname, int type,
                              const unsigned char *bytes, int len);

/* lookup a cert from a ossl_X509 STACK */
ossl_X509 *ossl_X509_find_by_issuer_and_serial(ossl_STACK_OF(ossl_X509) *sk, const ossl_X509_NAME *name,
                                     const ossl_ASN1_INTEGER *serial);
ossl_X509 *ossl_X509_find_by_subject(ossl_STACK_OF(ossl_X509) *sk, const ossl_X509_NAME *name);

ossl_DECLARE_ASN1_FUNCTIONS(ossl_PBEPARAM)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_PBE2PARAM)
ossl_DECLARE_ASN1_FUNCTIONS(ossl_PBKDF2PARAM)
#ifndef ossl_OPENSSL_NO_SCRYPT
ossl_DECLARE_ASN1_FUNCTIONS(ossl_SCRYPT_PARAMS)
#endif

int ossl_PKCS5_pbe_set0_algor(ossl_X509_ALGOR *algor, int alg, int iter,
                         const unsigned char *salt, int saltlen);
int ossl_PKCS5_pbe_set0_algor_ex(ossl_X509_ALGOR *algor, int alg, int iter,
                            const unsigned char *salt, int saltlen,
                            ossl_OSSL_LIB_CTX *libctx);

ossl_X509_ALGOR *ossl_PKCS5_pbe_set(int alg, int iter,
                          const unsigned char *salt, int saltlen);
ossl_X509_ALGOR *ossl_PKCS5_pbe_set_ex(int alg, int iter,
                             const unsigned char *salt, int saltlen,
                             ossl_OSSL_LIB_CTX *libctx);

ossl_X509_ALGOR *ossl_PKCS5_pbe2_set(const ossl_EVP_CIPHER *cipher, int iter,
                           unsigned char *salt, int saltlen);
ossl_X509_ALGOR *ossl_PKCS5_pbe2_set_iv(const ossl_EVP_CIPHER *cipher, int iter,
                              unsigned char *salt, int saltlen,
                              unsigned char *aiv, int prf_nid);
ossl_X509_ALGOR *ossl_PKCS5_pbe2_set_iv_ex(const ossl_EVP_CIPHER *cipher, int iter,
                                 unsigned char *salt, int saltlen,
                                 unsigned char *aiv, int prf_nid,
                                 ossl_OSSL_LIB_CTX *libctx);

#ifndef ossl_OPENSSL_NO_SCRYPT
ossl_X509_ALGOR *ossl_PKCS5_pbe2_set_scrypt(const ossl_EVP_CIPHER *cipher,
                                  const unsigned char *salt, int saltlen,
                                  unsigned char *aiv, uint64_t N, uint64_t r,
                                  uint64_t p);
#endif

ossl_X509_ALGOR *ossl_PKCS5_pbkdf2_set(int iter, unsigned char *salt, int saltlen,
                             int prf_nid, int keylen);
ossl_X509_ALGOR *ossl_PKCS5_pbkdf2_set_ex(int iter, unsigned char *salt, int saltlen,
                                int prf_nid, int keylen,
                                ossl_OSSL_LIB_CTX *libctx);

/* PKCS#8 utilities */

ossl_DECLARE_ASN1_FUNCTIONS(ossl_PKCS8_PRIV_KEY_INFO)

ossl_EVP_PKEY *ossl_EVP_PKCS82PKEY(const ossl_PKCS8_PRIV_KEY_INFO *p8);
ossl_EVP_PKEY *ossl_EVP_PKCS82PKEY_ex(const ossl_PKCS8_PRIV_KEY_INFO *p8, ossl_OSSL_LIB_CTX *libctx,
                            const char *propq);
ossl_PKCS8_PRIV_KEY_INFO *ossl_EVP_PKEY2PKCS8(const ossl_EVP_PKEY *pkey);

int ossl_PKCS8_pkey_set0(ossl_PKCS8_PRIV_KEY_INFO *priv, ossl_ASN1_OBJECT *aobj,
                    int version, int ptype, void *pval,
                    unsigned char *penc, int penclen);
int ossl_PKCS8_pkey_get0(const ossl_ASN1_OBJECT **ppkalg,
                    const unsigned char **pk, int *ppklen,
                    const ossl_X509_ALGOR **pa, const ossl_PKCS8_PRIV_KEY_INFO *p8);

const ossl_STACK_OF(ossl_X509_ATTRIBUTE) *
ossl_PKCS8_pkey_get0_attrs(const ossl_PKCS8_PRIV_KEY_INFO *p8);
int ossl_PKCS8_pkey_add1_attr(ossl_PKCS8_PRIV_KEY_INFO *p8, ossl_X509_ATTRIBUTE *attr);
int ossl_PKCS8_pkey_add1_attr_by_NID(ossl_PKCS8_PRIV_KEY_INFO *p8, int nid, int type,
                                const unsigned char *bytes, int len);
int ossl_PKCS8_pkey_add1_attr_by_OBJ(ossl_PKCS8_PRIV_KEY_INFO *p8, const ossl_ASN1_OBJECT *obj,
                                int type, const unsigned char *bytes, int len);


int ossl_X509_PUBKEY_set0_param(ossl_X509_PUBKEY *pub, ossl_ASN1_OBJECT *aobj,
                           int ptype, void *pval,
                           unsigned char *penc, int penclen);
int ossl_X509_PUBKEY_get0_param(ossl_ASN1_OBJECT **ppkalg,
                           const unsigned char **pk, int *ppklen,
                           ossl_X509_ALGOR **pa, const ossl_X509_PUBKEY *pub);
int ossl_X509_PUBKEY_eq(const ossl_X509_PUBKEY *a, const ossl_X509_PUBKEY *b);

# ifdef  __cplusplus
}
# endif
#endif
