/*
 * WARNING: do not edit!
 * Generated by Makefile from ../../../openssl/source/include/openssl/x509_vfy.h.in
 *
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */



#ifndef ossl_OPENSSL_X509_VFY_H
# define ossl_OPENSSL_X509_VFY_H
# pragma once

# include "ossl/openssl/macros.h"
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#  define ossl_HEADER_X509_VFY_H
# endif

/*
 * Protect against recursion, x509.h and x509_vfy.h each include the other.
 */
# ifndef ossl_OPENSSL_X509_H
#  include "ossl/openssl/x509.h"
# endif

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/lhash.h"
# include "ossl/openssl/bio.h"
# include "ossl/openssl/crypto.h"
# include "ossl/openssl/symhacks.h"

#ifdef  __cplusplus
extern "C" {
#endif

/*-
ossl_SSL_CTX -> ossl_X509_STORE
                -> ossl_X509_LOOKUP
                        ->ossl_X509_LOOKUP_METHOD
                -> ossl_X509_LOOKUP
                        ->ossl_X509_LOOKUP_METHOD

ossl_SSL     -> ossl_X509_STORE_CTX
                ->ossl_X509_STORE

The ossl_X509_STORE holds the tables etc for verification stuff.
A ossl_X509_STORE_CTX is used while validating a single certificate.
The ossl_X509_STORE has X509_LOOKUPs for looking up certs.
The ossl_X509_STORE then calls a function to actually verify the
certificate chain.
*/

typedef enum {
    ossl_X509_LU_NONE = 0,
    ossl_X509_LU_X509, ossl_X509_LU_CRL
} ossl_X509_LOOKUP_TYPE;

#ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
#define ossl_X509_LU_RETRY   -1
#define ossl_X509_LU_FAIL    0
#endif

ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_LOOKUP, ossl_X509_LOOKUP, ossl_X509_LOOKUP)
#define ossl_sk_X509_LOOKUP_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_LOOKUP_sk_type(sk))
#define ossl_sk_X509_LOOKUP_value(sk, idx) ((ossl_X509_LOOKUP *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_LOOKUP_sk_type(sk), (idx)))
#define ossl_sk_X509_LOOKUP_new(cmp) ((ossl_STACK_OF(ossl_X509_LOOKUP) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_LOOKUP_compfunc_type(cmp)))
#define ossl_sk_X509_LOOKUP_new_null() ((ossl_STACK_OF(ossl_X509_LOOKUP) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_LOOKUP_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_LOOKUP) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_LOOKUP_compfunc_type(cmp), (n)))
#define ossl_sk_X509_LOOKUP_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_LOOKUP_sk_type(sk), (n))
#define ossl_sk_X509_LOOKUP_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_LOOKUP_sk_type(sk))
#define ossl_sk_X509_LOOKUP_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_LOOKUP_sk_type(sk))
#define ossl_sk_X509_LOOKUP_delete(sk, i) ((ossl_X509_LOOKUP *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_LOOKUP_sk_type(sk), (i)))
#define ossl_sk_X509_LOOKUP_delete_ptr(sk, ptr) ((ossl_X509_LOOKUP *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr)))
#define ossl_sk_X509_LOOKUP_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr))
#define ossl_sk_X509_LOOKUP_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr))
#define ossl_sk_X509_LOOKUP_pop(sk) ((ossl_X509_LOOKUP *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_LOOKUP_sk_type(sk)))
#define ossl_sk_X509_LOOKUP_shift(sk) ((ossl_X509_LOOKUP *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_LOOKUP_sk_type(sk)))
#define ossl_sk_X509_LOOKUP_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_LOOKUP_sk_type(sk),ossl_ossl_check_X509_LOOKUP_freefunc_type(freefunc))
#define ossl_sk_X509_LOOKUP_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr), (idx))
#define ossl_sk_X509_LOOKUP_set(sk, idx, ptr) ((ossl_X509_LOOKUP *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_LOOKUP_sk_type(sk), (idx), ossl_ossl_check_X509_LOOKUP_type(ptr)))
#define ossl_sk_X509_LOOKUP_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr))
#define ossl_sk_X509_LOOKUP_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr))
#define ossl_sk_X509_LOOKUP_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_type(ptr), pnum)
#define ossl_sk_X509_LOOKUP_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_LOOKUP_sk_type(sk))
#define ossl_sk_X509_LOOKUP_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_LOOKUP_sk_type(sk))
#define ossl_sk_X509_LOOKUP_dup(sk) ((ossl_STACK_OF(ossl_X509_LOOKUP) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_LOOKUP_sk_type(sk)))
#define ossl_sk_X509_LOOKUP_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_LOOKUP) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_copyfunc_type(copyfunc), ossl_ossl_check_X509_LOOKUP_freefunc_type(freefunc)))
#define ossl_sk_X509_LOOKUP_set_cmp_func(sk, cmp) ((ossl_sk_X509_LOOKUP_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_LOOKUP_sk_type(sk), ossl_ossl_check_X509_LOOKUP_compfunc_type(cmp)))
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_OBJECT, ossl_X509_OBJECT, ossl_X509_OBJECT)
#define ossl_sk_X509_OBJECT_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_OBJECT_sk_type(sk))
#define ossl_sk_X509_OBJECT_value(sk, idx) ((ossl_X509_OBJECT *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_OBJECT_sk_type(sk), (idx)))
#define ossl_sk_X509_OBJECT_new(cmp) ((ossl_STACK_OF(ossl_X509_OBJECT) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_OBJECT_compfunc_type(cmp)))
#define ossl_sk_X509_OBJECT_new_null() ((ossl_STACK_OF(ossl_X509_OBJECT) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_OBJECT_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_OBJECT) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_OBJECT_compfunc_type(cmp), (n)))
#define ossl_sk_X509_OBJECT_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_OBJECT_sk_type(sk), (n))
#define ossl_sk_X509_OBJECT_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_OBJECT_sk_type(sk))
#define ossl_sk_X509_OBJECT_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_OBJECT_sk_type(sk))
#define ossl_sk_X509_OBJECT_delete(sk, i) ((ossl_X509_OBJECT *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_OBJECT_sk_type(sk), (i)))
#define ossl_sk_X509_OBJECT_delete_ptr(sk, ptr) ((ossl_X509_OBJECT *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr)))
#define ossl_sk_X509_OBJECT_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr))
#define ossl_sk_X509_OBJECT_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr))
#define ossl_sk_X509_OBJECT_pop(sk) ((ossl_X509_OBJECT *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_OBJECT_sk_type(sk)))
#define ossl_sk_X509_OBJECT_shift(sk) ((ossl_X509_OBJECT *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_OBJECT_sk_type(sk)))
#define ossl_sk_X509_OBJECT_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_OBJECT_sk_type(sk),ossl_ossl_check_X509_OBJECT_freefunc_type(freefunc))
#define ossl_sk_X509_OBJECT_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr), (idx))
#define ossl_sk_X509_OBJECT_set(sk, idx, ptr) ((ossl_X509_OBJECT *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_OBJECT_sk_type(sk), (idx), ossl_ossl_check_X509_OBJECT_type(ptr)))
#define ossl_sk_X509_OBJECT_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr))
#define ossl_sk_X509_OBJECT_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr))
#define ossl_sk_X509_OBJECT_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_type(ptr), pnum)
#define ossl_sk_X509_OBJECT_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_OBJECT_sk_type(sk))
#define ossl_sk_X509_OBJECT_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_OBJECT_sk_type(sk))
#define ossl_sk_X509_OBJECT_dup(sk) ((ossl_STACK_OF(ossl_X509_OBJECT) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_OBJECT_sk_type(sk)))
#define ossl_sk_X509_OBJECT_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_OBJECT) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_copyfunc_type(copyfunc), ossl_ossl_check_X509_OBJECT_freefunc_type(freefunc)))
#define ossl_sk_X509_OBJECT_set_cmp_func(sk, cmp) ((ossl_sk_X509_OBJECT_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_OBJECT_sk_type(sk), ossl_ossl_check_X509_OBJECT_compfunc_type(cmp)))
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_VERIFY_PARAM, ossl_X509_VERIFY_PARAM, ossl_X509_VERIFY_PARAM)
#define ossl_sk_X509_VERIFY_PARAM_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_VERIFY_PARAM_sk_type(sk))
#define ossl_sk_X509_VERIFY_PARAM_value(sk, idx) ((ossl_X509_VERIFY_PARAM *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_VERIFY_PARAM_sk_type(sk), (idx)))
#define ossl_sk_X509_VERIFY_PARAM_new(cmp) ((ossl_STACK_OF(ossl_X509_VERIFY_PARAM) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_VERIFY_PARAM_compfunc_type(cmp)))
#define ossl_sk_X509_VERIFY_PARAM_new_null() ((ossl_STACK_OF(ossl_X509_VERIFY_PARAM) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_VERIFY_PARAM_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_VERIFY_PARAM) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_VERIFY_PARAM_compfunc_type(cmp), (n)))
#define ossl_sk_X509_VERIFY_PARAM_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), (n))
#define ossl_sk_X509_VERIFY_PARAM_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk))
#define ossl_sk_X509_VERIFY_PARAM_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk))
#define ossl_sk_X509_VERIFY_PARAM_delete(sk, i) ((ossl_X509_VERIFY_PARAM *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), (i)))
#define ossl_sk_X509_VERIFY_PARAM_delete_ptr(sk, ptr) ((ossl_X509_VERIFY_PARAM *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr)))
#define ossl_sk_X509_VERIFY_PARAM_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr))
#define ossl_sk_X509_VERIFY_PARAM_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr))
#define ossl_sk_X509_VERIFY_PARAM_pop(sk) ((ossl_X509_VERIFY_PARAM *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk)))
#define ossl_sk_X509_VERIFY_PARAM_shift(sk) ((ossl_X509_VERIFY_PARAM *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk)))
#define ossl_sk_X509_VERIFY_PARAM_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk),ossl_ossl_check_X509_VERIFY_PARAM_freefunc_type(freefunc))
#define ossl_sk_X509_VERIFY_PARAM_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr), (idx))
#define ossl_sk_X509_VERIFY_PARAM_set(sk, idx, ptr) ((ossl_X509_VERIFY_PARAM *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), (idx), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr)))
#define ossl_sk_X509_VERIFY_PARAM_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr))
#define ossl_sk_X509_VERIFY_PARAM_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr))
#define ossl_sk_X509_VERIFY_PARAM_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_type(ptr), pnum)
#define ossl_sk_X509_VERIFY_PARAM_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk))
#define ossl_sk_X509_VERIFY_PARAM_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_VERIFY_PARAM_sk_type(sk))
#define ossl_sk_X509_VERIFY_PARAM_dup(sk) ((ossl_STACK_OF(ossl_X509_VERIFY_PARAM) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_VERIFY_PARAM_sk_type(sk)))
#define ossl_sk_X509_VERIFY_PARAM_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_VERIFY_PARAM) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_copyfunc_type(copyfunc), ossl_ossl_check_X509_VERIFY_PARAM_freefunc_type(freefunc)))
#define ossl_sk_X509_VERIFY_PARAM_set_cmp_func(sk, cmp) ((ossl_sk_X509_VERIFY_PARAM_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_VERIFY_PARAM_sk_type(sk), ossl_ossl_check_X509_VERIFY_PARAM_compfunc_type(cmp)))


/* This is used for a table of trust checking functions */
typedef struct ossl_x509_trust_st {
    int trust;
    int flags;
    int (*check_trust) (struct ossl_x509_trust_st *, ossl_X509 *, int);
    char *name;
    int arg1;
    void *arg2;
} ossl_X509_TRUST;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_X509_TRUST, ossl_X509_TRUST, ossl_X509_TRUST)
#define ossl_sk_X509_TRUST_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_X509_TRUST_sk_type(sk))
#define ossl_sk_X509_TRUST_value(sk, idx) ((ossl_X509_TRUST *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_X509_TRUST_sk_type(sk), (idx)))
#define ossl_sk_X509_TRUST_new(cmp) ((ossl_STACK_OF(ossl_X509_TRUST) *)ossl_OPENSSL_sk_new(ossl_ossl_check_X509_TRUST_compfunc_type(cmp)))
#define ossl_sk_X509_TRUST_new_null() ((ossl_STACK_OF(ossl_X509_TRUST) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_X509_TRUST_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_X509_TRUST) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_X509_TRUST_compfunc_type(cmp), (n)))
#define ossl_sk_X509_TRUST_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_X509_TRUST_sk_type(sk), (n))
#define ossl_sk_X509_TRUST_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_X509_TRUST_sk_type(sk))
#define ossl_sk_X509_TRUST_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_X509_TRUST_sk_type(sk))
#define ossl_sk_X509_TRUST_delete(sk, i) ((ossl_X509_TRUST *)ossl_OPENSSL_sk_delete(ossl_ossl_check_X509_TRUST_sk_type(sk), (i)))
#define ossl_sk_X509_TRUST_delete_ptr(sk, ptr) ((ossl_X509_TRUST *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr)))
#define ossl_sk_X509_TRUST_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr))
#define ossl_sk_X509_TRUST_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr))
#define ossl_sk_X509_TRUST_pop(sk) ((ossl_X509_TRUST *)ossl_OPENSSL_sk_pop(ossl_ossl_check_X509_TRUST_sk_type(sk)))
#define ossl_sk_X509_TRUST_shift(sk) ((ossl_X509_TRUST *)ossl_OPENSSL_sk_shift(ossl_ossl_check_X509_TRUST_sk_type(sk)))
#define ossl_sk_X509_TRUST_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_X509_TRUST_sk_type(sk),ossl_ossl_check_X509_TRUST_freefunc_type(freefunc))
#define ossl_sk_X509_TRUST_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr), (idx))
#define ossl_sk_X509_TRUST_set(sk, idx, ptr) ((ossl_X509_TRUST *)ossl_OPENSSL_sk_set(ossl_ossl_check_X509_TRUST_sk_type(sk), (idx), ossl_ossl_check_X509_TRUST_type(ptr)))
#define ossl_sk_X509_TRUST_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr))
#define ossl_sk_X509_TRUST_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr))
#define ossl_sk_X509_TRUST_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_type(ptr), pnum)
#define ossl_sk_X509_TRUST_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_X509_TRUST_sk_type(sk))
#define ossl_sk_X509_TRUST_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_X509_TRUST_sk_type(sk))
#define ossl_sk_X509_TRUST_dup(sk) ((ossl_STACK_OF(ossl_X509_TRUST) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_X509_TRUST_sk_type(sk)))
#define ossl_sk_X509_TRUST_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_X509_TRUST) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_copyfunc_type(copyfunc), ossl_ossl_check_X509_TRUST_freefunc_type(freefunc)))
#define ossl_sk_X509_TRUST_set_cmp_func(sk, cmp) ((ossl_sk_X509_TRUST_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_X509_TRUST_sk_type(sk), ossl_ossl_check_X509_TRUST_compfunc_type(cmp)))


/* standard trust ids */
# define ossl_X509_TRUST_DEFAULT      0 /* Only valid in purpose settings */
# define ossl_X509_TRUST_COMPAT       1
# define ossl_X509_TRUST_SSL_CLIENT   2
# define ossl_X509_TRUST_SSL_SERVER   3
# define ossl_X509_TRUST_EMAIL        4
# define ossl_X509_TRUST_OBJECT_SIGN  5
# define ossl_X509_TRUST_OCSP_SIGN    6
# define ossl_X509_TRUST_OCSP_REQUEST 7
# define ossl_X509_TRUST_TSA          8
/* Keep these up to date! */
# define ossl_X509_TRUST_MIN          1
# define ossl_X509_TRUST_MAX          8

/* trust_flags values */
# define ossl_X509_TRUST_DYNAMIC      (1U << 0)
# define ossl_X509_TRUST_DYNAMIC_NAME (1U << 1)
/* No compat trust if self-signed, preempts "DO_SS" */
# define ossl_X509_TRUST_NO_SS_COMPAT (1U << 2)
/* Compat trust if no explicit accepted trust EKUs */
# define ossl_X509_TRUST_DO_SS_COMPAT (1U << 3)
/* Accept "anyEKU" as a wildcard rejection OID and as a wildcard trust OID */
# define ossl_X509_TRUST_OK_ANY_EKU   (1U << 4)

/* check_trust return codes */
# define ossl_X509_TRUST_TRUSTED      1
# define ossl_X509_TRUST_REJECTED     2
# define ossl_X509_TRUST_UNTRUSTED    3

int ossl_X509_TRUST_set(int *t, int trust);
int ossl_X509_TRUST_get_count(void);
ossl_X509_TRUST *ossl_X509_TRUST_get0(int idx);
int ossl_X509_TRUST_get_by_id(int id);
int ossl_X509_TRUST_add(int id, int flags, int (*ck) (ossl_X509_TRUST *, ossl_X509 *, int),
                   const char *name, int arg1, void *arg2);
void ossl_X509_TRUST_cleanup(void);
int ossl_X509_TRUST_get_flags(const ossl_X509_TRUST *xp);
char *ossl_X509_TRUST_get0_name(const ossl_X509_TRUST *xp);
int ossl_X509_TRUST_get_trust(const ossl_X509_TRUST *xp);

int ossl_X509_trusted(const ossl_X509 *x);
int ossl_X509_add1_trust_object(ossl_X509 *x, const ossl_ASN1_OBJECT *obj);
int ossl_X509_add1_reject_object(ossl_X509 *x, const ossl_ASN1_OBJECT *obj);
void ossl_X509_trust_clear(ossl_X509 *x);
void ossl_X509_reject_clear(ossl_X509 *x);
ossl_STACK_OF(ossl_ASN1_OBJECT) *ossl_X509_get0_trust_objects(ossl_X509 *x);
ossl_STACK_OF(ossl_ASN1_OBJECT) *ossl_X509_get0_reject_objects(ossl_X509 *x);

int (*ossl_X509_TRUST_set_default(int (*trust) (int, ossl_X509 *, int))) (int, ossl_X509 *,
                                                                int);
int ossl_X509_check_trust(ossl_X509 *x, int id, int flags);

int ossl_X509_verify_cert(ossl_X509_STORE_CTX *ctx);
int ossl_X509_STORE_CTX_verify(ossl_X509_STORE_CTX *ctx);
ossl_STACK_OF(ossl_X509) *ossl_X509_build_chain(ossl_X509 *target, ossl_STACK_OF(ossl_X509) *certs,
                                 ossl_X509_STORE *store, int with_self_signed,
                                 ossl_OSSL_LIB_CTX *libctx, const char *propq);

int ossl_X509_STORE_set_depth(ossl_X509_STORE *store, int depth);

typedef int (*ossl_X509_STORE_CTX_verify_cb)(int, ossl_X509_STORE_CTX *);
int ossl_X509_STORE_CTX_print_verify_cb(int ok, ossl_X509_STORE_CTX *ctx);
typedef int (*ossl_X509_STORE_CTX_verify_fn)(ossl_X509_STORE_CTX *);
typedef int (*ossl_X509_STORE_CTX_get_issuer_fn)(ossl_X509 **issuer,
                                            ossl_X509_STORE_CTX *ctx, ossl_X509 *x);
typedef int (*ossl_X509_STORE_CTX_check_issued_fn)(ossl_X509_STORE_CTX *ctx,
                                              ossl_X509 *x, ossl_X509 *issuer);
typedef int (*ossl_X509_STORE_CTX_check_revocation_fn)(ossl_X509_STORE_CTX *ctx);
typedef int (*ossl_X509_STORE_CTX_get_crl_fn)(ossl_X509_STORE_CTX *ctx,
                                         ossl_X509_CRL **crl, ossl_X509 *x);
typedef int (*ossl_X509_STORE_CTX_check_crl_fn)(ossl_X509_STORE_CTX *ctx, ossl_X509_CRL *crl);
typedef int (*ossl_X509_STORE_CTX_cert_crl_fn)(ossl_X509_STORE_CTX *ctx,
                                          ossl_X509_CRL *crl, ossl_X509 *x);
typedef int (*ossl_X509_STORE_CTX_check_policy_fn)(ossl_X509_STORE_CTX *ctx);
typedef ossl_STACK_OF(ossl_X509)
    *(*ossl_X509_STORE_CTX_lookup_certs_fn)(ossl_X509_STORE_CTX *ctx,
                                       const ossl_X509_NAME *nm);
typedef ossl_STACK_OF(ossl_X509_CRL)
    *(*ossl_X509_STORE_CTX_lookup_crls_fn)(const ossl_X509_STORE_CTX *ctx,
                                      const ossl_X509_NAME *nm);
typedef int (*ossl_X509_STORE_CTX_cleanup_fn)(ossl_X509_STORE_CTX *ctx);

void ossl_X509_STORE_CTX_set_depth(ossl_X509_STORE_CTX *ctx, int depth);

# define ossl_X509_STORE_CTX_set_app_data(ctx,data) \
        ossl_X509_STORE_CTX_set_ex_data(ctx,0,data)
# define ossl_X509_STORE_CTX_get_app_data(ctx) \
        ossl_X509_STORE_CTX_get_ex_data(ctx,0)

# define ossl_X509_L_FILE_LOAD        1
# define ossl_X509_L_ADD_DIR          2
# define ossl_X509_L_ADD_STORE        3
# define ossl_X509_L_LOAD_STORE       4

# define ossl_X509_LOOKUP_load_file(x,name,type) \
                ossl_X509_LOOKUP_ctrl((x),ossl_X509_L_FILE_LOAD,(name),(long)(type),NULL)

# define ossl_X509_LOOKUP_add_dir(x,name,type) \
                ossl_X509_LOOKUP_ctrl((x),ossl_X509_L_ADD_DIR,(name),(long)(type),NULL)

# define ossl_X509_LOOKUP_add_store(x,name) \
                ossl_X509_LOOKUP_ctrl((x),ossl_X509_L_ADD_STORE,(name),0,NULL)

# define ossl_X509_LOOKUP_load_store(x,name) \
                ossl_X509_LOOKUP_ctrl((x),ossl_X509_L_LOAD_STORE,(name),0,NULL)

# define ossl_X509_LOOKUP_load_file_ex(x, name, type, libctx, propq)       \
ossl_X509_LOOKUP_ctrl_ex((x), ossl_X509_L_FILE_LOAD, (name), (long)(type), NULL,\
                    (libctx), (propq))

# define ossl_X509_LOOKUP_load_store_ex(x, name, libctx, propq)            \
ossl_X509_LOOKUP_ctrl_ex((x), ossl_X509_L_LOAD_STORE, (name), 0, NULL,          \
                    (libctx), (propq))

# define ossl_X509_LOOKUP_add_store_ex(x, name, libctx, propq)             \
ossl_X509_LOOKUP_ctrl_ex((x), ossl_X509_L_ADD_STORE, (name), 0, NULL,           \
                    (libctx), (propq))

# define ossl_X509_V_OK                                       0
# define ossl_X509_V_ERR_UNSPECIFIED                          1
# define ossl_X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT            2
# define ossl_X509_V_ERR_UNABLE_TO_GET_CRL                    3
# define ossl_X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE     4
# define ossl_X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE      5
# define ossl_X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY   6
# define ossl_X509_V_ERR_CERT_SIGNATURE_FAILURE               7
# define ossl_X509_V_ERR_CRL_SIGNATURE_FAILURE                8
# define ossl_X509_V_ERR_CERT_NOT_YET_VALID                   9
# define ossl_X509_V_ERR_CERT_HAS_EXPIRED                     10
# define ossl_X509_V_ERR_CRL_NOT_YET_VALID                    11
# define ossl_X509_V_ERR_CRL_HAS_EXPIRED                      12
# define ossl_X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD       13
# define ossl_X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD        14
# define ossl_X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD       15
# define ossl_X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD       16
# define ossl_X509_V_ERR_OUT_OF_MEM                           17
# define ossl_X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT          18
# define ossl_X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN            19
# define ossl_X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY    20
# define ossl_X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE      21
# define ossl_X509_V_ERR_CERT_CHAIN_TOO_LONG                  22
# define ossl_X509_V_ERR_CERT_REVOKED                         23
# define ossl_X509_V_ERR_NO_ISSUER_PUBLIC_KEY                 24
# define ossl_X509_V_ERR_PATH_LENGTH_EXCEEDED                 25
# define ossl_X509_V_ERR_INVALID_PURPOSE                      26
# define ossl_X509_V_ERR_CERT_UNTRUSTED                       27
# define ossl_X509_V_ERR_CERT_REJECTED                        28

/* These are 'informational' when looking for issuer cert */
# define ossl_X509_V_ERR_SUBJECT_ISSUER_MISMATCH              29
# define ossl_X509_V_ERR_AKID_SKID_MISMATCH                   30
# define ossl_X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH          31
# define ossl_X509_V_ERR_KEYUSAGE_NO_CERTSIGN                 32
# define ossl_X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER             33
# define ossl_X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION         34
# define ossl_X509_V_ERR_KEYUSAGE_NO_CRL_SIGN                 35
# define ossl_X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION     36
# define ossl_X509_V_ERR_INVALID_NON_CA                       37
# define ossl_X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED           38
# define ossl_X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE        39
# define ossl_X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED       40
# define ossl_X509_V_ERR_INVALID_EXTENSION                    41
# define ossl_X509_V_ERR_INVALID_POLICY_EXTENSION             42
# define ossl_X509_V_ERR_NO_EXPLICIT_POLICY                   43
# define ossl_X509_V_ERR_DIFFERENT_CRL_SCOPE                  44
# define ossl_X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE        45
# define ossl_X509_V_ERR_UNNESTED_RESOURCE                    46
# define ossl_X509_V_ERR_PERMITTED_VIOLATION                  47
# define ossl_X509_V_ERR_EXCLUDED_VIOLATION                   48
# define ossl_X509_V_ERR_SUBTREE_MINMAX                       49
/* The application is not happy */
# define ossl_X509_V_ERR_APPLICATION_VERIFICATION             50
# define ossl_X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE          51
# define ossl_X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX        52
# define ossl_X509_V_ERR_UNSUPPORTED_NAME_SYNTAX              53
# define ossl_X509_V_ERR_CRL_PATH_VALIDATION_ERROR            54
/* Another issuer check debug option */
# define ossl_X509_V_ERR_PATH_LOOP                            55
/* Suite B mode algorithm violation */
# define ossl_X509_V_ERR_SUITE_B_INVALID_VERSION              56
# define ossl_X509_V_ERR_SUITE_B_INVALID_ALGORITHM            57
# define ossl_X509_V_ERR_SUITE_B_INVALID_CURVE                58
# define ossl_X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM  59
# define ossl_X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED              60
# define ossl_X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256 61
/* Host, email and IP check errors */
# define ossl_X509_V_ERR_HOSTNAME_MISMATCH                    62
# define ossl_X509_V_ERR_EMAIL_MISMATCH                       63
# define ossl_X509_V_ERR_IP_ADDRESS_MISMATCH                  64
/* DANE TLSA errors */
# define ossl_X509_V_ERR_DANE_NO_MATCH                        65
/* security level errors */
# define ossl_X509_V_ERR_EE_KEY_TOO_SMALL                     66
# define ossl_X509_V_ERR_CA_KEY_TOO_SMALL                     67
# define ossl_X509_V_ERR_CA_MD_TOO_WEAK                       68
/* Caller error */
# define ossl_X509_V_ERR_INVALID_CALL                         69
/* Issuer lookup error */
# define ossl_X509_V_ERR_STORE_LOOKUP                         70
/* Certificate transparency */
# define ossl_X509_V_ERR_NO_VALID_SCTS                        71

# define ossl_X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION         72
/* OCSP status errors */
# define ossl_X509_V_ERR_OCSP_VERIFY_NEEDED                   73  /* Need OCSP verification */
# define ossl_X509_V_ERR_OCSP_VERIFY_FAILED                   74  /* Couldn't verify cert through OCSP */
# define ossl_X509_V_ERR_OCSP_CERT_UNKNOWN                    75  /* Certificate wasn't recognized by the OCSP responder */

# define ossl_X509_V_ERR_UNSUPPORTED_SIGNATURE_ALGORITHM      76
# define ossl_X509_V_ERR_SIGNATURE_ALGORITHM_MISMATCH         77

/* Errors in case a check in ossl_X509_V_FLAG_X509_STRICT mode fails */
# define ossl_X509_V_ERR_SIGNATURE_ALGORITHM_INCONSISTENCY    78
# define ossl_X509_V_ERR_INVALID_CA                           79
# define ossl_X509_V_ERR_PATHLEN_INVALID_FOR_NON_CA           80
# define ossl_X509_V_ERR_PATHLEN_WITHOUT_KU_KEY_CERT_SIGN     81
# define ossl_X509_V_ERR_KU_KEY_CERT_SIGN_INVALID_FOR_NON_CA  82
# define ossl_X509_V_ERR_ISSUER_NAME_EMPTY                    83
# define ossl_X509_V_ERR_SUBJECT_NAME_EMPTY                   84
# define ossl_X509_V_ERR_MISSING_AUTHORITY_KEY_IDENTIFIER     85
# define ossl_X509_V_ERR_MISSING_SUBJECT_KEY_IDENTIFIER       86
# define ossl_X509_V_ERR_EMPTY_SUBJECT_ALT_NAME               87
# define ossl_X509_V_ERR_EMPTY_SUBJECT_SAN_NOT_CRITICAL       88
# define ossl_X509_V_ERR_CA_BCONS_NOT_CRITICAL                89
# define ossl_X509_V_ERR_AUTHORITY_KEY_IDENTIFIER_CRITICAL    90
# define ossl_X509_V_ERR_SUBJECT_KEY_IDENTIFIER_CRITICAL      91
# define ossl_X509_V_ERR_CA_CERT_MISSING_KEY_USAGE            92
# define ossl_X509_V_ERR_EXTENSIONS_REQUIRE_VERSION_3         93
# define ossl_X509_V_ERR_EC_KEY_EXPLICIT_PARAMS               94

/* Certificate verify flags */
# ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
#  define ossl_X509_V_FLAG_CB_ISSUER_CHECK             0x0   /* Deprecated */
# endif
/* Use check time instead of current time */
# define ossl_X509_V_FLAG_USE_CHECK_TIME              0x2
/* Lookup CRLs */
# define ossl_X509_V_FLAG_CRL_CHECK                   0x4
/* Lookup CRLs for whole chain */
# define ossl_X509_V_FLAG_CRL_CHECK_ALL               0x8
/* Ignore unhandled critical extensions */
# define ossl_X509_V_FLAG_IGNORE_CRITICAL             0x10
/* Disable workarounds for broken certificates */
# define ossl_X509_V_FLAG_X509_STRICT                 0x20
/* Enable proxy certificate validation */
# define ossl_X509_V_FLAG_ALLOW_PROXY_CERTS           0x40
/* Enable policy checking */
# define ossl_X509_V_FLAG_POLICY_CHECK                0x80
/* Policy variable require-explicit-policy */
# define ossl_X509_V_FLAG_EXPLICIT_POLICY             0x100
/* Policy variable inhibit-any-policy */
# define ossl_X509_V_FLAG_INHIBIT_ANY                 0x200
/* Policy variable inhibit-policy-mapping */
# define ossl_X509_V_FLAG_INHIBIT_MAP                 0x400
/* Notify callback that policy is OK */
# define ossl_X509_V_FLAG_NOTIFY_POLICY               0x800
/* Extended CRL features such as indirect CRLs, alternate CRL signing keys */
# define ossl_X509_V_FLAG_EXTENDED_CRL_SUPPORT        0x1000
/* Delta CRL support */
# define ossl_X509_V_FLAG_USE_DELTAS                  0x2000
/* Check self-signed CA signature */
# define ossl_X509_V_FLAG_CHECK_SS_SIGNATURE          0x4000
/* Use trusted store first */
# define ossl_X509_V_FLAG_TRUSTED_FIRST               0x8000
/* Suite B 128 bit only mode: not normally used */
# define ossl_X509_V_FLAG_SUITEB_128_LOS_ONLY         0x10000
/* Suite B 192 bit only mode */
# define ossl_X509_V_FLAG_SUITEB_192_LOS              0x20000
/* Suite B 128 bit mode allowing 192 bit algorithms */
# define ossl_X509_V_FLAG_SUITEB_128_LOS              0x30000
/* Allow partial chains if at least one certificate is in trusted store */
# define ossl_X509_V_FLAG_PARTIAL_CHAIN               0x80000
/*
 * If the initial chain is not trusted, do not attempt to build an alternative
 * chain. Alternate chain checking was introduced in 1.1.0. Setting this flag
 * will force the behaviour to match that of previous versions.
 */
# define ossl_X509_V_FLAG_NO_ALT_CHAINS               0x100000
/* Do not check certificate/CRL validity against current time */
# define ossl_X509_V_FLAG_NO_CHECK_TIME               0x200000

# define ossl_X509_VP_FLAG_DEFAULT                    0x1
# define ossl_X509_VP_FLAG_OVERWRITE                  0x2
# define ossl_X509_VP_FLAG_RESET_FLAGS                0x4
# define ossl_X509_VP_FLAG_LOCKED                     0x8
# define ossl_X509_VP_FLAG_ONCE                       0x10

/* Internal use: mask of policy related options */
# define ossl_X509_V_FLAG_POLICY_MASK (ossl_X509_V_FLAG_POLICY_CHECK \
                                | ossl_X509_V_FLAG_EXPLICIT_POLICY \
                                | ossl_X509_V_FLAG_INHIBIT_ANY \
                                | ossl_X509_V_FLAG_INHIBIT_MAP)

int ossl_X509_OBJECT_idx_by_subject(ossl_STACK_OF(ossl_X509_OBJECT) *h, ossl_X509_LOOKUP_TYPE type,
                               const ossl_X509_NAME *name);
ossl_X509_OBJECT *ossl_X509_OBJECT_retrieve_by_subject(ossl_STACK_OF(ossl_X509_OBJECT) *h,
                                             ossl_X509_LOOKUP_TYPE type,
                                             const ossl_X509_NAME *name);
ossl_X509_OBJECT *ossl_X509_OBJECT_retrieve_match(ossl_STACK_OF(ossl_X509_OBJECT) *h,
                                        ossl_X509_OBJECT *x);
int ossl_X509_OBJECT_up_ref_count(ossl_X509_OBJECT *a);
ossl_X509_OBJECT *ossl_X509_OBJECT_new(void);
void ossl_X509_OBJECT_free(ossl_X509_OBJECT *a);
ossl_X509_LOOKUP_TYPE ossl_X509_OBJECT_get_type(const ossl_X509_OBJECT *a);
ossl_X509 *ossl_X509_OBJECT_get0_X509(const ossl_X509_OBJECT *a);
int ossl_X509_OBJECT_set1_X509(ossl_X509_OBJECT *a, ossl_X509 *obj);
ossl_X509_CRL *ossl_X509_OBJECT_get0_X509_CRL(const ossl_X509_OBJECT *a);
int ossl_X509_OBJECT_set1_X509_CRL(ossl_X509_OBJECT *a, ossl_X509_CRL *obj);
ossl_X509_STORE *ossl_X509_STORE_new(void);
void ossl_X509_STORE_free(ossl_X509_STORE *v);
int ossl_X509_STORE_lock(ossl_X509_STORE *ctx);
int ossl_X509_STORE_unlock(ossl_X509_STORE *ctx);
int ossl_X509_STORE_up_ref(ossl_X509_STORE *v);
ossl_STACK_OF(ossl_X509_OBJECT) *ossl_X509_STORE_get0_objects(const ossl_X509_STORE *v);
ossl_STACK_OF(ossl_X509) *ossl_X509_STORE_get1_all_certs(ossl_X509_STORE *st);
ossl_STACK_OF(ossl_X509) *ossl_X509_STORE_CTX_get1_certs(ossl_X509_STORE_CTX *st,
                                          const ossl_X509_NAME *nm);
ossl_STACK_OF(ossl_X509_CRL) *ossl_X509_STORE_CTX_get1_crls(const ossl_X509_STORE_CTX *st,
                                             const ossl_X509_NAME *nm);
int ossl_X509_STORE_set_flags(ossl_X509_STORE *ctx, unsigned long flags);
int ossl_X509_STORE_set_purpose(ossl_X509_STORE *ctx, int purpose);
int ossl_X509_STORE_set_trust(ossl_X509_STORE *ctx, int trust);
int ossl_X509_STORE_set1_param(ossl_X509_STORE *ctx, const ossl_X509_VERIFY_PARAM *pm);
ossl_X509_VERIFY_PARAM *ossl_X509_STORE_get0_param(const ossl_X509_STORE *ctx);

void ossl_X509_STORE_set_verify(ossl_X509_STORE *ctx, ossl_X509_STORE_CTX_verify_fn verify);
#define ossl_X509_STORE_set_verify_func(ctx, func) \
            ossl_X509_STORE_set_verify((ctx),(func))
void ossl_X509_STORE_CTX_set_verify(ossl_X509_STORE_CTX *ctx,
                               ossl_X509_STORE_CTX_verify_fn verify);
ossl_X509_STORE_CTX_verify_fn ossl_X509_STORE_get_verify(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_verify_cb(ossl_X509_STORE *ctx,
                              ossl_X509_STORE_CTX_verify_cb verify_cb);
# define ossl_X509_STORE_set_verify_cb_func(ctx,func) \
            ossl_X509_STORE_set_verify_cb((ctx),(func))
ossl_X509_STORE_CTX_verify_cb ossl_X509_STORE_get_verify_cb(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_get_issuer(ossl_X509_STORE *ctx,
                               ossl_X509_STORE_CTX_get_issuer_fn get_issuer);
ossl_X509_STORE_CTX_get_issuer_fn ossl_X509_STORE_get_get_issuer(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_check_issued(ossl_X509_STORE *ctx,
                                 ossl_X509_STORE_CTX_check_issued_fn check_issued);
ossl_X509_STORE_CTX_check_issued_fn ossl_X509_STORE_get_check_issued(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_check_revocation(ossl_X509_STORE *ctx,
                                     ossl_X509_STORE_CTX_check_revocation_fn check_revocation);
ossl_X509_STORE_CTX_check_revocation_fn
    ossl_X509_STORE_get_check_revocation(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_get_crl(ossl_X509_STORE *ctx,
                            ossl_X509_STORE_CTX_get_crl_fn get_crl);
ossl_X509_STORE_CTX_get_crl_fn ossl_X509_STORE_get_get_crl(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_check_crl(ossl_X509_STORE *ctx,
                              ossl_X509_STORE_CTX_check_crl_fn check_crl);
ossl_X509_STORE_CTX_check_crl_fn ossl_X509_STORE_get_check_crl(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_cert_crl(ossl_X509_STORE *ctx,
                             ossl_X509_STORE_CTX_cert_crl_fn cert_crl);
ossl_X509_STORE_CTX_cert_crl_fn ossl_X509_STORE_get_cert_crl(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_check_policy(ossl_X509_STORE *ctx,
                                 ossl_X509_STORE_CTX_check_policy_fn check_policy);
ossl_X509_STORE_CTX_check_policy_fn ossl_X509_STORE_get_check_policy(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_lookup_certs(ossl_X509_STORE *ctx,
                                 ossl_X509_STORE_CTX_lookup_certs_fn lookup_certs);
ossl_X509_STORE_CTX_lookup_certs_fn ossl_X509_STORE_get_lookup_certs(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_lookup_crls(ossl_X509_STORE *ctx,
                                ossl_X509_STORE_CTX_lookup_crls_fn lookup_crls);
#define ossl_X509_STORE_set_lookup_crls_cb(ctx, func) \
    ossl_X509_STORE_set_lookup_crls((ctx), (func))
ossl_X509_STORE_CTX_lookup_crls_fn ossl_X509_STORE_get_lookup_crls(const ossl_X509_STORE *ctx);
void ossl_X509_STORE_set_cleanup(ossl_X509_STORE *ctx,
                            ossl_X509_STORE_CTX_cleanup_fn cleanup);
ossl_X509_STORE_CTX_cleanup_fn ossl_X509_STORE_get_cleanup(const ossl_X509_STORE *ctx);

#define ossl_X509_STORE_get_ex_new_index(l, p, newf, dupf, freef) \
    ossl_CRYPTO_get_ex_new_index(ossl_CRYPTO_EX_INDEX_X509_STORE, l, p, newf, dupf, freef)
int ossl_X509_STORE_set_ex_data(ossl_X509_STORE *ctx, int idx, void *data);
void *ossl_X509_STORE_get_ex_data(const ossl_X509_STORE *ctx, int idx);

ossl_X509_STORE_CTX *ossl_X509_STORE_CTX_new_ex(ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_X509_STORE_CTX *ossl_X509_STORE_CTX_new(void);

int ossl_X509_STORE_CTX_get1_issuer(ossl_X509 **issuer, ossl_X509_STORE_CTX *ctx, ossl_X509 *x);

void ossl_X509_STORE_CTX_free(ossl_X509_STORE_CTX *ctx);
int ossl_X509_STORE_CTX_init(ossl_X509_STORE_CTX *ctx, ossl_X509_STORE *trust_store,
                        ossl_X509 *target, ossl_STACK_OF(ossl_X509) *untrusted);
void ossl_X509_STORE_CTX_set0_trusted_stack(ossl_X509_STORE_CTX *ctx, ossl_STACK_OF(ossl_X509) *sk);
void ossl_X509_STORE_CTX_cleanup(ossl_X509_STORE_CTX *ctx);

ossl_X509_STORE *ossl_X509_STORE_CTX_get0_store(const ossl_X509_STORE_CTX *ctx);
ossl_X509 *ossl_X509_STORE_CTX_get0_cert(const ossl_X509_STORE_CTX *ctx);
ossl_STACK_OF(ossl_X509)* ossl_X509_STORE_CTX_get0_untrusted(const ossl_X509_STORE_CTX *ctx);
void ossl_X509_STORE_CTX_set0_untrusted(ossl_X509_STORE_CTX *ctx, ossl_STACK_OF(ossl_X509) *sk);
void ossl_X509_STORE_CTX_set_verify_cb(ossl_X509_STORE_CTX *ctx,
                                  ossl_X509_STORE_CTX_verify_cb verify);
ossl_X509_STORE_CTX_verify_cb ossl_X509_STORE_CTX_get_verify_cb(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_verify_fn ossl_X509_STORE_CTX_get_verify(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_get_issuer_fn ossl_X509_STORE_CTX_get_get_issuer(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_check_issued_fn ossl_X509_STORE_CTX_get_check_issued(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_check_revocation_fn ossl_X509_STORE_CTX_get_check_revocation(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_get_crl_fn ossl_X509_STORE_CTX_get_get_crl(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_check_crl_fn ossl_X509_STORE_CTX_get_check_crl(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_cert_crl_fn ossl_X509_STORE_CTX_get_cert_crl(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_check_policy_fn ossl_X509_STORE_CTX_get_check_policy(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_lookup_certs_fn ossl_X509_STORE_CTX_get_lookup_certs(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_lookup_crls_fn ossl_X509_STORE_CTX_get_lookup_crls(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX_cleanup_fn ossl_X509_STORE_CTX_get_cleanup(const ossl_X509_STORE_CTX *ctx);

#ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
# define ossl_X509_STORE_CTX_get_chain ossl_X509_STORE_CTX_get0_chain
# define ossl_X509_STORE_CTX_set_chain ossl_X509_STORE_CTX_set0_untrusted
# define ossl_X509_STORE_CTX_trusted_stack ossl_X509_STORE_CTX_set0_trusted_stack
# define ossl_X509_STORE_get_by_subject ossl_X509_STORE_CTX_get_by_subject
# define ossl_X509_STORE_get1_certs ossl_X509_STORE_CTX_get1_certs
# define ossl_X509_STORE_get1_crls ossl_X509_STORE_CTX_get1_crls
/* the following macro is misspelled; use ossl_X509_STORE_get1_certs instead */
# define ossl_X509_STORE_get1_cert ossl_X509_STORE_CTX_get1_certs
/* the following macro is misspelled; use ossl_X509_STORE_get1_crls instead */
# define ossl_X509_STORE_get1_crl ossl_X509_STORE_CTX_get1_crls
#endif

ossl_X509_LOOKUP *ossl_X509_STORE_add_lookup(ossl_X509_STORE *v, ossl_X509_LOOKUP_METHOD *m);
ossl_X509_LOOKUP_METHOD *ossl_X509_LOOKUP_hash_dir(void);
ossl_X509_LOOKUP_METHOD *ossl_X509_LOOKUP_file(void);
ossl_X509_LOOKUP_METHOD *ossl_X509_LOOKUP_store(void);

typedef int (*ossl_X509_LOOKUP_ctrl_fn)(ossl_X509_LOOKUP *ctx, int cmd, const char *argc,
                                   long argl, char **ret);
typedef int (*ossl_X509_LOOKUP_ctrl_ex_fn)(
    ossl_X509_LOOKUP *ctx, int cmd, const char *argc, long argl, char **ret,
    ossl_OSSL_LIB_CTX *libctx, const char *propq);

typedef int (*ossl_X509_LOOKUP_get_by_subject_fn)(ossl_X509_LOOKUP *ctx,
                                             ossl_X509_LOOKUP_TYPE type,
                                             const ossl_X509_NAME *name,
                                             ossl_X509_OBJECT *ret);
typedef int (*ossl_X509_LOOKUP_get_by_subject_ex_fn)(ossl_X509_LOOKUP *ctx,
                                                         ossl_X509_LOOKUP_TYPE type,
                                                         const ossl_X509_NAME *name,
                                                         ossl_X509_OBJECT *ret,
                                                         ossl_OSSL_LIB_CTX *libctx,
                                                         const char *propq);
typedef int (*ossl_X509_LOOKUP_get_by_issuer_serial_fn)(ossl_X509_LOOKUP *ctx,
                                                   ossl_X509_LOOKUP_TYPE type,
                                                   const ossl_X509_NAME *name,
                                                   const ossl_ASN1_INTEGER *serial,
                                                   ossl_X509_OBJECT *ret);
typedef int (*ossl_X509_LOOKUP_get_by_fingerprint_fn)(ossl_X509_LOOKUP *ctx,
                                                 ossl_X509_LOOKUP_TYPE type,
                                                 const unsigned char* bytes,
                                                 int len,
                                                 ossl_X509_OBJECT *ret);
typedef int (*ossl_X509_LOOKUP_get_by_alias_fn)(ossl_X509_LOOKUP *ctx,
                                           ossl_X509_LOOKUP_TYPE type,
                                           const char *str,
                                           int len,
                                           ossl_X509_OBJECT *ret);

ossl_X509_LOOKUP_METHOD *ossl_X509_LOOKUP_meth_new(const char *name);
void ossl_X509_LOOKUP_meth_free(ossl_X509_LOOKUP_METHOD *method);

int ossl_X509_LOOKUP_meth_set_new_item(ossl_X509_LOOKUP_METHOD *method,
                                  int (*new_item) (ossl_X509_LOOKUP *ctx));
int (*ossl_X509_LOOKUP_meth_get_new_item(const ossl_X509_LOOKUP_METHOD* method))
    (ossl_X509_LOOKUP *ctx);

int ossl_X509_LOOKUP_meth_set_free(ossl_X509_LOOKUP_METHOD *method,
                              void (*free_fn) (ossl_X509_LOOKUP *ctx));
void (*ossl_X509_LOOKUP_meth_get_free(const ossl_X509_LOOKUP_METHOD* method))
    (ossl_X509_LOOKUP *ctx);

int ossl_X509_LOOKUP_meth_set_init(ossl_X509_LOOKUP_METHOD *method,
                              int (*init) (ossl_X509_LOOKUP *ctx));
int (*ossl_X509_LOOKUP_meth_get_init(const ossl_X509_LOOKUP_METHOD* method))
    (ossl_X509_LOOKUP *ctx);

int ossl_X509_LOOKUP_meth_set_shutdown(ossl_X509_LOOKUP_METHOD *method,
                                  int (*shutdown) (ossl_X509_LOOKUP *ctx));
int (*ossl_X509_LOOKUP_meth_get_shutdown(const ossl_X509_LOOKUP_METHOD* method))
    (ossl_X509_LOOKUP *ctx);

int ossl_X509_LOOKUP_meth_set_ctrl(ossl_X509_LOOKUP_METHOD *method,
                              ossl_X509_LOOKUP_ctrl_fn ctrl_fn);
ossl_X509_LOOKUP_ctrl_fn ossl_X509_LOOKUP_meth_get_ctrl(const ossl_X509_LOOKUP_METHOD *method);

int ossl_X509_LOOKUP_meth_set_get_by_subject(ossl_X509_LOOKUP_METHOD *method,
                                        ossl_X509_LOOKUP_get_by_subject_fn fn);
ossl_X509_LOOKUP_get_by_subject_fn ossl_X509_LOOKUP_meth_get_get_by_subject(
    const ossl_X509_LOOKUP_METHOD *method);

int ossl_X509_LOOKUP_meth_set_get_by_issuer_serial(ossl_X509_LOOKUP_METHOD *method,
    ossl_X509_LOOKUP_get_by_issuer_serial_fn fn);
ossl_X509_LOOKUP_get_by_issuer_serial_fn ossl_X509_LOOKUP_meth_get_get_by_issuer_serial(
    const ossl_X509_LOOKUP_METHOD *method);

int ossl_X509_LOOKUP_meth_set_get_by_fingerprint(ossl_X509_LOOKUP_METHOD *method,
    ossl_X509_LOOKUP_get_by_fingerprint_fn fn);
ossl_X509_LOOKUP_get_by_fingerprint_fn ossl_X509_LOOKUP_meth_get_get_by_fingerprint(
    const ossl_X509_LOOKUP_METHOD *method);

int ossl_X509_LOOKUP_meth_set_get_by_alias(ossl_X509_LOOKUP_METHOD *method,
                                      ossl_X509_LOOKUP_get_by_alias_fn fn);
ossl_X509_LOOKUP_get_by_alias_fn ossl_X509_LOOKUP_meth_get_get_by_alias(
    const ossl_X509_LOOKUP_METHOD *method);


int ossl_X509_STORE_add_cert(ossl_X509_STORE *ctx, ossl_X509 *x);
int ossl_X509_STORE_add_crl(ossl_X509_STORE *ctx, ossl_X509_CRL *x);

int ossl_X509_STORE_CTX_get_by_subject(const ossl_X509_STORE_CTX *vs,
                                  ossl_X509_LOOKUP_TYPE type,
                                  const ossl_X509_NAME *name, ossl_X509_OBJECT *ret);
ossl_X509_OBJECT *ossl_X509_STORE_CTX_get_obj_by_subject(ossl_X509_STORE_CTX *vs,
                                               ossl_X509_LOOKUP_TYPE type,
                                               const ossl_X509_NAME *name);

int ossl_X509_LOOKUP_ctrl(ossl_X509_LOOKUP *ctx, int cmd, const char *argc,
                     long argl, char **ret);
int ossl_X509_LOOKUP_ctrl_ex(ossl_X509_LOOKUP *ctx, int cmd, const char *argc, long argl,
                        char **ret, ossl_OSSL_LIB_CTX *libctx, const char *propq);

int ossl_X509_load_cert_file(ossl_X509_LOOKUP *ctx, const char *file, int type);
int ossl_X509_load_cert_file_ex(ossl_X509_LOOKUP *ctx, const char *file, int type,
                           ossl_OSSL_LIB_CTX *libctx, const char *propq);
int ossl_X509_load_crl_file(ossl_X509_LOOKUP *ctx, const char *file, int type);
int ossl_X509_load_cert_crl_file(ossl_X509_LOOKUP *ctx, const char *file, int type);
int ossl_X509_load_cert_crl_file_ex(ossl_X509_LOOKUP *ctx, const char *file, int type,
                               ossl_OSSL_LIB_CTX *libctx, const char *propq);

ossl_X509_LOOKUP *ossl_X509_LOOKUP_new(ossl_X509_LOOKUP_METHOD *method);
void ossl_X509_LOOKUP_free(ossl_X509_LOOKUP *ctx);
int ossl_X509_LOOKUP_init(ossl_X509_LOOKUP *ctx);
int ossl_X509_LOOKUP_by_subject(ossl_X509_LOOKUP *ctx, ossl_X509_LOOKUP_TYPE type,
                           const ossl_X509_NAME *name, ossl_X509_OBJECT *ret);
int ossl_X509_LOOKUP_by_subject_ex(ossl_X509_LOOKUP *ctx, ossl_X509_LOOKUP_TYPE type,
                              const ossl_X509_NAME *name, ossl_X509_OBJECT *ret,
                              ossl_OSSL_LIB_CTX *libctx, const char *propq);
int ossl_X509_LOOKUP_by_issuer_serial(ossl_X509_LOOKUP *ctx, ossl_X509_LOOKUP_TYPE type,
                                 const ossl_X509_NAME *name,
                                 const ossl_ASN1_INTEGER *serial,
                                 ossl_X509_OBJECT *ret);
int ossl_X509_LOOKUP_by_fingerprint(ossl_X509_LOOKUP *ctx, ossl_X509_LOOKUP_TYPE type,
                               const unsigned char *bytes, int len,
                               ossl_X509_OBJECT *ret);
int ossl_X509_LOOKUP_by_alias(ossl_X509_LOOKUP *ctx, ossl_X509_LOOKUP_TYPE type,
                         const char *str, int len, ossl_X509_OBJECT *ret);
int ossl_X509_LOOKUP_set_method_data(ossl_X509_LOOKUP *ctx, void *data);
void *ossl_X509_LOOKUP_get_method_data(const ossl_X509_LOOKUP *ctx);
ossl_X509_STORE *ossl_X509_LOOKUP_get_store(const ossl_X509_LOOKUP *ctx);
int ossl_X509_LOOKUP_shutdown(ossl_X509_LOOKUP *ctx);

int ossl_X509_STORE_load_file(ossl_X509_STORE *ctx, const char *file);
int ossl_X509_STORE_load_path(ossl_X509_STORE *ctx, const char *path);
int ossl_X509_STORE_load_store(ossl_X509_STORE *ctx, const char *store);
int ossl_X509_STORE_load_locations(ossl_X509_STORE *ctx,
                                               const char *file,
                                               const char *dir);
int ossl_X509_STORE_set_default_paths(ossl_X509_STORE *ctx);

int ossl_X509_STORE_load_file_ex(ossl_X509_STORE *ctx, const char *file,
                            ossl_OSSL_LIB_CTX *libctx, const char *propq);
int ossl_X509_STORE_load_store_ex(ossl_X509_STORE *ctx, const char *store,
                             ossl_OSSL_LIB_CTX *libctx, const char *propq);
int ossl_X509_STORE_load_locations_ex(ossl_X509_STORE *ctx, const char *file,
                                 const char *dir, ossl_OSSL_LIB_CTX *libctx,
                                 const char *propq);
int ossl_X509_STORE_set_default_paths_ex(ossl_X509_STORE *ctx, ossl_OSSL_LIB_CTX *libctx,
                                    const char *propq);

#define ossl_X509_STORE_CTX_get_ex_new_index(l, p, newf, dupf, freef) \
    ossl_CRYPTO_get_ex_new_index(ossl_CRYPTO_EX_INDEX_X509_STORE_CTX, l, p, newf, dupf, freef)
int ossl_X509_STORE_CTX_set_ex_data(ossl_X509_STORE_CTX *ctx, int idx, void *data);
void *ossl_X509_STORE_CTX_get_ex_data(const ossl_X509_STORE_CTX *ctx, int idx);
int ossl_X509_STORE_CTX_get_error(const ossl_X509_STORE_CTX *ctx);
void ossl_X509_STORE_CTX_set_error(ossl_X509_STORE_CTX *ctx, int s);
int ossl_X509_STORE_CTX_get_error_depth(const ossl_X509_STORE_CTX *ctx);
void ossl_X509_STORE_CTX_set_error_depth(ossl_X509_STORE_CTX *ctx, int depth);
ossl_X509 *ossl_X509_STORE_CTX_get_current_cert(const ossl_X509_STORE_CTX *ctx);
void ossl_X509_STORE_CTX_set_current_cert(ossl_X509_STORE_CTX *ctx, ossl_X509 *x);
ossl_X509 *ossl_X509_STORE_CTX_get0_current_issuer(const ossl_X509_STORE_CTX *ctx);
ossl_X509_CRL *ossl_X509_STORE_CTX_get0_current_crl(const ossl_X509_STORE_CTX *ctx);
ossl_X509_STORE_CTX *ossl_X509_STORE_CTX_get0_parent_ctx(const ossl_X509_STORE_CTX *ctx);
ossl_STACK_OF(ossl_X509) *ossl_X509_STORE_CTX_get0_chain(const ossl_X509_STORE_CTX *ctx);
ossl_STACK_OF(ossl_X509) *ossl_X509_STORE_CTX_get1_chain(const ossl_X509_STORE_CTX *ctx);
void ossl_X509_STORE_CTX_set_cert(ossl_X509_STORE_CTX *ctx, ossl_X509 *target);
void ossl_X509_STORE_CTX_set0_verified_chain(ossl_X509_STORE_CTX *c, ossl_STACK_OF(ossl_X509) *sk);
void ossl_X509_STORE_CTX_set0_crls(ossl_X509_STORE_CTX *ctx, ossl_STACK_OF(ossl_X509_CRL) *sk);
int ossl_X509_STORE_CTX_set_purpose(ossl_X509_STORE_CTX *ctx, int purpose);
int ossl_X509_STORE_CTX_set_trust(ossl_X509_STORE_CTX *ctx, int trust);
int ossl_X509_STORE_CTX_purpose_inherit(ossl_X509_STORE_CTX *ctx, int def_purpose,
                                   int purpose, int trust);
void ossl_X509_STORE_CTX_set_flags(ossl_X509_STORE_CTX *ctx, unsigned long flags);
void ossl_X509_STORE_CTX_set_time(ossl_X509_STORE_CTX *ctx, unsigned long flags,
                             time_t t);

ossl_X509_POLICY_TREE *ossl_X509_STORE_CTX_get0_policy_tree(const ossl_X509_STORE_CTX *ctx);
int ossl_X509_STORE_CTX_get_explicit_policy(const ossl_X509_STORE_CTX *ctx);
int ossl_X509_STORE_CTX_get_num_untrusted(const ossl_X509_STORE_CTX *ctx);

ossl_X509_VERIFY_PARAM *ossl_X509_STORE_CTX_get0_param(const ossl_X509_STORE_CTX *ctx);
void ossl_X509_STORE_CTX_set0_param(ossl_X509_STORE_CTX *ctx, ossl_X509_VERIFY_PARAM *param);
int ossl_X509_STORE_CTX_set_default(ossl_X509_STORE_CTX *ctx, const char *name);

/*
 * Bridge opacity barrier between libcrypt and libssl, also needed to support
 * offline testing in test/danetest.c
 */
void ossl_X509_STORE_CTX_set0_dane(ossl_X509_STORE_CTX *ctx, ossl_SSL_DANE *dane);
#define ossl_DANE_FLAG_NO_DANE_EE_NAMECHECKS (1L << 0)

/* ossl_X509_VERIFY_PARAM functions */

ossl_X509_VERIFY_PARAM *ossl_X509_VERIFY_PARAM_new(void);
void ossl_X509_VERIFY_PARAM_free(ossl_X509_VERIFY_PARAM *param);
int ossl_X509_VERIFY_PARAM_inherit(ossl_X509_VERIFY_PARAM *to,
                              const ossl_X509_VERIFY_PARAM *from);
int ossl_X509_VERIFY_PARAM_set1(ossl_X509_VERIFY_PARAM *to,
                           const ossl_X509_VERIFY_PARAM *from);
int ossl_X509_VERIFY_PARAM_set1_name(ossl_X509_VERIFY_PARAM *param, const char *name);
int ossl_X509_VERIFY_PARAM_set_flags(ossl_X509_VERIFY_PARAM *param,
                                unsigned long flags);
int ossl_X509_VERIFY_PARAM_clear_flags(ossl_X509_VERIFY_PARAM *param,
                                  unsigned long flags);
unsigned long ossl_X509_VERIFY_PARAM_get_flags(const ossl_X509_VERIFY_PARAM *param);
int ossl_X509_VERIFY_PARAM_set_purpose(ossl_X509_VERIFY_PARAM *param, int purpose);
int ossl_X509_VERIFY_PARAM_set_trust(ossl_X509_VERIFY_PARAM *param, int trust);
void ossl_X509_VERIFY_PARAM_set_depth(ossl_X509_VERIFY_PARAM *param, int depth);
void ossl_X509_VERIFY_PARAM_set_auth_level(ossl_X509_VERIFY_PARAM *param, int auth_level);
time_t ossl_X509_VERIFY_PARAM_get_time(const ossl_X509_VERIFY_PARAM *param);
void ossl_X509_VERIFY_PARAM_set_time(ossl_X509_VERIFY_PARAM *param, time_t t);
int ossl_X509_VERIFY_PARAM_add0_policy(ossl_X509_VERIFY_PARAM *param,
                                  ossl_ASN1_OBJECT *policy);
int ossl_X509_VERIFY_PARAM_set1_policies(ossl_X509_VERIFY_PARAM *param,
                                    ossl_STACK_OF(ossl_ASN1_OBJECT) *policies);

int ossl_X509_VERIFY_PARAM_set_inh_flags(ossl_X509_VERIFY_PARAM *param,
                                    uint32_t flags);
uint32_t ossl_X509_VERIFY_PARAM_get_inh_flags(const ossl_X509_VERIFY_PARAM *param);

char *ossl_X509_VERIFY_PARAM_get0_host(ossl_X509_VERIFY_PARAM *param, int idx);
int ossl_X509_VERIFY_PARAM_set1_host(ossl_X509_VERIFY_PARAM *param,
                                const char *name, size_t namelen);
int ossl_X509_VERIFY_PARAM_add1_host(ossl_X509_VERIFY_PARAM *param,
                                const char *name, size_t namelen);
void ossl_X509_VERIFY_PARAM_set_hostflags(ossl_X509_VERIFY_PARAM *param,
                                     unsigned int flags);
unsigned int ossl_X509_VERIFY_PARAM_get_hostflags(const ossl_X509_VERIFY_PARAM *param);
char *ossl_X509_VERIFY_PARAM_get0_peername(const ossl_X509_VERIFY_PARAM *param);
void ossl_X509_VERIFY_PARAM_move_peername(ossl_X509_VERIFY_PARAM *, ossl_X509_VERIFY_PARAM *);
char *ossl_X509_VERIFY_PARAM_get0_email(ossl_X509_VERIFY_PARAM *param);
int ossl_X509_VERIFY_PARAM_set1_email(ossl_X509_VERIFY_PARAM *param,
                                 const char *email, size_t emaillen);
char *ossl_X509_VERIFY_PARAM_get1_ip_asc(ossl_X509_VERIFY_PARAM *param);
int ossl_X509_VERIFY_PARAM_set1_ip(ossl_X509_VERIFY_PARAM *param,
                              const unsigned char *ip, size_t iplen);
int ossl_X509_VERIFY_PARAM_set1_ip_asc(ossl_X509_VERIFY_PARAM *param,
                                  const char *ipasc);

int ossl_X509_VERIFY_PARAM_get_depth(const ossl_X509_VERIFY_PARAM *param);
int ossl_X509_VERIFY_PARAM_get_auth_level(const ossl_X509_VERIFY_PARAM *param);
const char *ossl_X509_VERIFY_PARAM_get0_name(const ossl_X509_VERIFY_PARAM *param);

int ossl_X509_VERIFY_PARAM_add0_table(ossl_X509_VERIFY_PARAM *param);
int ossl_X509_VERIFY_PARAM_get_count(void);
const ossl_X509_VERIFY_PARAM *ossl_X509_VERIFY_PARAM_get0(int id);
const ossl_X509_VERIFY_PARAM *ossl_X509_VERIFY_PARAM_lookup(const char *name);
void ossl_X509_VERIFY_PARAM_table_cleanup(void);

/* Non positive return values are errors */
#define ossl_X509_PCY_TREE_FAILURE  -2 /* Failure to satisfy explicit policy */
#define ossl_X509_PCY_TREE_INVALID  -1 /* Inconsistent or invalid extensions */
#define ossl_X509_PCY_TREE_INTERNAL  0 /* Internal error, most likely malloc */

/*
 * Positive return values form a bit mask, all but the first are internal to
 * the library and don't appear in results from ossl_X509_policy_check().
 */
#define ossl_X509_PCY_TREE_VALID     1 /* The policy tree is valid */
#define ossl_X509_PCY_TREE_EMPTY     2 /* The policy tree is empty */
#define ossl_X509_PCY_TREE_EXPLICIT  4 /* Explicit policy required */

int ossl_X509_policy_check(ossl_X509_POLICY_TREE **ptree, int *pexplicit_policy,
                      ossl_STACK_OF(ossl_X509) *certs,
                      ossl_STACK_OF(ossl_ASN1_OBJECT) *policy_oids, unsigned int flags);

void ossl_X509_policy_tree_free(ossl_X509_POLICY_TREE *tree);

int ossl_X509_policy_tree_level_count(const ossl_X509_POLICY_TREE *tree);
ossl_X509_POLICY_LEVEL *ossl_X509_policy_tree_get0_level(const ossl_X509_POLICY_TREE *tree,
                                               int i);

ossl_STACK_OF(ossl_X509_POLICY_NODE)
    *ossl_X509_policy_tree_get0_policies(const ossl_X509_POLICY_TREE *tree);

ossl_STACK_OF(ossl_X509_POLICY_NODE)
    *ossl_X509_policy_tree_get0_user_policies(const ossl_X509_POLICY_TREE *tree);

int ossl_X509_policy_level_node_count(ossl_X509_POLICY_LEVEL *level);

ossl_X509_POLICY_NODE *ossl_X509_policy_level_get0_node(const ossl_X509_POLICY_LEVEL *level,
                                              int i);

const ossl_ASN1_OBJECT *ossl_X509_policy_node_get0_policy(const ossl_X509_POLICY_NODE *node);

ossl_STACK_OF(ossl_POLICYQUALINFO)
    *ossl_X509_policy_node_get0_qualifiers(const ossl_X509_POLICY_NODE *node);
const ossl_X509_POLICY_NODE
    *ossl_X509_policy_node_get0_parent(const ossl_X509_POLICY_NODE *node);

#ifdef  __cplusplus
}
#endif
#endif
