/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_CMPERR_H
# define ossl_OPENSSL_CMPERR_H
# pragma once

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/cryptoerr_legacy.h"


# ifndef ossl_OPENSSL_NO_CMP


/*
 * CMP reason codes.
 */
#  define ossl_CMP_R_ALGORITHM_NOT_SUPPORTED                    139
#  define ossl_CMP_R_BAD_CHECKAFTER_IN_POLLREP                  167
#  define ossl_CMP_R_BAD_REQUEST_ID                             108
#  define ossl_CMP_R_CERTHASH_UNMATCHED                         156
#  define ossl_CMP_R_CERTID_NOT_FOUND                           109
#  define ossl_CMP_R_CERTIFICATE_NOT_ACCEPTED                   169
#  define ossl_CMP_R_CERTIFICATE_NOT_FOUND                      112
#  define ossl_CMP_R_CERTREQMSG_NOT_FOUND                       157
#  define ossl_CMP_R_CERTRESPONSE_NOT_FOUND                     113
#  define ossl_CMP_R_CERT_AND_KEY_DO_NOT_MATCH                  114
#  define ossl_CMP_R_CHECKAFTER_OUT_OF_RANGE                    181
#  define ossl_CMP_R_ENCOUNTERED_KEYUPDATEWARNING               176
#  define ossl_CMP_R_ENCOUNTERED_WAITING                        162
#  define ossl_CMP_R_ERROR_CALCULATING_PROTECTION               115
#  define ossl_CMP_R_ERROR_CREATING_CERTCONF                    116
#  define ossl_CMP_R_ERROR_CREATING_CERTREP                     117
#  define ossl_CMP_R_ERROR_CREATING_CERTREQ                     163
#  define ossl_CMP_R_ERROR_CREATING_ERROR                       118
#  define ossl_CMP_R_ERROR_CREATING_GENM                        119
#  define ossl_CMP_R_ERROR_CREATING_GENP                        120
#  define ossl_CMP_R_ERROR_CREATING_PKICONF                     122
#  define ossl_CMP_R_ERROR_CREATING_POLLREP                     123
#  define ossl_CMP_R_ERROR_CREATING_POLLREQ                     124
#  define ossl_CMP_R_ERROR_CREATING_RP                          125
#  define ossl_CMP_R_ERROR_CREATING_RR                          126
#  define ossl_CMP_R_ERROR_PARSING_PKISTATUS                    107
#  define ossl_CMP_R_ERROR_PROCESSING_MESSAGE                   158
#  define ossl_CMP_R_ERROR_PROTECTING_MESSAGE                   127
#  define ossl_CMP_R_ERROR_SETTING_CERTHASH                     128
#  define ossl_CMP_R_ERROR_UNEXPECTED_CERTCONF                  160
#  define ossl_CMP_R_ERROR_VALIDATING_PROTECTION                140
#  define ossl_CMP_R_ERROR_VALIDATING_SIGNATURE                 171
#  define ossl_CMP_R_FAILED_BUILDING_OWN_CHAIN                  164
#  define ossl_CMP_R_FAILED_EXTRACTING_PUBKEY                   141
#  define ossl_CMP_R_FAILURE_OBTAINING_RANDOM                   110
#  define ossl_CMP_R_FAIL_INFO_OUT_OF_RANGE                     129
#  define ossl_CMP_R_INVALID_ARGS                               100
#  define ossl_CMP_R_INVALID_OPTION                             174
#  define ossl_CMP_R_MISSING_CERTID                             165
#  define ossl_CMP_R_MISSING_KEY_INPUT_FOR_CREATING_PROTECTION  130
#  define ossl_CMP_R_MISSING_KEY_USAGE_DIGITALSIGNATURE         142
#  define ossl_CMP_R_MISSING_P10CSR                             121
#  define ossl_CMP_R_MISSING_PBM_SECRET                         166
#  define ossl_CMP_R_MISSING_PRIVATE_KEY                        131
#  define ossl_CMP_R_MISSING_PRIVATE_KEY_FOR_POPO               190
#  define ossl_CMP_R_MISSING_PROTECTION                         143
#  define ossl_CMP_R_MISSING_PUBLIC_KEY                         183
#  define ossl_CMP_R_MISSING_REFERENCE_CERT                     168
#  define ossl_CMP_R_MISSING_SECRET                             178
#  define ossl_CMP_R_MISSING_SENDER_IDENTIFICATION              111
#  define ossl_CMP_R_MISSING_TRUST_ANCHOR                       179
#  define ossl_CMP_R_MISSING_TRUST_STORE                        144
#  define ossl_CMP_R_MULTIPLE_REQUESTS_NOT_SUPPORTED            161
#  define ossl_CMP_R_MULTIPLE_RESPONSES_NOT_SUPPORTED           170
#  define ossl_CMP_R_MULTIPLE_SAN_SOURCES                       102
#  define ossl_CMP_R_NO_STDIO                                   194
#  define ossl_CMP_R_NO_SUITABLE_SENDER_CERT                    145
#  define ossl_CMP_R_NULL_ARGUMENT                              103
#  define ossl_CMP_R_PKIBODY_ERROR                              146
#  define ossl_CMP_R_PKISTATUSINFO_NOT_FOUND                    132
#  define ossl_CMP_R_POLLING_FAILED                             172
#  define ossl_CMP_R_POTENTIALLY_INVALID_CERTIFICATE            147
#  define ossl_CMP_R_RECEIVED_ERROR                             180
#  define ossl_CMP_R_RECIPNONCE_UNMATCHED                       148
#  define ossl_CMP_R_REQUEST_NOT_ACCEPTED                       149
#  define ossl_CMP_R_REQUEST_REJECTED_BY_SERVER                 182
#  define ossl_CMP_R_SENDER_GENERALNAME_TYPE_NOT_SUPPORTED      150
#  define ossl_CMP_R_SRVCERT_DOES_NOT_VALIDATE_MSG              151
#  define ossl_CMP_R_TOTAL_TIMEOUT                              184
#  define ossl_CMP_R_TRANSACTIONID_UNMATCHED                    152
#  define ossl_CMP_R_TRANSFER_ERROR                             159
#  define ossl_CMP_R_UNEXPECTED_PKIBODY                         133
#  define ossl_CMP_R_UNEXPECTED_PKISTATUS                       185
#  define ossl_CMP_R_UNEXPECTED_PVNO                            153
#  define ossl_CMP_R_UNKNOWN_ALGORITHM_ID                       134
#  define ossl_CMP_R_UNKNOWN_CERT_TYPE                          135
#  define ossl_CMP_R_UNKNOWN_PKISTATUS                          186
#  define ossl_CMP_R_UNSUPPORTED_ALGORITHM                      136
#  define ossl_CMP_R_UNSUPPORTED_KEY_TYPE                       137
#  define ossl_CMP_R_UNSUPPORTED_PROTECTION_ALG_DHBASEDMAC      154
#  define ossl_CMP_R_VALUE_TOO_LARGE                            175
#  define ossl_CMP_R_VALUE_TOO_SMALL                            177
#  define ossl_CMP_R_WRONG_ALGORITHM_OID                        138
#  define ossl_CMP_R_WRONG_CERTID                               189
#  define ossl_CMP_R_WRONG_CERTID_IN_RP                         187
#  define ossl_CMP_R_WRONG_PBM_VALUE                            155
#  define ossl_CMP_R_WRONG_RP_COMPONENT_COUNT                   188
#  define ossl_CMP_R_WRONG_SERIAL_IN_RP                         173

# endif
#endif
