/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_COMPERR_H
# define ossl_OPENSSL_COMPERR_H
# pragma once

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/cryptoerr_legacy.h"


# ifndef ossl_OPENSSL_NO_COMP


/*
 * COMP reason codes.
 */
#  define ossl_COMP_R_ZLIB_DEFLATE_ERROR                        99
#  define ossl_COMP_R_ZLIB_INFLATE_ERROR                        100
#  define ossl_COMP_R_ZLIB_NOT_SUPPORTED                        101

# endif
#endif
