/*
 * WARNING: do not edit!
 * Generated by configdata.pm from ../../../openssl/source/Configurations/common0.tmpl, ../../../openssl/source/Configurations/unix-Makefile.tmpl
 * via Makefile.in
 *
 * Copyright 2016-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_CONFIGURATION_H
# define ossl_OPENSSL_CONFIGURATION_H
# pragma once

# ifdef  __cplusplus
extern "C" {
# endif

# ifdef ossl_OPENSSL_ALGORITHM_DEFINES
#  error ossl_OPENSSL_ALGORITHM_DEFINES no longer supported
# endif

/*
 * OpenSSL was configured with the following options:
 */

# define ossl_OPENSSL_CONFIGURED_API 30000
# ifndef ossl_OPENSSL_RAND_SEED_OS
#  define ossl_OPENSSL_RAND_SEED_OS
# endif
# ifndef ossl_OPENSSL_THREADS
#  define ossl_OPENSSL_THREADS
# endif
# ifndef ossl_OPENSSL_NO_ACVP_TESTS
#  define ossl_OPENSSL_NO_ACVP_TESTS
# endif
# ifndef ossl_OPENSSL_NO_ASAN
#  define ossl_OPENSSL_NO_ASAN
# endif
# ifndef ossl_OPENSSL_NO_CRYPTO_MDEBUG
#  define ossl_OPENSSL_NO_CRYPTO_MDEBUG
# endif
# ifndef ossl_OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
#  define ossl_OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
# endif
# ifndef ossl_OPENSSL_NO_DEVCRYPTOENG
#  define ossl_OPENSSL_NO_DEVCRYPTOENG
# endif
# ifndef ossl_OPENSSL_NO_EC_NISTP_64_GCC_128
#  define ossl_OPENSSL_NO_EC_NISTP_64_GCC_128
# endif
# ifndef ossl_OPENSSL_NO_EGD
#  define ossl_OPENSSL_NO_EGD
# endif
# ifndef ossl_OPENSSL_NO_EXTERNAL_TESTS
#  define ossl_OPENSSL_NO_EXTERNAL_TESTS
# endif
# ifndef ossl_OPENSSL_NO_FIPS_SECURITYCHECKS
#  define ossl_OPENSSL_NO_FIPS_SECURITYCHECKS
# endif
# ifndef ossl_OPENSSL_NO_FUZZ_AFL
#  define ossl_OPENSSL_NO_FUZZ_AFL
# endif
# ifndef ossl_OPENSSL_NO_FUZZ_LIBFUZZER
#  define ossl_OPENSSL_NO_FUZZ_LIBFUZZER
# endif
# ifndef ossl_OPENSSL_NO_KTLS
#  define ossl_OPENSSL_NO_KTLS
# endif
# ifndef ossl_OPENSSL_NO_MD2
#  define ossl_OPENSSL_NO_MD2
# endif
# ifndef ossl_OPENSSL_NO_MSAN
#  define ossl_OPENSSL_NO_MSAN
# endif
# ifndef ossl_OPENSSL_NO_RC5
#  define ossl_OPENSSL_NO_RC5
# endif
# ifndef ossl_OPENSSL_NO_SCTP
#  define ossl_OPENSSL_NO_SCTP
# endif
# ifndef ossl_OPENSSL_NO_SSL3
#  define ossl_OPENSSL_NO_SSL3
# endif
# ifndef ossl_OPENSSL_NO_SSL3_METHOD
#  define ossl_OPENSSL_NO_SSL3_METHOD
# endif
# ifndef ossl_OPENSSL_NO_TRACE
#  define ossl_OPENSSL_NO_TRACE
# endif
# ifndef ossl_OPENSSL_NO_UBSAN
#  define ossl_OPENSSL_NO_UBSAN
# endif
# ifndef ossl_OPENSSL_NO_UNIT_TEST
#  define ossl_OPENSSL_NO_UNIT_TEST
# endif
# ifndef ossl_OPENSSL_NO_UPLINK
#  define ossl_OPENSSL_NO_UPLINK
# endif
# ifndef ossl_OPENSSL_NO_WEAK_SSL_CIPHERS
#  define ossl_OPENSSL_NO_WEAK_SSL_CIPHERS
# endif
# ifndef ossl_OPENSSL_NO_STATIC_ENGINE
#  define ossl_OPENSSL_NO_STATIC_ENGINE
# endif


/* Generate 80386 code? */
# undef ossl_I386_ONLY

/*
 * The following are cipher-specific, but are part of the public API.
 */
# if !defined(ossl_OPENSSL_SYS_UEFI)
#  undef ossl_BN_LLONG
/* Only one for the following should be defined */
#  define ossl_SIXTY_FOUR_BIT_LONG
#  undef ossl_SIXTY_FOUR_BIT
#  undef ossl_THIRTY_TWO_BIT
# endif

# define ossl_RC4_INT unsigned int

# ifdef  __cplusplus
}
# endif

#endif                          /* ossl_OPENSSL_CONFIGURATION_H */
