/*
 * WARNING: do not edit!
 * Generated by Makefile from ../../../openssl/source/include/openssl/srp.h.in
 *
 * Copyright 2004-2021 The OpenSSL Project Authors. All Rights Reserved.
 * Copyright (c) 2004, EdelKey Project. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 *
 * Originally written by Christophe Renou and Peter Sylvester,
 * for the EdelKey project.
 */



#ifndef ossl_OPENSSL_SRP_H
# define ossl_OPENSSL_SRP_H
# pragma once

# include "ossl/openssl/macros.h"
# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0
#  define ossl_HEADER_SRP_H
# endif

#include "ossl/openssl/opensslconf.h"

#ifndef ossl_OPENSSL_NO_SRP
# include <stdio.h>
# include <string.h>
# include "ossl/openssl/safestack.h"
# include "ossl/openssl/bn.h"
# include "ossl/openssl/crypto.h"

# ifdef  __cplusplus
extern "C" {
# endif

# ifndef ossl_OPENSSL_NO_DEPRECATED_3_0

typedef struct ossl_SRP_gN_cache_st {
    char *b64_bn;
    ossl_BIGNUM *bn;
} ossl_SRP_gN_cache;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_SRP_gN_cache, ossl_SRP_gN_cache, ossl_SRP_gN_cache)
#define ossl_sk_SRP_gN_cache_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_SRP_gN_cache_sk_type(sk))
#define ossl_sk_SRP_gN_cache_value(sk, idx) ((ossl_SRP_gN_cache *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_SRP_gN_cache_sk_type(sk), (idx)))
#define ossl_sk_SRP_gN_cache_new(cmp) ((ossl_STACK_OF(ossl_SRP_gN_cache) *)ossl_OPENSSL_sk_new(ossl_ossl_check_SRP_gN_cache_compfunc_type(cmp)))
#define ossl_sk_SRP_gN_cache_new_null() ((ossl_STACK_OF(ossl_SRP_gN_cache) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_SRP_gN_cache_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_SRP_gN_cache) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_SRP_gN_cache_compfunc_type(cmp), (n)))
#define ossl_sk_SRP_gN_cache_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_SRP_gN_cache_sk_type(sk), (n))
#define ossl_sk_SRP_gN_cache_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_SRP_gN_cache_sk_type(sk))
#define ossl_sk_SRP_gN_cache_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_SRP_gN_cache_sk_type(sk))
#define ossl_sk_SRP_gN_cache_delete(sk, i) ((ossl_SRP_gN_cache *)ossl_OPENSSL_sk_delete(ossl_ossl_check_SRP_gN_cache_sk_type(sk), (i)))
#define ossl_sk_SRP_gN_cache_delete_ptr(sk, ptr) ((ossl_SRP_gN_cache *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr)))
#define ossl_sk_SRP_gN_cache_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr))
#define ossl_sk_SRP_gN_cache_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr))
#define ossl_sk_SRP_gN_cache_pop(sk) ((ossl_SRP_gN_cache *)ossl_OPENSSL_sk_pop(ossl_ossl_check_SRP_gN_cache_sk_type(sk)))
#define ossl_sk_SRP_gN_cache_shift(sk) ((ossl_SRP_gN_cache *)ossl_OPENSSL_sk_shift(ossl_ossl_check_SRP_gN_cache_sk_type(sk)))
#define ossl_sk_SRP_gN_cache_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_SRP_gN_cache_sk_type(sk),ossl_ossl_check_SRP_gN_cache_freefunc_type(freefunc))
#define ossl_sk_SRP_gN_cache_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr), (idx))
#define ossl_sk_SRP_gN_cache_set(sk, idx, ptr) ((ossl_SRP_gN_cache *)ossl_OPENSSL_sk_set(ossl_ossl_check_SRP_gN_cache_sk_type(sk), (idx), ossl_ossl_check_SRP_gN_cache_type(ptr)))
#define ossl_sk_SRP_gN_cache_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr))
#define ossl_sk_SRP_gN_cache_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr))
#define ossl_sk_SRP_gN_cache_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_type(ptr), pnum)
#define ossl_sk_SRP_gN_cache_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_SRP_gN_cache_sk_type(sk))
#define ossl_sk_SRP_gN_cache_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_SRP_gN_cache_sk_type(sk))
#define ossl_sk_SRP_gN_cache_dup(sk) ((ossl_STACK_OF(ossl_SRP_gN_cache) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_SRP_gN_cache_sk_type(sk)))
#define ossl_sk_SRP_gN_cache_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_SRP_gN_cache) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_copyfunc_type(copyfunc), ossl_ossl_check_SRP_gN_cache_freefunc_type(freefunc)))
#define ossl_sk_SRP_gN_cache_set_cmp_func(sk, cmp) ((ossl_sk_SRP_gN_cache_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_SRP_gN_cache_sk_type(sk), ossl_ossl_check_SRP_gN_cache_compfunc_type(cmp)))



typedef struct ossl_SRP_user_pwd_st {
    /* Owned by us. */
    char *id;
    ossl_BIGNUM *s;
    ossl_BIGNUM *v;
    /* Not owned by us. */
    const ossl_BIGNUM *g;
    const ossl_BIGNUM *N;
    /* Owned by us. */
    char *info;
} ossl_SRP_user_pwd;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_SRP_user_pwd, ossl_SRP_user_pwd, ossl_SRP_user_pwd)
#define ossl_sk_SRP_user_pwd_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_SRP_user_pwd_sk_type(sk))
#define ossl_sk_SRP_user_pwd_value(sk, idx) ((ossl_SRP_user_pwd *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_SRP_user_pwd_sk_type(sk), (idx)))
#define ossl_sk_SRP_user_pwd_new(cmp) ((ossl_STACK_OF(ossl_SRP_user_pwd) *)ossl_OPENSSL_sk_new(ossl_ossl_check_SRP_user_pwd_compfunc_type(cmp)))
#define ossl_sk_SRP_user_pwd_new_null() ((ossl_STACK_OF(ossl_SRP_user_pwd) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_SRP_user_pwd_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_SRP_user_pwd) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_SRP_user_pwd_compfunc_type(cmp), (n)))
#define ossl_sk_SRP_user_pwd_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_SRP_user_pwd_sk_type(sk), (n))
#define ossl_sk_SRP_user_pwd_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_SRP_user_pwd_sk_type(sk))
#define ossl_sk_SRP_user_pwd_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_SRP_user_pwd_sk_type(sk))
#define ossl_sk_SRP_user_pwd_delete(sk, i) ((ossl_SRP_user_pwd *)ossl_OPENSSL_sk_delete(ossl_ossl_check_SRP_user_pwd_sk_type(sk), (i)))
#define ossl_sk_SRP_user_pwd_delete_ptr(sk, ptr) ((ossl_SRP_user_pwd *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr)))
#define ossl_sk_SRP_user_pwd_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr))
#define ossl_sk_SRP_user_pwd_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr))
#define ossl_sk_SRP_user_pwd_pop(sk) ((ossl_SRP_user_pwd *)ossl_OPENSSL_sk_pop(ossl_ossl_check_SRP_user_pwd_sk_type(sk)))
#define ossl_sk_SRP_user_pwd_shift(sk) ((ossl_SRP_user_pwd *)ossl_OPENSSL_sk_shift(ossl_ossl_check_SRP_user_pwd_sk_type(sk)))
#define ossl_sk_SRP_user_pwd_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_SRP_user_pwd_sk_type(sk),ossl_ossl_check_SRP_user_pwd_freefunc_type(freefunc))
#define ossl_sk_SRP_user_pwd_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr), (idx))
#define ossl_sk_SRP_user_pwd_set(sk, idx, ptr) ((ossl_SRP_user_pwd *)ossl_OPENSSL_sk_set(ossl_ossl_check_SRP_user_pwd_sk_type(sk), (idx), ossl_ossl_check_SRP_user_pwd_type(ptr)))
#define ossl_sk_SRP_user_pwd_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr))
#define ossl_sk_SRP_user_pwd_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr))
#define ossl_sk_SRP_user_pwd_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_type(ptr), pnum)
#define ossl_sk_SRP_user_pwd_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_SRP_user_pwd_sk_type(sk))
#define ossl_sk_SRP_user_pwd_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_SRP_user_pwd_sk_type(sk))
#define ossl_sk_SRP_user_pwd_dup(sk) ((ossl_STACK_OF(ossl_SRP_user_pwd) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_SRP_user_pwd_sk_type(sk)))
#define ossl_sk_SRP_user_pwd_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_SRP_user_pwd) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_copyfunc_type(copyfunc), ossl_ossl_check_SRP_user_pwd_freefunc_type(freefunc)))
#define ossl_sk_SRP_user_pwd_set_cmp_func(sk, cmp) ((ossl_sk_SRP_user_pwd_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_SRP_user_pwd_sk_type(sk), ossl_ossl_check_SRP_user_pwd_compfunc_type(cmp)))


ossl_OSSL_DEPRECATEDIN_3_0
ossl_SRP_user_pwd *ossl_SRP_user_pwd_new(void);
ossl_OSSL_DEPRECATEDIN_3_0
void ossl_SRP_user_pwd_free(ossl_SRP_user_pwd *user_pwd);

ossl_OSSL_DEPRECATEDIN_3_0
void ossl_SRP_user_pwd_set_gN(ossl_SRP_user_pwd *user_pwd, const ossl_BIGNUM *g,
                         const ossl_BIGNUM *N);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_user_pwd_set1_ids(ossl_SRP_user_pwd *user_pwd, const char *id,
                          const char *info);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_user_pwd_set0_sv(ossl_SRP_user_pwd *user_pwd, ossl_BIGNUM *s, ossl_BIGNUM *v);

typedef struct ossl_SRP_VBASE_st {
    ossl_STACK_OF(ossl_SRP_user_pwd) *users_pwd;
    ossl_STACK_OF(ossl_SRP_gN_cache) *gN_cache;
/* to simulate a user */
    char *seed_key;
    const ossl_BIGNUM *default_g;
    const ossl_BIGNUM *default_N;
} ossl_SRP_VBASE;

/*
 * Internal structure storing N and g pair
 */
typedef struct ossl_SRP_gN_st {
    char *id;
    const ossl_BIGNUM *g;
    const ossl_BIGNUM *N;
} ossl_SRP_gN;
ossl_SKM_DEFINE_STACK_OF_INTERNAL(ossl_SRP_gN, ossl_SRP_gN, ossl_SRP_gN)
#define ossl_sk_SRP_gN_num(sk) ossl_OPENSSL_sk_num(ossl_ossl_check_const_SRP_gN_sk_type(sk))
#define ossl_sk_SRP_gN_value(sk, idx) ((ossl_SRP_gN *)ossl_OPENSSL_sk_value(ossl_ossl_check_const_SRP_gN_sk_type(sk), (idx)))
#define ossl_sk_SRP_gN_new(cmp) ((ossl_STACK_OF(ossl_SRP_gN) *)ossl_OPENSSL_sk_new(ossl_ossl_check_SRP_gN_compfunc_type(cmp)))
#define ossl_sk_SRP_gN_new_null() ((ossl_STACK_OF(ossl_SRP_gN) *)ossl_OPENSSL_sk_new_null())
#define ossl_sk_SRP_gN_new_reserve(cmp, n) ((ossl_STACK_OF(ossl_SRP_gN) *)ossl_OPENSSL_sk_new_reserve(ossl_ossl_check_SRP_gN_compfunc_type(cmp), (n)))
#define ossl_sk_SRP_gN_reserve(sk, n) ossl_OPENSSL_sk_reserve(ossl_ossl_check_SRP_gN_sk_type(sk), (n))
#define ossl_sk_SRP_gN_free(sk) ossl_OPENSSL_sk_free(ossl_ossl_check_SRP_gN_sk_type(sk))
#define ossl_sk_SRP_gN_zero(sk) ossl_OPENSSL_sk_zero(ossl_ossl_check_SRP_gN_sk_type(sk))
#define ossl_sk_SRP_gN_delete(sk, i) ((ossl_SRP_gN *)ossl_OPENSSL_sk_delete(ossl_ossl_check_SRP_gN_sk_type(sk), (i)))
#define ossl_sk_SRP_gN_delete_ptr(sk, ptr) ((ossl_SRP_gN *)ossl_OPENSSL_sk_delete_ptr(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr)))
#define ossl_sk_SRP_gN_push(sk, ptr) ossl_OPENSSL_sk_push(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr))
#define ossl_sk_SRP_gN_unshift(sk, ptr) ossl_OPENSSL_sk_unshift(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr))
#define ossl_sk_SRP_gN_pop(sk) ((ossl_SRP_gN *)ossl_OPENSSL_sk_pop(ossl_ossl_check_SRP_gN_sk_type(sk)))
#define ossl_sk_SRP_gN_shift(sk) ((ossl_SRP_gN *)ossl_OPENSSL_sk_shift(ossl_ossl_check_SRP_gN_sk_type(sk)))
#define ossl_sk_SRP_gN_pop_free(sk, freefunc) ossl_OPENSSL_sk_pop_free(ossl_ossl_check_SRP_gN_sk_type(sk),ossl_ossl_check_SRP_gN_freefunc_type(freefunc))
#define ossl_sk_SRP_gN_insert(sk, ptr, idx) ossl_OPENSSL_sk_insert(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr), (idx))
#define ossl_sk_SRP_gN_set(sk, idx, ptr) ((ossl_SRP_gN *)ossl_OPENSSL_sk_set(ossl_ossl_check_SRP_gN_sk_type(sk), (idx), ossl_ossl_check_SRP_gN_type(ptr)))
#define ossl_sk_SRP_gN_find(sk, ptr) ossl_OPENSSL_sk_find(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr))
#define ossl_sk_SRP_gN_find_ex(sk, ptr) ossl_OPENSSL_sk_find_ex(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr))
#define ossl_sk_SRP_gN_find_all(sk, ptr, pnum) ossl_OPENSSL_sk_find_all(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_type(ptr), pnum)
#define ossl_sk_SRP_gN_sort(sk) ossl_OPENSSL_sk_sort(ossl_ossl_check_SRP_gN_sk_type(sk))
#define ossl_sk_SRP_gN_is_sorted(sk) ossl_OPENSSL_sk_is_sorted(ossl_ossl_check_const_SRP_gN_sk_type(sk))
#define ossl_sk_SRP_gN_dup(sk) ((ossl_STACK_OF(ossl_SRP_gN) *)ossl_OPENSSL_sk_dup(ossl_ossl_check_const_SRP_gN_sk_type(sk)))
#define ossl_sk_SRP_gN_deep_copy(sk, copyfunc, freefunc) ((ossl_STACK_OF(ossl_SRP_gN) *)ossl_OPENSSL_sk_deep_copy(ossl_ossl_check_const_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_copyfunc_type(copyfunc), ossl_ossl_check_SRP_gN_freefunc_type(freefunc)))
#define ossl_sk_SRP_gN_set_cmp_func(sk, cmp) ((ossl_sk_SRP_gN_compfunc)ossl_OPENSSL_sk_set_cmp_func(ossl_ossl_check_SRP_gN_sk_type(sk), ossl_ossl_check_SRP_gN_compfunc_type(cmp)))



ossl_OSSL_DEPRECATEDIN_3_0
ossl_SRP_VBASE *ossl_SRP_VBASE_new(char *seed_key);
ossl_OSSL_DEPRECATEDIN_3_0
void ossl_SRP_VBASE_free(ossl_SRP_VBASE *vb);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_VBASE_init(ossl_SRP_VBASE *vb, char *verifier_file);

ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_VBASE_add0_user(ossl_SRP_VBASE *vb, ossl_SRP_user_pwd *user_pwd);

/* NOTE: unlike in ossl_SRP_VBASE_get_by_user, caller owns the returned pointer.*/
ossl_OSSL_DEPRECATEDIN_3_0
ossl_SRP_user_pwd *ossl_SRP_VBASE_get1_by_user(ossl_SRP_VBASE *vb, char *username);

ossl_OSSL_DEPRECATEDIN_3_0
char *ossl_SRP_create_verifier_ex(const char *user, const char *pass, char **salt,
                             char **verifier, const char *N, const char *g,
                             ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_OSSL_DEPRECATEDIN_3_0
char *ossl_SRP_create_verifier(const char *user, const char *pass, char **salt,
                          char **verifier, const char *N, const char *g);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_create_verifier_BN_ex(const char *user, const char *pass, ossl_BIGNUM **salt,
                              ossl_BIGNUM **verifier, const ossl_BIGNUM *N,
                              const ossl_BIGNUM *g, ossl_OSSL_LIB_CTX *libctx,
                              const char *propq);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_create_verifier_BN(const char *user, const char *pass, ossl_BIGNUM **salt,
                           ossl_BIGNUM **verifier, const ossl_BIGNUM *N,
                           const ossl_BIGNUM *g);

#  define ossl_SRP_NO_ERROR 0
#  define ossl_SRP_ERR_VBASE_INCOMPLETE_FILE 1
#  define ossl_SRP_ERR_VBASE_BN_LIB 2
#  define ossl_SRP_ERR_OPEN_FILE 3
#  define ossl_SRP_ERR_MEMORY 4

#  define ossl_DB_srptype      0
#  define ossl_DB_srpverifier  1
#  define ossl_DB_srpsalt      2
#  define ossl_DB_srpid        3
#  define ossl_DB_srpgN        4
#  define ossl_DB_srpinfo      5
#  undef  ossl_DB_NUMBER
#  define ossl_DB_NUMBER       6

#  define ossl_DB_SRP_INDEX    'I'
#  define ossl_DB_SRP_VALID    'V'
#  define ossl_DB_SRP_REVOKED  'R'
#  define ossl_DB_SRP_MODIF    'v'

/* see srp.c */
ossl_OSSL_DEPRECATEDIN_3_0
char *ossl_SRP_check_known_gN_param(const ossl_BIGNUM *g, const ossl_BIGNUM *N);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_SRP_gN *ossl_SRP_get_default_gN(const char *id);

/* server side .... */
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_server_key(const ossl_BIGNUM *A, const ossl_BIGNUM *v, const ossl_BIGNUM *u,
                            const ossl_BIGNUM *b, const ossl_BIGNUM *N);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_B_ex(const ossl_BIGNUM *b, const ossl_BIGNUM *N, const ossl_BIGNUM *g,
                      const ossl_BIGNUM *v, ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_B(const ossl_BIGNUM *b, const ossl_BIGNUM *N, const ossl_BIGNUM *g,
                   const ossl_BIGNUM *v);

ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_Verify_A_mod_N(const ossl_BIGNUM *A, const ossl_BIGNUM *N);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_u_ex(const ossl_BIGNUM *A, const ossl_BIGNUM *B, const ossl_BIGNUM *N,
                      ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_u(const ossl_BIGNUM *A, const ossl_BIGNUM *B, const ossl_BIGNUM *N);

/* client side .... */

ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_x_ex(const ossl_BIGNUM *s, const char *user, const char *pass,
                      ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_x(const ossl_BIGNUM *s, const char *user, const char *pass);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_A(const ossl_BIGNUM *a, const ossl_BIGNUM *N, const ossl_BIGNUM *g);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_client_key_ex(const ossl_BIGNUM *N, const ossl_BIGNUM *B, const ossl_BIGNUM *g,
                            const ossl_BIGNUM *x, const ossl_BIGNUM *a, const ossl_BIGNUM *u,
                            ossl_OSSL_LIB_CTX *libctx, const char *propq);
ossl_OSSL_DEPRECATEDIN_3_0
ossl_BIGNUM *ossl_SRP_Calc_client_key(const ossl_BIGNUM *N, const ossl_BIGNUM *B, const ossl_BIGNUM *g,
                            const ossl_BIGNUM *x, const ossl_BIGNUM *a, const ossl_BIGNUM *u);
ossl_OSSL_DEPRECATEDIN_3_0
int ossl_SRP_Verify_B_mod_N(const ossl_BIGNUM *B, const ossl_BIGNUM *N);

#  define ossl_SRP_MINIMAL_N 1024

# endif /* ossl_OPENSSL_NO_DEPRECATED_3_0 */

/* This method ignores the configured seed and fails for an unknown user. */
# ifndef ossl_OPENSSL_NO_DEPRECATED_1_1_0
ossl_OSSL_DEPRECATEDIN_1_1_0
ossl_SRP_user_pwd *ossl_SRP_VBASE_get_by_user(ossl_SRP_VBASE *vb, char *username);
# endif

# ifdef  __cplusplus
}
# endif
# endif

#endif
