/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef ossl_OPENSSL_TSERR_H
# define ossl_OPENSSL_TSERR_H
# pragma once

# include "ossl/openssl/opensslconf.h"
# include "ossl/openssl/symhacks.h"
# include "ossl/openssl/cryptoerr_legacy.h"


# ifndef ossl_OPENSSL_NO_TS


/*
 * TS reason codes.
 */
#  define ossl_TS_R_BAD_PKCS7_TYPE                              132
#  define ossl_TS_R_BAD_TYPE                                    133
#  define ossl_TS_R_CANNOT_LOAD_CERT                            137
#  define ossl_TS_R_CANNOT_LOAD_KEY                             138
#  define ossl_TS_R_CERTIFICATE_VERIFY_ERROR                    100
#  define ossl_TS_R_COULD_NOT_SET_ENGINE                        127
#  define ossl_TS_R_COULD_NOT_SET_TIME                          115
#  define ossl_TS_R_DETACHED_CONTENT                            134
#  define ossl_TS_R_ESS_ADD_SIGNING_CERT_ERROR                  116
#  define ossl_TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR               139
#  define ossl_TS_R_ESS_SIGNING_CERTIFICATE_ERROR               101
#  define ossl_TS_R_INVALID_NULL_POINTER                        102
#  define ossl_TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE          117
#  define ossl_TS_R_MESSAGE_IMPRINT_MISMATCH                    103
#  define ossl_TS_R_NONCE_MISMATCH                              104
#  define ossl_TS_R_NONCE_NOT_RETURNED                          105
#  define ossl_TS_R_NO_CONTENT                                  106
#  define ossl_TS_R_NO_TIME_STAMP_TOKEN                         107
#  define ossl_TS_R_PKCS7_ADD_SIGNATURE_ERROR                   118
#  define ossl_TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR                 119
#  define ossl_TS_R_PKCS7_TO_TS_TST_INFO_FAILED                 129
#  define ossl_TS_R_POLICY_MISMATCH                             108
#  define ossl_TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE      120
#  define ossl_TS_R_RESPONSE_SETUP_ERROR                        121
#  define ossl_TS_R_SIGNATURE_FAILURE                           109
#  define ossl_TS_R_THERE_MUST_BE_ONE_SIGNER                    110
#  define ossl_TS_R_TIME_SYSCALL_ERROR                          122
#  define ossl_TS_R_TOKEN_NOT_PRESENT                           130
#  define ossl_TS_R_TOKEN_PRESENT                               131
#  define ossl_TS_R_TSA_NAME_MISMATCH                           111
#  define ossl_TS_R_TSA_UNTRUSTED                               112
#  define ossl_TS_R_TST_INFO_SETUP_ERROR                        123
#  define ossl_TS_R_TS_DATASIGN                                 124
#  define ossl_TS_R_UNACCEPTABLE_POLICY                         125
#  define ossl_TS_R_UNSUPPORTED_MD_ALGORITHM                    126
#  define ossl_TS_R_UNSUPPORTED_VERSION                         113
#  define ossl_TS_R_VAR_BAD_VALUE                               135
#  define ossl_TS_R_VAR_LOOKUP_FAILURE                          136
#  define ossl_TS_R_WRONG_CONTENT_TYPE                          114

# endif
#endif
